### ISSUE TITLE
Loading webpage...

### ISSUE THREAD

**Issue by trsbox** [dr4fters/dr4ft#100]
Did the at latest gitpull and build with now errors and going to webpage just says "loading webpage". Any ideas?   Debian linux.

Trsbox.net:1337

**Comment by trsbox** [comment]
With **no errors.

**Comment by HerveH44** [comment]
Hi @trsbox,

If I understand you had a previous install of dr4ft and you manually upgraded it, via **git pull**. I think this could come from the configs which may be too old. 

I would suggest that you **do a backup of both config.*.js, which are config.client.js and config.server.js**, then run **node scripts/postinstall** from the root directory. Then the app should work. 

You may need then to rewrite the configs with your specific data, like site name or other infos. 

Hervé

**Comment by trsbox** [comment]
Tried what you said but still getting "loading webpage"

**Comment by HerveH44** [comment]
Okay, can you show what the console of your browser tells ? 

Before running the server, could you execute ```npm run postinstall``` ?

**Comment by trsbox** [comment]
After running that command it works...

**Comment by ZeldaZach** [comment]
Glad you figured this out!
