### ISSUE TITLE
MTGJSON post-processing fails with `TypeError: groupedCardsArray.map(...).flatMap is not a function`

### ISSUE THREAD

**Issue by serokellcao** [dr4fters/dr4ft#1006]
Expected behaviour: `npm i` installs dependencies and fetches the data from mtgjson.

Observed behaviour: `npm i` phase two fails with

> `2020-04-30 16:47:29,500+0300 [ERROR] [GLOBAL] Couldn't complete AllSets.json check : TypeError: groupedCardsArray.map(...).flatMap is not a function`

see [full log](https://github.com/dr4fters/dr4ft/files/4558693/dr4ft-issue-2.txt) attached.

Reproduced: `master` at the time of writing. I've started debugging it now.

**Comment by HerveH44** [comment]
I think you are using an old version of node which does not have Array.flatMap. It should be NodeJs > 11.0.0

Could you tell me what version of NodeJs you are using? ( using "node --version" for example)

**Comment by serokellcao** [comment]
I'm very sorry, I'll do that in a sec.

**Comment by HerveH44** [comment]
You're are completely right. I'll make a PR for that.
