### ISSUE TITLE
Feature request: Implement Glimpse Draft

### ISSUE THREAD

**Issue by serokellcao** [dr4fters/dr4ft#1007]
[Specification](http://turnonemagic.com/glimpse-drafting-best-way-draft-cube-2-4-players-title-shorter/) of Glimpse Draft format.

I'll implement it after I (or someone else) will fix #1006

**Comment by serokellcao** [comment]
You can follow the progress in [my fork](https://github.com/serokellcao/dr4ft/commits/master). I'll squash the flurry of commits before making a PR.

**Comment by serokellcao** [comment]
A question to @HerveH44 and/or @tooomm —

in `sendPack(pack)`, there is a line `this.send("pack", pack);`.

I understand that it sends this information over websocket to frontend, however, when I grep `frontend/`, I can't understand how it's handled:

```
λ grep -Rni '"pack"' frontend/
frontend/src/zones.js:3:export const ZONE_PACK = "pack";
frontend/src/zones.js:7:  [ZONE_PACK]: "Pack",
frontend/src/game/Game.jsx:66:    ? <Grid key={"pack"} zones={[ZONE_PACK]} />
frontend/src/game/Game.jsx:67:    : <div key={"pack"}/>;
```

Can you help me out a little bit with understanding of what's going on here?

**Comment by serokellcao** [comment]
Implemented first version. You can read the implementation story in the commit messages of my fork. 

Deployed here: http://thoughtflare.memorici.de:22019.

I need help with disabling bots for the format or tweaking bots in such way that they will pick following the correct protocol, not crashing drafts.

I also made a change where `meta()` is getting called without consideration for the next player being a bot, and it didn't break anything. Maybe I'm missing something, but tests pass, and drafts are as fast as before. Some comments about that would be appreciated.

As well as how to render timer selection in the game lobby (I'll figure the latter out on my own before making a PR, but I'd love to take a shortcut).

**Comment by HerveH44** [comment]
@serokellcao the events that you are looking for are all in the "frontend/src/events.js" file. Look for the function pass

**Comment by HerveH44** [comment]
I can't see how you "burn" cards in your implementation?

**Comment by serokellcao** [comment]
> I can't see how you "burn" cards in your implementation?

Using the obscure technique of mutable data structures and side effects:
https://github.com/serokellcao/dr4ft/commit/6470c05eaf67ca845cdfd307c1c388d6bb8f26c9#diff-1034785fb7388d6d0546ed761ab74ba0R191

**Comment by LotusWalker** [comment]
Any timeline on when Glimpse drafts will be implemented and testable on Dr4ft.info?
