### ISSUE TITLE
Feature request: Implement "Reserve Card" functionality

### ISSUE THREAD

**Issue by serokellcao** [dr4fters/dr4ft#1011]
Ditto.

Rationale: 

 1. Prevent misclicks;
 2. Provide formats with card burning (e.g. Glimpse Draft) with a nice UX with a click providing options to:
    a. Reserve to pick
    b. Reserve to burn

**Comment by tooomm** [comment]
"Reserve to pick" is already there, called `Autopick`. You have to click a card once to select/mark it for automatic pick once the timer runs up. A pick is never confirmed/done just by clicking a card for the first time.
So making a false pick can only happen if you double click a card instead single clicking it. Or clicking a card marked as `Autopick` again. Or did I get you wrong?

"Reserve to burn" sounds to be super specific and limited to the drafting mode "Glimpse Drafting".

**Comment by serokellcao** [comment]
Oh, I somehow missed that, sorry!
I think I'll work out a decent UX for Glimpse Drafting another way.

**Comment by tooomm** [comment]
Nevermind :)
