### ISSUE TITLE
Feature Request: Add MTGO + MTG Arena export options

### ISSUE THREAD

**Issue by nex3** [dr4fters/dr4ft#1016]
When exporting a draft deck to a txt format, split cards such as [Dead/Gone](https://scryfall.com/card/plc/113/dead-gone) are listed with two slashes and spaces between their names, like `Dead // Gone`. Magic Online can't parse this format, and will refuse to import decklists that use it. It wants split card names to have one slash and no spaces between the words, like `Dead/Gone`.

**Comment by serokellcao** [comment]
I think we should keep the default TXT format intact, and instead add more target formats.

Different applications want different formats. For instance, MTGA handles splits completely differently and doesn't know about its own "DLC" sets.

I wrote an exporter for MTGA: http://thoughtflare.memorici.de:22020 (the only exporter I know of that actually works), and I think that we should port the working exporters to JS, increasing the amount of target applications we can interact with.

Having a stable normal TXT format is crucial for that approach.

This is why, I'd say that this is not a bug, but rather a feature request ;)

**Comment by ZeldaZach** [comment]
I would call this a feature request too. All sub-systems (Scryfall, MTGJSON, etc) use the double slash approach. Will rebrand the ticket.

**Comment by serokellcao** [comment]
@nex3, if you can give me a spec for MODO, when I'll be adding MTGA export functionality later this week, I'll implement MODO export too!

**Comment by nex3** [comment]
As far as I know, Magic Online's text format import is exactly the same as the `.txt` format emitted today other than the way split cards are represented.

**Comment by serokellcao** [comment]
@nex3, can you please check how does MODO format adventure cards such as "Murderous Rider"?

Bike-shedding: I'd argue that export UX is anything but low-priority. The fact that I had to make http://thoughtflare.memorici.de:22020 for my play-group's convenience is an evidence. It's something that gets in the way of every single drafter who doesn't use Cockatrice to play the matches.

**Comment by nex3** [comment]
Adventures are formatted as just the creature's name, so `Murderous Rider`.

**Comment by serokellcao** [comment]
Thank you, just as I thought!

Will do my best to implement exports by Saturday!

**Comment by HerveH44** [comment]
Hi @serokellcao how is this issue going? Do you need extra help?

**Comment by dniemitalo** [comment]
The spec for MTGO export is almost the same as the existing text export format. Two changes are needed for the new format:
1) Change the slashes in split cards as outlined above: "fire // ice" becomes "fire/ice" 
(applies to Fuse and Aftermath cards in the same way; anything found with "is:split" in Scryfall)
2) Include a blank line before the sideboard. 

Adventure cards are formatted as "Murderous Rider" without the adventure spell name. Nothing different needed. Transform cards and flip cards are also fine. All three of those types use the single card name ("Nezumi Shortfang" or "Kessig Prowler" or "Beanstalk Giant")

**Comment by tooomm** [comment]
@serokellcao in case you don't get around to implement your working deck converter code from http://thoughtflare.memorici.de:22020 to dr4ft... can you give us some short notes on what is different to the format and what needs to be covered for proper MTGA export? [MTGO specs we have - thanks dniemitalo](https://github.com/dr4fters/dr4ft/issues/1016#issuecomment-657174615)

<br>

>I'd argue that export UX is anything but low-priority. (...) It's something that gets in the way of every single drafter who doesn't use Cockatrice to play the matches.

I can totally see that! Met many many people who happen to draft online in the recent months and they don't know of (or don't like) Cockatrice. There are several communities around web drafting which all play it out in MTGA for example.

**Comment by mixmix** [comment]
Started work on this here https://github.com/dr4fters/dr4ft/pull/1419
But have realised I'm going to need to change it to support all the other formats

**Comment by mixmix** [comment]
Summarising what people have said above:
- support following platform formats:
    - A. Cockatrice _(suffers from similar issues with // )_
    - B. MTGO
    - C. MTGA
- need to consider following types of // card:
    1. Split cards e.g. Dead // Gone
    2. Flip cards e.g. Nezumi Shortfang
    3. Transform cards e.g. Kessig Prowler
    4. Adventure cards e.g. Murderous Rider
    5.  ZNR 2-sided e.g. Riverglide Pathway

That's 15 different behaviours we need to know about ...

**Comment by mixmix** [comment]
Hey I am happy to build an exporter for arena.
Did anyone know anything about the format / want to help me test something?

Giving me an exported deck from arena would basically do it

**Comment by mixmix** [comment]
(Cockatrice and mtgo exporters are about done)

**Comment by tooomm** [comment]
❤️ 

Here is the pre-constructed GW Arena deck `To Adventure!`. Hope that helps!
```
Deck
1 Realm-Cloaked Giant (ELD) 26
1 Lovestruck Beast (ELD) 165
1 Temple of Plenty (THB) 248
4 Blossoming Sands (M21) 244
10 Plains (M21) 260
10 Forest (M21) 272
3 Faerie Guidemother (ELD) 11
3 Edgewall Innkeeper (ELD) 151
2 Silverflame Squire (ELD) 31
3 Shepherd of the Flock (ELD) 28
3 Garenbrig Squire (ELD) 158
3 Wandermare (ELD) 204
2 Mysterious Pathlighter (ELD) 22
2 Ardenvale Tactician (ELD) 5
2 Oakhame Ranger (ELD) 212
1 Giant Killer (ELD) 14
1 Ironscale Hydra (THB) 296
1 Victory's Envoy (THB) 289
1 Drannith Magistrate (IKO) 11
3 Banishing Light (THB) 4
1 Primal Might (M21) 197
2 Basri's Lieutenant (M21) 9
```

**Comment by mixmix** [comment]
Thanks @tooomm that helps a lot. It helps me see what they expect with adventure cards.

Can you try with some other cards like :


```
2 Nezumi Shortfang
1 Kessig Prowler
1 Refuse/Cooperate
1 Riverglide Pathway
1 Dead/Gone
1 Catch/Release

Sideboard

1 Who/What/When/Where/Why
```


**Specifically testing here :**
- flip cards
- transform cards
- split cards
- fuse cards
- aftermath cards
- modal_dfc (eg riverglide pathway)

Also, want to know how they demarcate the sideboard

**Comment by tooomm** [comment]
I see what I can do as I probably don't own all of those (or similar) card types (like aftermath from AKR), and MTGA itself is limited to certain newer sets still (starting with Ixalan).
Therefore old fun cards, flip or split/fuse cards are non-existent yet. But maybe there is a similar pattern to MTGO and we can still implement them ahead already.

All quick and dirty, sorry. Can't offer more at the moment. :)

```
Deck
1 Cragcrown Pathway (ZNR) 261
2 Hadana's Climb (RIX) 158
10 Forest (ANB) 112

Sideboard
1 Ajani's Welcome (M19) 6

```

**Comment by mixmix** [comment]
Huh, a triple slash! Thanks @tooomm

**Comment by tooomm** [comment]
After https://github.com/dr4fters/dr4ft/pull/1419 implemented this and #1454 spotted some issues in the .dek format, which got "solved" by switching to .txt format for MTGO in https://github.com/dr4fters/dr4ft/pull/1457...

...I realized now that Cockatrice uses a different, non xml style, format for .dek files.

An example deck saved as .dek in Cockatrice turns out like this:
```
1 Alrund, God of the Cosmos
1 Alrund's Epiphany
SB: 2 Disdainful Stroke
```

@LotusWalker Can you please check if that works in MTGO at all? Could be an easy way to support .dek and accomplish a distinct app assignment.
Or it's an issue with Cockatrice, which I then happily rise there. 👍

**Comment by LotusWalker** [comment]
Hi @tooomm, I just edited a .dek file as you noted above, and then tried importing into MTGO, but once imported the deck was empty in MTGO...so it didn’t pick up the individual cards.

**Comment by tooomm** [comment]
Hey, thanks for checking and coming back to me @LotusWalker!

Do you mind trying this with [Cockatrice](https://cockatrice.github.io/) for yourself (in case you use the free software) and check it directly? Just so that we can be sure it's not a fault on either end?
I just put some cards in a deck and hit `Save deck as`. You have to manually type out the extension to get the specific content though, they default to their own .cod format (xml based).


I do not own MTGO. :/

**Comment by LotusWalker** [comment]
Sorry, I don’t use Cockatrice.

**Comment by tooomm** [comment]
Ok, I bring it up in their repository (https://github.com/Cockatrice/Cockatrice) then. 👍
