### ISSUE TITLE
Bug: pick timeouts put the draft in a weird state

### ISSUE THREAD

**Issue by nex3** [dr4fters/dr4ft#1017]
While running test drafts, I've run into a few situations where the draft seems to enter a glitchy state when a drafter's picks time out. For example, I captured the following screenshot after starting a draft, making a few picks, and forgetting about it for an hour or so:

![image](https://user-images.githubusercontent.com/188/80930181-b02ad880-8d66-11ea-9e64-5849ea0fee92.png)

The consequences of the bugginess have ranged from "the draft continues as normal once an explicit pick is made" to "It shows 'Waiting for the next pack...' forever until I refresh the page" to "the entire draft vanishes after I refresh the page and I can't get it back".

Unfortunately I haven't been able to find a consistent means of reproducing the issue. As far as I can tell, it's *always* connected to picks timing out, and I believe none of those picks have ever had cards selected to be autopicked. In case it matters, this is my room configuration:

![image](https://user-images.githubusercontent.com/188/80930267-5545b100-8d67-11ea-84ab-d8cbe9381b12.png)

**Comment by serokellcao** [comment]
I think it might have something to do with the special treatment bot seats get.
When you're surrounded by bots, `meta()` call that refreshes and broadcasts the state won't get updated until you get the pack from the bot behind you.

I don't know if it matters, but in my implementation, I've removed the isBot check and no slowdown happened.

**Comment by ZeldaZach** [comment]
Will defer to @serokellcao on this one. If you're having no issues, can you link to a beta site so it can be re-ested?

**Comment by serokellcao** [comment]
I retract my statement BTW, I investigated `meta()` function thoroughly and how it's handled, I'm sure that it's not the issue.

It seems like some desync? Could it be that your computer went to sleep in the meantime and websocket dropped? @nex3

**Comment by nex3** [comment]
I was using my computer continuously throughout the period (although not necessarily the tab in question).

**Comment by HerveH44** [comment]
One part of the problem might come from the "add" event on the frontend. This event is triggered when the server makes the autopick for the player. Right now it does update the update pack state, just the "main" or "side" state. So the last pick of a pack can be shown even after the server picked a card for you. 

That should be easy to resolve, i'll make a PR for this. 

It may not explain all the weird behaviour @nex3 witnessed. Just so you know, a game exists only for a couple hours, after that the server will close it so if you stay on the page after that it may not respond as you would normally expect.

**Comment by HerveH44** [comment]
@nex3 Do you still experiment this kind of behaviour during draft ?

**Comment by nex3** [comment]
I haven't seen this in a long time.
