### ISSUE TITLE
Clarify download options

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1018]
Currently the deck download options in the dropdown are named `cod`, `json`, `mwdeck` and `txt` which is not super intuitive for all users and could be easier and more self explanatory like for example:
`Cockatrice (.cod)`, `JSON (.json)`, `Magic Workstation (.mwdeck)`, `Text file (.txt)`

This was created with https://github.com/dr4fters/dr4ft/issues/1016 in mind.
I don't even know the deck format type for MTGO (`MTG Online (.???)`).

**Comment by ZeldaZach** [comment]
MTGO is .dek

**Comment by mixmix** [comment]
This is a duplicate and should be resolved by pr I have open

**Comment by tooomm** [comment]
Yes, I will add this to the list of issues your PR solves.
