### ISSUE TITLE
Bug?: draft boosters not that random

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1025]
I'm using this issue to track a _possible bug_.

I've been doing a bunch of drafting of Ikoria with friends, and have been noticing this thing where I've been seeing duplicates of the same rares come up _a little more often_ than expected.

e.g. just now within the same draft (2 players, 6 bots): 
- a friend and I both first-picked a Kaheera in each of our pack 1
- we also each pulled a 2 Snapdacks
- later I pulled 2 Lurrus
- and 2 Sea-Dasher Octopus

I _think_ I've seen similar things in other games. These aren't impossible things to happen, .. it's just there are 68 rares / mythics in the set, so the odds of getting at least 2 packs of 24 with the same rare is not _that_ high, but it seems to happen every draft.

## Next step

I'm too lazy to do that probability calculation. I think I'm gonna look into the algorithm for pack generation

## Questions

Has anyone else had this recurring experience?

**Comment by taw** [comment]
IKO data looks totally fine as far as I can tell.

**Comment by HerveH44** [comment]
I've run some tests (generating 1000 boosters) and never found any bias in rare repartition. I would tend to close this issue unless some news facts come out.

**Comment by ZeldaZach** [comment]
Agreed. Personal Bias is always a thing.

**Comment by mixmix** [comment]
hey @HerveH44 I've written a script which consistently demonstrates a bug - namely pools which have way too many duplicate rares / mythics to be healthily random. (btw I think testing 1000 booster generations is a good idea, but that hides a problem at the pool level) 

```js
const { DraftNormal } = require('./backend/pool')

const playersLength = 8
const sets = ['IKO', 'IKO', 'IKO']

const pool = DraftNormal({ playersLength, sets })

const isSpecial = card => (
  card.rarity === 'Rare' ||
  card.rarity === 'Mythic'
)

const specials = pool.flatMap(pack => pack.filter(isSpecial))

const names = specials
  .sort((a, b) => b.number - a.number > 0 ? -1 : 1)
  .map(card => `${card.number} - ${card.name}`)

console.log(names)
```

```js
// exampe output
[ '66 - Sea-Dasher Octopus',
  '84 - Dirge Bat',
  '114 - Everquill Phoenix',
  '127 - Mythos of Vadrok',
  '141 - Yidaro, Wandering Monster',
  '155 - Gemrazer',
  "175 - Vivien, Monsters' Advocate",
  '181 - Chevill, Bane of Monsters',
  '186 - Frondland Felidar',
  '186 - Frondland Felidar',
  '189 - Genesis Ultimatum',
  '191 - Inspired Ultimatum',
  '201 - Quartzwood Crasher',
  '216 - Winota, Joiner of Forces',
  '221 - Gyruda, Doom of Depths',
  '221 - Gyruda, Doom of Depths',
  '224 - Kaheera, the Orphanguard',
  '224 - Kaheera, the Orphanguard',
  '227 - Lutri, the Spellchaser',
  '232 - Yorion, Sky Nomad',
  '232 - Yorion, Sky Nomad',
  '232 - Yorion, Sky Nomad',
  '233 - Zirda, the Dawnwaker',
  '248 - Indatha Triome' ]
```

**Comment by mixmix** [comment]
btw I think testing 1000 booster generations is a good idea, but that hides a problem at the pool level.

I wrote a script to test pools (https://gist.github.com/mixmix/b7555e9f64efd9ca2c2ef4c745d64937) and found that over 10,000 pools, 80% of those pools had 19-22 unqiue rares/ mythics in their pool.

Said another way : _most pools had at least 2-5 duplicate rares / mythics_.

(note that could mean e.g.  double / triple quadruple copies of the same rare, OR multiple doubles etc)

**Comment by tooomm** [comment]
Thanks for the further investigation and your input @mixmix!

**Comment by HerveH44** [comment]
Hi @mixmix, I'm not into statistics but could you tell me what is the probability that all rare slots of 24 boosters have different value?

**Comment by HerveH44** [comment]
Checking on this site : https://math.stackexchange.com/questions/56815/how-do-i-calculate-the-probability-of-getting-10-unique-members-of-a-set-given-r

I get the result for 55 rares (around what we have in ELD, 53 rares and 15 mythics - 1/8 possibility): 0.026% chance all 24 boosters rares are all different from each other. 

I would say that it goes along with what you found  - nearly all the time you'll have a duplicate.

**Comment by mixmix** [comment]
Yeah I've thought about doing the probability. I think it will be easier to
write a test with a set of numbers, which I plan to do next

One duplicate pair seems reasonable. It was 3-4 pairs regularly which
surprised me

**Comment by mixmix** [comment]
Ok here we go !

## Raw Number Simulation

This is based on picking 24 random numbers, and seeing how many unique numbers you get. 
Here's the results from 1e6 'pools' : 

uniques | proportion
--------|-----------
... | ...
15 | `░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0
16 | `░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0
17 | `▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.03
18 | `▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.09
19 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░` 0.17
20 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░` 0.24
21 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░` 0.23
22 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░` 0.14
23 | `▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.04
24 | `░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0


**Assumptions**:
- 53 rares, 15 mythics, where mythics are half as likely as rares (as suggested by `boosterRules.json` if I read right)
- ignore foils (for similicity)

## `./pools.js` Simulation 

This is the same results as in previous comment (3 IKO draft, 8 players), but visualised. This is the result of 1e5 pools (these simulations take significantly longer than raw numbers above)

15 | `░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0
16 | `░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0
17 | `░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.02
18 | `▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.06
19 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░` 0.14
20 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░` 0.21
21 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░` 0.23
22 | `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░` 0.18
23 | `▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.09
24 | `▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░` 0.03

(note you can have >24 unique rares in the pool because of foils, but this is very uncommon, so I've not graphed it) 
---

You can see the code I wrote to generate these here : https://github.com/mixmix/dr4ft/pull/1

**Comment by mixmix** [comment]
Here's the two overlayed as a diff : 
![dr4ft-diff](https://user-images.githubusercontent.com/2665886/82720851-7583e280-9d0b-11ea-86cd-559af9647ac3.png)

## summary

the `pool.js` probability curve actually sits _slightly higher_ (peak likelihood of  21 unique cards in a pool of 24) compared to my purely number based simulation (peak of 20).

so looks like my expectations don't align with actual probabilities.
**let's close this!**

**Comment by tooomm** [comment]
1e6 = 10^6?

**Comment by mixmix** [comment]
Yes. Sorry that's the JS for that

**Comment by HerveH44** [comment]
@mixmix thanks for the investigation
