### ISSUE TITLE
Client id exported to draft log as event id

### ISSUE THREAD

**Issue by oelarnes** [dr4fters/dr4ft#1035]
Hi, I've been familiarizing myself with this great project to customize it for a league I run.

I had some confusion about App.state.id vs the room id and it looks like I am not the only one!

getLog in events.js write App.state.id to your draftlog as 'Event #', but that value is a uid generated by the client to persist identity between sessions. Looking over logs, it is the case that this is a player identifier not an event identifier.

```
  getLog() {
    const {id, log, players, self, sets, gamesubtype, filename} = App.state;
    const isCube = /cube/.test(gamesubtype);
    const date = new Date().toISOString().slice(0, -5).replace(/-/g, "").replace(/:/g, "").replace("T", "_");
    const data = [
      `Event #: ${id}`,
      `Time: ${date}`,
      "Players:"
    ];
```

In general, the game id and title do not appear to be persisted to App.state nor does title appear to be accessible to the client at all.  I may be able to submit a pull for this issue in the coming days.

**Comment by tooomm** [comment]
Hi @oelarnes, thanks for opening this. Happy to see you like our project so far.
New PR's are always very welcome!

I'm curious what kind of league you plan on running? :)

**Comment by oelarnes** [comment]
I run an online cube league called "Online Cube League". We've been going strong for over a year and lately I've been using it as a motivator to learn some full-stack js. I have a GraphQL data platform I'm fairly happy with at https://github.com/oelarnes/ocl-data, and currently I'm working on shoving it onto dr4ft like a Parcelbeast onto a Glimmerbell. If you have any thoughts on whether it's interesting to make dr4ft more extensible or modular I'd be interested in that as well.

**Comment by HerveH44** [comment]
Hi, how would you like to use your data with dr4ft ?

About your issue, good catch, I don't think we save the gameId but that would make sense to save it, either in the gamestate or directly to the App.state. 

I would suggest to save it from the "frontend/src/router.js" where you can find it in the switch case "g". You could also just save it in the "initGameState" function too.
