### ISSUE TITLE
Bug: ELD split cards mismatch names/text

### ISSUE THREAD

**Issue by oelarnes** [dr4fters/dr4ft#1045]
This is an issue with how cards keyed by name are created, and results in incorrect or confusing oracle text being displayed in the draft. Here's what cubable_cards_by_name.json looks like for Murderous Rider:

    "murderous rider": {
        "uuid": "4797ff05-e346-529b-bdce-a038f5a4da2a",
        "name": "Murderous Rider",
        "names": [
            "Murderous Rider",
            "Swift End"
        ],
        "color": "Black",
        "colors": [
            "B"
        ],
        "colorIdentity": [
            "B"
        ],
        "setCode": "ELD",
        "scryfallId": "49c98e70-e8fe-4fea-b1d0-e7560780fda9",
        "cmc": 3,
        "number": "287",
        "type": "Instant",
        "manaCost": "{1}{B}{B}",
        "rarity": "Rare",
        "url": "https://api.scryfall.com/cards/49c98e70-e8fe-4fea-b1d0-e7560780fda9?format=image",
        "layout": "adventure",
        "isDoubleFaced": false,
        "flippedCardURL": "",
        "supertypes": [],
        "subtypes": [
            "Adventure"
        ],
        "text": "Destroy target creature or planeswalker. You lose 2 life. (Then exile this card. You may cast the creature later from exile.)",
        "frameEffects": [
            "showcase"
        ]
    },

Since cube cobra names Adventures by the card name, this results in only the adventure text appearing in text-only mode. Verified the bug manifests on the current deployment on dr4ft.info. Thanks.

**Comment by HerveH44** [comment]
Hi @oelarnes , actually you can find the problem not in "cubable_cards.json" which only maps cubable cards to uuid, but in "cards.json" which actually maps the uuid to a card representation. 

Where you want to work is on the file "backend/import/toBoosterCard.js" which maps a mtgjson card to an entry of cards.json. The problem with Adventure cards are that there text is actually split in 2 different cards. You could find more infos on their website or ask @ZeldaZach but what I can see is that you can find all the linked cards with the mtgjson property "otherFaceIds" which is an array of UUID of all the different side of the card. 

One of the possibilities you can do is have a special function inside the "toBoosterCard" function for the layout "adventure" that takes the rawCards and the current "otherFaceIds" from the mtgJsonCard. Inside this function, search the rawCards for the different UUID that are inside the otherFaceIds prop, map them with their property "text" and join them with a "\n---\n" or something similar. 

One thing though is that otherFaceIds may have 3 UUID which do not make sense to me. @ZeldaZach how do you fill the property "otherFaceIds" for adventure Cards?
