### ISSUE TITLE
move/include dependencies from old repos?

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#106]
In https://github.com/dr4fters/dr4ft/commit/775e20c Zach added some dependencies:

https://github.com/dr4fters/dr4ft/blob/master/package.json#L36
https://github.com/dr4fters/dr4ft/blob/master/package.json#L46

Wouldn't it be plausible to migrate or fork them to the dr4fters organization as well if we still rely on them?

**Comment by HerveH44** [comment]
yeah that's a really good idea. 

I'm currently working, or exercising more or less on react-redux to organize the code better. I found out that these projects already have maintained and better implementations (like lodash for exemple) to handle the same things. 

I'll see in a bit if I can merge things in this repo.

**Comment by ZeldaZach** [comment]
Done already
