### ISSUE TITLE
Bug: Dr4ft works on Chrome, but not FireFox

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#1093]
Latest build of master seems to work fine on Chrome, while a blank screen with three errors on firefox relating to booster version and loading in the game types

cc: @HerveH44

**Comment by mixmix** [comment]
reproduced this locally with commit : `3ccc465`

**Comment by mixmix** [comment]
scratch that `3ccc46532757310731bfe03e3a0b4ac20112a788 ` works totally fine for me.

Setup:
- node `12.6.3`
- `npm install && npm start` based setup (not docker) 
- firefox / chromium on linux, both running dr4ft happily

**Comment by ZeldaZach** [comment]
Feel free to reach out on Discord @mixmix https://mtgjson.com/discord so we can discuss this further

**Comment by tooomm** [comment]
dr4ft.info now works on Firefox (and Chromium) again.

https://github.com/dr4fters/dr4ft/pull/1100
