### ISSUE TITLE
smarter default file name for deck downloads

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#11]
Make the default deck name something like:
`gamemode_timestamp` or `date_localtimestamp_gamemode`, not sure if other informatin like playercount would be too helpful

So a filename could look like: `2017-04-23_17-21_sealed.txt` or `2017-04-23_draft_17-21.cod` (with the timestamp at the end)

The idea is get a useful filename which you don't have to change all the time, which isn't overwriting other files and actually provides useful information!
<br>

Edit: Even more important... just realized that the name is also baked into the .cod file and therefore shows up if you load the deck file in the deck editor, plus it can't really be changed there by the ordinary user:
```
  <deckname>16-04-2017_3</deckname>
```

**Comment by tritoch** [comment]
Fixed by https://github.com/dr4fters/dr4ft/commit/b848a15dce26fba26372ce1897674d43e5c81568

Default is now format-date-time.ext. Overrides cookie though.
