### ISSUE TITLE
dr4ft.info returns Service Unavailable (HTTPCode 503)

### ISSUE THREAD

**Issue by programming-wolf** [dr4fters/dr4ft#1105]
Hi folks, 
I have not been able to access https://dr4ft.info for the last few days because of error code 503. Maybe there is an error with your nginx configuration? I can access http://beta-dr4ft.herokuapp.com.

I wanted to use your website for a draft this week, is it ok if I use the beta version? 

Thanks,
Ben

**Comment by tooomm** [comment]
It's preferred when you use: https://stable-dr4ft.herokuapp.com/
It just got recently created for backup purposes. Thanks to @HerveH44 ❤️ 

beta-dr4ft should be more for testing and can change or break more frequently. It can still be a last resort if the others are not available, sure.

**Comment by programming-wolf** [comment]
Thanks for the fast reply, I'll do so.

**Comment by ZeldaZach** [comment]
We're back up. I changed the build process so hopefully it won't crash and go offline
