### ISSUE TITLE
Bug: Cube Cobra imports failing silently

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#1130]
Trying to import any cube doesn't update the list. I don't see any logs on my side.

**Comment by tooomm** [comment]
Same here on Firefox/Windows. No cards are imported to the list, nor does any error appear. If you tried an invalid/non-existent ID dr4ft used to show an error message at the very top for example. 
Tried with e.g. Cube ID [nicolaj](https://cubecobra.com/cube/overview/nicolaj)

@dekkerglen did anything change on your side?
