### ISSUE TITLE
Feature Request: Use keyrune to display set symbols

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1131]
## Detailed Description

As seen in recent design drafts, I like a lot how set icons are displayed in the drop down menu next to the set name for the set selection.

The keyrune package (https://www.npmjs.com/package/keyrune) should have the icons we need.

**Comment by mixmix** [comment]
This looks great. I'm a big fan of reading symbols over reading text

**Comment by mixmix** [comment]
Underway: https://github.com/dr4fters/dr4ft/pull/1474
