### ISSUE TITLE
Feature Request: Use MTGJSON v5 (v4 deprecated in 2020)

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1132]
## Detailed Description

MTGJSON v5 got released: https://mtgjson.com/changelog/version-5/#_5-0-0

Switch over to the new release for downloading and processing card data.
Also, the version information is integrated right into the card data download now. There is still a separate version file available (called meta now).
The former separate version file and the actual data file were often out of sync or delayed etc. Pulling that information right from the data file is more convenient for us, and ensures we always display the correct data.
<br>

**v4 is deprecated and only works until the end of 2020!** See https://mtgjson.com/changelog/version-4/

**Comment by taw** [comment]
Also my booster information is all in mtgjson v5 directly, so you won't need to use the other source, so it might simplify your life.
(it uses different format, as that's what mtgjson requested)
