### ISSUE TITLE
Feature Request: Use newest card versions for Cube drafts

### ISSUE THREAD

**Issue by dniemitalo** [dr4fters/dr4ft#1135]
Some cards are displayed with older card images that have obselete rules text. For example, Counterspell uses its image from Unlimited set, which was printed with the Interrupt type and outdated rules wording. 

Preferring the newest non-Masterpiece image from Scryfall would solve that issue.

**Comment by danielmartin0** [comment]
Oldest printings tend to work better for me given that I use a block cube.

**Comment by HerveH44** [comment]
It has been a long debate between which version of the card we should use. We decided to go with the oldest card existing.

**Comment by ZeldaZach** [comment]
We also have #1302 in the works, which will make it easier to customize your selections.
