### ISSUE TITLE
Bug: Sorting and image quality selector messed up in game

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1155]
**Webpage**: dr4ft.info

#1136 introduced a regression.

## Detailed Description

There used to be a nice horizontal radio button selection table.

## Further Information

Before #1136:
![Untitled](https://user-images.githubusercontent.com/9874850/88186104-0fe1a300-cc35-11ea-9cbe-b7f2435f4dbe.png)

After #1136 it loos like this:
(Don't be confused by the additional options, the above is from a Sealed game, while this is from a Draft with more settings)
![Untitled2](https://user-images.githubusercontent.com/9874850/88186110-11ab6680-cc35-11ea-9f0a-77670bb59175.png)

**Comment by mixmix** [comment]
Is the desired state to revert back to the original state, or was there a new design e should ask for?

**Comment by tooomm** [comment]
It seems obvious to go back to the initial look/behavior.
If you have a different idea feel free to share it here!

**Comment by mixmix** [comment]
I'll _draft_ something up. Working on this now

**Comment by mixmix** [comment]
here you go @ZeldaZach / @tooomm 

https://github.com/dr4fters/dr4ft/pull/1248

**Comment by mixmix** [comment]
Bump @tooomm @ZeldaZach

I think the failing tests are just linting
