### ISSUE TITLE
Pop-up prompt asking for player name

### ISSUE THREAD

**Issue by anoda9** [dr4fters/dr4ft#116]
When you join a draft or sealed room and your name is not set, there should be pop-up window prompting you to set your name. If that is too disruptive (or too likely to be blocked by people's adblockers), there should be some other reminder to set your username - big colored text saying "set your name in the chat", etc. 

There just needs to be some more obvious prompt for users to set their names. Other people in the draft shouldn't have to prompt them to set it.

**Comment by ZeldaZach** [comment]
I have no issues with the chat /name funct, but the clicking / editing was really nice and shouldn't have been removed

**Comment by HerveH44** [comment]
@anoda9 I tried to implement a solution, keeping an <input> for the player to change its name directly. It's available in the server http://dr4ft.info:8080. Could you try and tell me if that suits you?

**Comment by ZeldaZach** [comment]
Dupe #42
