### ISSUE TITLE
Feature Request: support drafting N cards per pick

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#1169]
## Detailed Description

With Double Masters, wizards has added that for the first pick of each pack, you get two cards. So it would be 2,1,1,1,...,1 totaling 15 cards selected in 14 picks. 

Goal is to support this draft pardim for double masters packs that get drafted. 

Stretch goal is A way to allow users to set how many cards per pick (input field would be a list of numbs like I had above)

**Comment by KainMorgen** [comment]
n-cards per pick becomes even more relevant with Command Legends being announced where you get to pick two cards everytime - not just for the first pick of the draft.

**Comment by UlyssesInvictus** [comment]
Hi -- just wondering if this is a feature that's still planned for support in time for Commander Legends (CMR)? I'm a dev myself, so if this is the kind of thing I can help support through PRs, let me know!

**Comment by lrawicz** [comment]
working on this

**Comment by pyrovoice** [comment]
@lrawicz Any update ? I could also lend a hand if needed

**Comment by lrawicz** [comment]
test my code, please

**Comment by natron2244** [comment]
I swear I saw this feature available on the site, but seems to be no longer there. Need any help with testing or coding?(Also a follow developer 😉 )

**Comment by lrawicz** [comment]
Haha yes, we had the feature avalible but we roll it back because we found and important bug.

I will fix the bug during the week.

**Comment by natron2244** [comment]
@lrawicz awesome to hear, I just found this site/project over! Amazing work! 😄

**Comment by LynxDove** [comment]
@lrawicz Hello! Just found Dr4ft.info and Im really impressed. Is there a way for me to find out when you have added multiple picks again? Im relatively new to using github so forgive me if this is a silly question.

**Comment by ZeldaZach** [comment]
@LynxDove I reverted the change on the dr4ft server, but not the GitHub project itself. When a fix for the multi-pick is re-introduced I'll build master upstream again

**Comment by natron2244** [comment]
Awesome work guys! 👏
