### ISSUE TITLE
Bug: 2XM boosters should have two rares. 

### ISSUE THREAD

**Issue by brantlc** [dr4fters/dr4ft#1176]
**Webpage**:

**Comment by tooomm** [comment]
The picking algorithm needs to change as well for 2XM packs, allowing to pick two cards out of the first pack.

**Comment by lover-of-memes** [comment]
This doesn't appear to be an issue with dr4ft. magic-sealed-data is working on fixing pack generation. If you spin up your own instance of dr4ft, it will have the recently modified rules that do include two rares (but it isn't perfect yet). [https://github.com/taw/magic-sealed-data/issues/3](https://github.com/taw/magic-sealed-data/issues/3)

**Comment by tooomm** [comment]
Interesting. The data in taw's repo is already available for 5 days... I thought dr4ft automatically updates those rules on a very regular basis and checks like once an hour?

It looks like in works now at dr4ft.info as well @lover-of-memes - only 4 days late. Maybe Zach had to rebuild manually for some reason or there is an issue with the updater.

**Comment by ZeldaZach** [comment]
This is addressed already
