### ISSUE TITLE
Scryfall direct image links need updates

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1195]
Direct `img.scryfall.com` links needs to get changed to API requests which forward to the image.
There are redirects in place for now, but not forever.

As far as I can tell, we have direct image links to old img.scryfall here:
https://github.com/dr4fters/dr4ft/blob/master/backend/import/xml/parser.spec.js

Announcement & information: https://scryfall.com/blog/upcoming-api-changes-to-scryfall-image-uris-and-download-uris-221

**Comment by HerveH44** [comment]
This is a value inside a test which do not get rendered by any browser. We are using the api everywhere else.
