### ISSUE TITLE
Missing Battlebond BBD for use with cube

### ISSUE THREAD

**Issue by impromptuu** [dr4fters/dr4ft#120]
Unable to start a room with a cube list with two BBD cards.

**Comment by HerveH44** [comment]
Hi, 
As a matter of fact, our card database mostly depends on MTGJSON work. It may be better to post an issue over there. As soon as the cards are in the Allsets.json it should solve itself! 

Hervé

**Comment by impromptuu** [comment]
As far as I'm aware, BBD has been on mtgjson since June, 2 2018.

**Comment by HerveH44** [comment]
Ok, so it should be the maintainer of the website that should take care of the update of the cards. What site do you use?

**Comment by tooomm** [comment]
Can you tell if the same problem exist with Commander sets? @impromptuu

**Comment by tooomm** [comment]
@impromptuu can you try if your cube with BBD cards works for you on this test page?
https://beta-dr4ft-pr-130.herokuapp.com/

**Comment by tooomm** [comment]
It looks like there is a problem indeed @HerveH44 

If you take [this cube](http://www.cubetutor.com/viewcube/5936) it'll work just fine.
But when you replace one card with a BBD card like [`Archfiend of Despair`](https://scryfall.com/card/bbd/44/archfiend-of-despair) it'll give you an error:

`invalid cards: archfiend of despair`

**Comment by HerveH44** [comment]
@impromptuu you can test there : https://beta-dr4ft-pr-138.herokuapp.com/ with your cube list?

**Comment by impromptuu** [comment]
@HerveH44 My cube list works for the link provided.

@tooomm I've found no issues with commander sets with a little testing.  Only the battlebond set.

**Comment by impromptuu** [comment]
@HerveH44 As for drafting, it should probably only show up in chaos, as there is no current way to implement battlebond-style drafting.  If that is even worth it with the need to implement the partners in packs the way Wizards did.

**Comment by tooomm** [comment]
Cool, thanks for letting us know.

Having real Two-Headed Giant drafts would require some more changes, true.

**Comment by tooomm** [comment]
Fixed in #169
