### ISSUE TITLE
please remove invocation art if possible

### ISSUE THREAD

**Issue by pj123123** [dr4fters/dr4ft#121]
this is more of a request than a problem. the invocation art is really hard to read. also it might be nice to just remove all of the masterpiece art if possible.

**Comment by HerveH44** [comment]
Hi, 

What do you mean by invocation art? Would you prefer to have past image art for the masterpieces?

**Comment by pj123123** [comment]
Yes, that is my preference and perhaps the preference of other. The Amonkhet Invocations is the name for the AHK and HOU lottery cards with the hieroglyph-esque font. Those cards are the hardest to read. So if you could program in the older more legible art that would be helpful. Cards like Opposition for example have the new art. But i would rather not see any masterpiece art. Thanks for your response!

**Comment by tooomm** [comment]
I think using the same art that shows up in real boosters is the most expected and most convenient way of handling it.
Probably that's the preference of most users, too. Newer players would likely be completely confused by the old art of some cards...

At best there could be an option - once such sets are involved - to disable the special art for all people in that draft, or on your site only if possible.
But that's unlikely to happen anytime soon.

**Comment by HerveH44** [comment]
@tooomm where should such option be in your point of view? Personnally, I would just disable the images from invocation when you cube, but keep them when you found them in the sets that have invocations... We don't have that kind of possibility I think from our setup unfortunately. I think I could check how to just delete the URL from invocations. They are in separated sets if I remember correctly, it should then be just a question of filtering the sets from updating our DB.

**Comment by pj123123** [comment]
I agree, it wouldnt make sense to see the urza's destiny card art and frame pop up in an AKH draft for Opposition. I wonder however how often AKH/HOU will be drafted in the future and if anyone drafting it would be a new player likely to get confused. It seems the upside of deleting invocations is high. No one likes them and they are hard to read. Also, there are cards like Hazoret that have a non invocation version which are only displayed in their invocation version. I think this creates confusion for new players, since they are likely to be more familiar with the regular card frame and art. My opinion is that invocations create more confusion than would be created if they were removed. And personally i still feel this is true for all the masterpieces.

**Comment by pj123123** [comment]
And ya, my preference is largely influenced by their presence in Cube Draft, which is very popular, and likely to be far more popular than drafting BFZ or KLD or AKH. I think this should be a consideration when moving forward since lottery cards are probably a thing of the past, and since most users prefer the more legible and familiar art of non masterpiece cards.

**Comment by tooomm** [comment]
@pj123123 can you test again here: https://beta-dr4ft-pr-136.herokuapp.com/

**Comment by pj123123** [comment]
I tested the vintage cube and it looks great! No masterpieces really looks good in that context.  I haven't drafted AKH in a while so i was just going off Hazoret always appearing as an invocation in cube. Thanks for your guys attention to this request.

**Comment by tooomm** [comment]
So cubes are fixed with https://github.com/dr4fters/dr4ft/pull/136 and don't show masterpiece arts anymore.

I'm still wondering about their wanted/expected appearance in BFZ/AKH/HOU... (without & with #136)

**Comment by tooomm** [comment]
Question stands if Masterpieces are broken for the containing sets, will open another issue.

@pj123123 keep in mind that we just do the code, no idea when websites will start using that "fix".
