### ISSUE TITLE
Bug: Brazen Borrower shows up incorrectly

### ISSUE THREAD

**Issue by Brokkoly** [dr4fters/dr4ft#1233]
**Webpage**: 
this was on https://dr4ft.info/#g/aedd0270-feca-11ea-abb0-990aa9ce7f01

![image](https://user-images.githubusercontent.com/14946087/94215599-c450ad00-fea2-11ea-8c51-04e5d95db10d.png)

Brazen borrower consistently breaks when drafting this cube: https://cubecobra.com/cube/list/5e87ece5df3ffb7493ed59bb.

Here is the game Id: https://dr4ft.info/#g/aedd0270-feca-11ea-abb0-990aa9ce7f01
## Detailed Description
Brazen Borrower was passed to me and the image did not load.

**Comment by LotusWalker** [comment]
I have Brazen Borrower in my cube as well and can confirm that the image loads properly for all our drafts, so I believe this issue has been fixed. Also using Chrome.
