### ISSUE TITLE
Bug: exporting split cards or double faced cards uses the wrong format

### ISSUE THREAD

**Issue by ebbit1q** [dr4fters/dr4ft#1242]
**Webpage**: www.dr4ft.info `Running Version: 853ccda (build 2020-09-28) - Using MTGJSON card data v4.7.0 (2020-09-28) and Magic Sealed Data booster rules commit 459802c`

----------------------------------------------------------------------------------

## Detailed Description

When you export any adventure card it'll be exported as just the creature name, while when you export any of the new double faced land cards it'll export with `//` in it. If you then export the decklist to cockatrice it'll show up as unrecognized.

If you then edit your decklist to have the proper cards your deck hash will no longer match, making competitive limited play with these cards impossible.

**Comment by ebbit1q** [comment]
the problematic layouts are "modal_dfc" and "adventure", see related ticket asking for the opposite because other locations use different formats https://github.com/dr4fters/dr4ft/issues/1045

**Comment by ZeldaZach** [comment]
Sounds like a real issue we should address

**Comment by HerveH44** [comment]
Is it still the case @ebbit1q . Last time I tried it worked correctly

**Comment by LotusWalker** [comment]
Yes, this is still a problem, but @mixmix is working on a fix for this in #1419

**Comment by mixmix** [comment]
Yep I'm writing right tests over this with example cards to hit edge cases.
It was super annoying getting es6 tests working, but think I've got it now...

**Comment by ebbit1q** [comment]
I technically fixed this from the other side https://github.com/Cockatrice/Cockatrice/pull/4131 makes cockatrice's import from plain text function smarter so it corrects these, while it finds the cards the deck hash will no longer match, making competitive play with these cards impossible

**Comment by mixmix** [comment]
I'm still going to fix the export as this covers mtgo too. 

Might need advice re deck hash. 
Ideally the deck hash would be derived from something more universal like uuids right?

**Comment by ebbit1q** [comment]
cockatrice's protocol is based on nothing but the card name, this abstraction allows it to play other card games and custom cards as well, while it's not perfect it makes sense to base the hash on the card names

**Comment by mixmix** [comment]
Makes sense. But then we need a canonical definition of what format card names should take everywhere

**Comment by ebbit1q** [comment]
cockatrice's system is simple, all cards that have a front and back face are split into two separate entities with their face's name as key, this includes kamigawa flip cards. all cards that have multiple names in the same orientation are combined with ` // ` in between.

example:
```
1 Everythingamajig (e)
1 Rune-Tail, Kitsune Ascendant
1 Who // What // When // Where // Why
1 Fire // Ice
1 Clearwater Pathway
```
this is a valid deck with the deck hash `3gvp9fad`

the everythingamajig is uuid `ca90bc5e-e448-47b7-a011-c19ac23c5eaa` with num `147e`

**Comment by mixmix** [comment]
And aftermath cards?
I'm guessing they are slashes?

**Comment by mixmix** [comment]
I'm writing really clear tests which will make all of this very easy to be explicit about btw

**Comment by ebbit1q** [comment]
of course, aftermath cards and adventures are on the same face, the only exception to this are the kamigawa flip cards in order to make them function like the double sided cards. cockatrice itself doesn't have tests for the deck hash function but the last time the deck hash function was changed was 2015, and we introduced the first test 2 months later.

**Comment by mixmix** [comment]
I'm a bit of a nerd and would kinda love to help draft a spec for that hash.

Sounds like it would be fairly easy, and could save a lot of pain. But I also have a lot on my wishlist of things to work on (and limited time)

**Comment by ebbit1q** [comment]
we could come with a new hash, the old one only has 5 bytes of complexity, since 2011 it's become easier to create a conflict there. on the other hand it all depends on the way cards are named in the database which would be a lot more sensitive to unexpected changes or even worse, new discrepancies could be introduced when new more "out there" card designs are introduced.

**Comment by mixmix** [comment]
Yeah a simple rule could by to always drop everything after any. Would need to confirm that they make cards uniquely enough like there isn't both
- fire
- fire // ice

I guess in Cockatrice that might be hard to guarentee if there are all sorts of cars sets going in. Hmm

**Comment by ebbit1q** [comment]
they don't make cards uniquely enough, we have multiple cards with a right side that has the same name of a different card right now and they could introduce a card with a left side that has the same name at any time.
I think cockatrice's current approach is appropriate for its internals here even though it means that when future card designs release they have to be adjusted to on a case by case basis.

**Comment by MotherofRuins** [comment]
This issue remains with meld cards from EMN, but not the other DFC cards from EMN.

**Comment by mixmix** [comment]
Can you give me an example card @MotherofRuins
?

Full card name, and desired output for your format would be good

**Comment by mixmix** [comment]
Got one

```
Graf rats // chittering host
```

Should come out as

```
Graf rats
```

Thanks for pointing out another edge case @MotherofRuins

**Comment by MotherofRuins** [comment]
All these:  https://scryfall.com/search?q=is%3Ameld

**Comment by mixmix** [comment]
Sweet. Yeah I've opened a pull request resolving this
