### ISSUE TITLE
Bug: Radio buttons in Setting invisible

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1243]
**Webpage**: www.dr4ft.info
**Browser**:  Firefox v80.0.1

![image](https://user-images.githubusercontent.com/2665886/95048972-51b6bb80-0745-11eb-8fc3-b9be68f4318e.png)

Can't see which option is selected for **Sort By** and **Card Image Quality** Not sure what it's supposed to look like, but this can't be it!

**Comment by tooomm** [comment]
Thanks for reporting, however it's already noted in https://github.com/dr4fters/dr4ft/issues/1155.

Closing as duplicate. Follow the other issue please @mixmix!
