### ISSUE TITLE
Bug: CMC sort broken in production

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1256]
**Webpage**: dr4ft.info
**Browser**: Firefox 81.0

----------------------------------------------------------------------------------

## Background Information

Draft options : draft, 3 packs Zendikar Rising, no timer
ID : https://dr4ft.info/#g/0c4abf40-0b70-11eb-9cae-55ac05459b51 (incomplete test game)

## Detailed Description

I start the draft, choose "sort by CMC" and I see this in my Main Deck section

![image](https://user-images.githubusercontent.com/2665886/95669518-3254de00-0bde-11eb-8530-a5a34534cdd3.png)

i.e. cards are not sorted by CMC, they're all filed under CMC 0. Actually neither is the Pack I'm picking from (order seems random). But then that's not such a problem.

----

I've tried reproducing this in a Dev env, but cannot... (same set, same draft options, same git commit). The only thing I can think of is that production hasn't had `npm i && npm run build` run on it .... but I can't see any mention of this issue in the git log.

**Comment by tooomm** [comment]
Checking the page it looks like there is just a custom set for Zendikar Rising that somebody uploaded as it's listed in the `Custom` section instead `Expansions`
Most likely the card information there is not complete or has wrong cmc data. There is no official ZNR data available at the draft page yet, sadly.

@ZeldaZach Can you please investigate why the updater didn't pick it up from MTGJSON? The automatic check and integration seems to not work properly. :(

**Comment by mixmix** [comment]
Yeah I wondered about this too, but then why did my local version have cmc working?
Perhaps the author created a broken custom upload initially but has since fixed it but dr4ft.info hasn't picked that up?

**Comment by mixmix** [comment]
Yeah I think your hypothesis about that broken upload is right, I'm not seeing any problem with core21

![Screenshot_20201012-020158_Firefox Focus.jpg](https://user-images.githubusercontent.com/2665886/95679390-031a8d00-0c2f-11eb-98e9-b1db790b3f37.jpg)

**Comment by tooomm** [comment]
With the redeployment of your recent PR, the correct ZNR data is now included from MTGJSON. @mixmix 

Works now as expected on dr4ft.info
