### ISSUE TITLE
Bug: Automatic update checks, fetching and integrating new card data doesn't work

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1257]
## Background Information

dr4ft used to check mtgjson data and automatically added new (non-spoiler) sets found there.

## Further Information

Is there a connection to the new MTGJSON v5 release (https://github.com/dr4fters/dr4ft/issues/1132) and the service still checking/expecting v4 data? Or did some endpoint change already, even though it's all supposed to work until the end of 2020?

**Comment by ZeldaZach** [comment]
We need to move to v5 as soon as we can

**Comment by lrawicz** [comment]
Sorry, I don't understand the task. Does my PR resolve the issue?

**Comment by HerveH44** [comment]
@tooomm could you be more explicit with the issue ? I think we auto-update should still be working. 

@lrawicz you may have a bit more work to do to follow up on your PR : the booster rules seem to be aggregated within the set data so we could modify the code so we just download the MTGJson file and update both set data and booster rules. Are you interested?

**Comment by HerveH44** [comment]
Closing this. @tooomm you can reopen it if you feel it needs it.
