### ISSUE TITLE
Bug: Frequency of multicolor and colorless commons greatly off-kilter in KTK packs

### ISSUE THREAD

**Issue by awjackson** [dr4fters/dr4ft#1264]
**Webpage**: 

## Detailed Description

Generated a couple dozen 12-pack KTK sealed pools. Every single pool had at least twelve Banners and twelve three-color common morphs (Abzan Guide etc.), and most of the pools had fifteen or more of each. On the other hand none of the pools had a single common tapland unless it was a foil. There are five banners, five three-color common morphs and ten taplands out of 101 commons, so a 12-pack pool should contain an average of twelve taplands, six banners and six three-color morphs.

I suspect the getRandomCardsWithColorBalance function in backend/boosterGenerator.js is not handling colorless and multicolor cards properly, but I can't even guess why it is over-selecting artifacts but failing to select lands when both are colorless cards.

**Comment by ZeldaZach** [comment]
Hmm, this sounds like a booster generation failure. @taw maybe you have some insight?

**Comment by taw** [comment]
Data is correct (every KTK common has the same rate, nothing about KTK packs is unusual), and I opened a thousand packs on mtg.wtf to verify, and ratios look correct.

However - it might very well be `getRandomCardsWithColorBalance` on your side, that's one thing that's probably different between your code and mine.

[This is the code I use](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/color_balanced_card_sheet.rb) to keep EVs matched. Naive code (pick cards at random, keep rerolling until pack contains at least one common of every color) has very biased EV.

At some point I'd like to get rid of color balancing flag and just make sheets like `whiteCommons`, `blueCommons`, `blackCommons`, `redCommons`, `greenCommons`, `otherCommons` for each set, as that's the most complex thing about using booster data.

Can you easily open like a 1000 packs on your backend to see the ratios?

**Comment by HerveH44** [comment]
Solved by #1395
