### ISSUE TITLE
Bug: Custom Card Images No Longer Displaying

### ISSUE THREAD

**Issue by slumberspirit** [dr4fters/dr4ft#1335]
**Webpage**: www.dr4ft.info

This seems to happen regardless of what draft options are selected, across all tests I've done.

## Detailed Description

Last weekend and previous to that, my custom card images would display in a draft. Now they just display as a white space and create a new card-sized row below them in the draft with their rules text. This is the line in my xml where I have the imgur link, which hasn't changed. ~~The < brackets are [ so they display here:~~
`<set rarity="rare" uuid="" num="" muid="" picurl="(working imgur link here.png)">CUBE</set>`

## Further Information

This console error is coming up in Chrome:
![image](https://user-images.githubusercontent.com/63704671/103110833-5714fb00-45fc-11eb-90bd-1e720e513572.png)

**Comment by cmackeen** [comment]
I am trying to do this for the first time, and have valid pic urls in a card/set xml within the set tags. I get no images, same 404 error, and I am on Firefox 84.0

**Comment by ZeldaZach** [comment]
Might be due to the new v5 update we pulled in. Might have to rework custom iamges

**Comment by FullOnWizard** [comment]
> Might be due to the new v5 update we pulled in. Might have to rework custom images

@ZeldaZach any status update here? Is anyone working on it? I'm having the same issue and curious if its something that will fixed anytime soon(ish).  Appreciate any info/work.

**Comment by ZeldaZach** [comment]
cc @lrawicz would be a nice fix

**Comment by HerveH44** [comment]
@cmackeen could you please provide the custom set you're trying to use? A link to the xml would be perfect for us to test it.

**Comment by HerveH44** [comment]
@FullOnWizard you can also provide a  custom set if you have one !

**Comment by pinchedharmonic** [comment]
here is our custom set, images hosted by @cmackeen 
[TTN FINAL MAYBE.zip](https://github.com/dr4fters/dr4ft/files/5896924/TTN.FINAL.MAYBE.zip)

**Comment by cmackeen** [comment]
Hey @HerveH44 or @ZeldaZach are there any updates on this? I see there are other issues, and just curious if we should try and upload a custom set again?

**Comment by HerveH44** [comment]
Hi, sorry I have little free time right now but I'll check it whenever I have some time!
