### ISSUE TITLE
Bug: Decadent draft doesn't spawn new packs.

### ISSUE THREAD

**Issue by MotherofRuins** [dr4fters/dr4ft#1391]
http://dr4ft.info/
Chrome Version 87.0.4280.141 (Official Build) (64-bit)

----
Launched a new decadent draft.  After each pick, the same pack is presented, with one less card.

**Comment by HerveH44** [comment]
It's a pb introduced by Glimpse draft. Will provide a PR shortly

**Comment by HerveH44** [comment]
@MotherofRuins can you check also on the PR deployed app if that answers your issue ?

**Comment by MotherofRuins** [comment]
I don't know what a PR deployed app is, but the dr4ft decadent draft is fixed, thank you.
