### ISSUE TITLE
Bug: transform cards in draft don't flip

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1394]
After recent branch I contributed to was merged cards like werewolves don't flip when you hover on them.

This only effects the draft pack, not the main deck etc

**Comment by mixmix** [comment]
Pretty sure I know what this is. Still look into it soon

**Comment by HerveH44** [comment]
Normally, the toBoosterCard file (parse MTGJson to dr4ft card) should add the properties "isDoubleFaced" and the url to the other face. Maybe moving to mtgjv5 we didn't update this?

**Comment by mixmix** [comment]
I think it's that I refractored GlimpseCard to not depend on DefaultCard and I might have dropped an important on hover function
