### ISSUE TITLE
Kaldheim Draft Pack Collation is off

### ISSUE THREAD

**Issue by ZackAwesomeness** [dr4fters/dr4ft#1397]
The packs in kaldheim draft currently have snow dual lands(and the one that gives the color that you chose as it enters) counting as regular commons, as well as the land slot being sometimes only a single color snow land, and sometimes a basic non-snow land. The packs also include the cards from the theme and set boosters, as well as the alternate art versions of cards.

**Comment by HerveH44** [comment]
Hey, could you provide us with the exact collation of Kaldheim, including a url where we could check it ?

@ZeldaZach I guess it must be linked with how we fetch booster rules. Is @taw still around ?

**Comment by ZeldaZach** [comment]
Booster rules for MTGJSON come directly from @taw so this is an upstream ticket

**Comment by ZackAwesomeness** [comment]
Where would I actually submit the issue? @ZeldaZach

**Comment by taw** [comment]
@ZackAwesomeness To http://github.com/taw/magic-sealed-data but nothing will happen until KLD is fully in released mtgjson without `isPartialPreview` flag.

**Comment by HerveH44** [comment]
Thanks @taw . Closing this issue as it's beyond our scope.
