### ISSUE TITLE
Bring all NPM packages up to date

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#1405]
A lot of our NPM packages have had major version bumps. I'd like to get our NPM up to date, and account for all the changes done.

**Comment by mixmix** [comment]
I did a suite of minor and patch updates. Will need to look at major version bumps closely

**Comment by tooomm** [comment]
In the meantime we have accumulated several issues due to outdated packages.

> *As spotted in https://github.com/dr4fters/dr4ft/pull/1506/checks?check_run_id=2990227822#step:4:1422:*
>
> "found 30 vulnerabilities (25 moderate, 4 high, 1 critical)"

**Comment by tooomm** [comment]
Done in #1588
