### ISSUE TITLE
Bug: Start//Fire erroneously appears in my cube

### ISSUE THREAD

**Issue by LotusWalker** [dr4fters/dr4ft#1420]
Chrome Version 87.0.4280.141 (Official Build) (64-bit)

I imported my cube from CubeCobra into Dr4ft, and was surprised to see the Mystery Booster test card Start//Fire in my draft. This card isn't in my cube. I think it might be replacing Fire//Ice (which is in my cube), but not positive about that. In the list of cards imported, it shows "Fire (uma 225)" which I believe is my Fire//Ice, but which is being swapped by Start//Fire.

**Comment by HerveH44** [comment]
Could you provide the name of your cube in cubecobra ?

**Comment by LotusWalker** [comment]
Sure, here's the link, as well as a screenshot of the issue:

http://cubecobra.com/cube/list/guertinvintagecube

![Dr4ft Screenshot](https://user-images.githubusercontent.com/69441720/105613706-86e12b00-5d81-11eb-826c-e8a2d3202512.png)

**Comment by HerveH44** [comment]
@nex3 I guess there must be a bug inside the process to write cubable cards. I'm going to investigate it. Maybe you have some clues already

**Comment by HerveH44** [comment]
@LotusWalker thanks for the info. I'll check it. Sorry for the inconvenience in the meantime.

**Comment by LotusWalker** [comment]
No worries! Thanks for investigating.

**Comment by HerveH44** [comment]
In fact, I don't think it's something caused by @nex3 , but rather a problem of #848. @LotusWalker is it possible to get the whole card instead of just the "fire" part ?

**Comment by LotusWalker** [comment]
So the whole card is Fire//Ice. The transform/adventure/mdfc cards in my cube all loaded without a problem, but Fire//Ice is the only split card in my cube.
