### ISSUE TITLE
Kaldheim draft includes Theme Booster exclusives

### ISSUE THREAD

**Issue by Frozedon** [dr4fters/dr4ft#1421]
When drafting Kaldheim, it includes cards that are exclusive to the Theme Boosters. Some of those cards imbalance the draft format and probably should be culled out.

https://scryfall.com/search?order=set&q=set%3Akhm+is%3Athemepack&unique=prints

**Comment by HerveH44** [comment]
Hi, thanks for your feedback. 
As indicated before in #1397, Kaldeim collation has not yet been implemented in the repo doing the collation. 

@ZeldaZach we could try to implement in the "Default booster" the rule to discard cards with number > to the set number of cards. Personnally, I would prefer keeping the default booster without any rule to keep it as generic as possible. But I can understand drafters wanting to play with the new sets as quick as possible.

**Comment by HerveH44** [comment]
Closing this as it's not related to our scope.

**Comment by ZeldaZach** [comment]
Until a set launches, we can’t create a stable draft environment. However, if the theme booster cards are still appearing after launch (now), then we need to address that.
