### ISSUE TITLE
Maintenance: remove Magic Workstation

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1434]
In this PR : https://github.com/dr4fters/dr4ft/pull/1419
where @mixmix changed export options, the question "is magic workstation something we want to support" came up.

We honestly didn't know if anyone was still using it.
In that PR the code for exporting to its format has been commented out.

If we're going to remove it @tooomm suggested we go through the app and pull out all places it might have touched - e.g. hashes for deck exported to that

**Comment by tooomm** [comment]
MWS parts I'm aware:

- deck export for MWS
- hash calculation for MWS
- table column next to player names to display that hash

**Comment by mixmix** [comment]
I think those hashes are also Cockatrice deck hashes right?

What's not clear to me are there is a hash column and a "trice" column? No idea what that is. Hash of sideboard?

**Comment by tooomm** [comment]
There are two different hashes:
![hashes](https://user-images.githubusercontent.com/9874850/107099983-64382300-6813-11eb-9b5c-8563881ef02b.png)

`Trice` --> Cockatrice
`MWS` --> Magic Workstation

I know the first is badly named and should get changed once there is more space after MWS is gone. :)

**Comment by mixmix** [comment]
Lol I thought trice as some technical term like trie or radix.
Funny it's just a more acceptable abbreviation than cock
