### ISSUE TITLE
Bug: Random sets still broken?

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1436]
## Background Information

Example game ID I copied before crashing on dr4ft.info: 42caaa50-6807-11eb-8cfc-67644fe12bbe

Running Version: 8793772 (build 2021-02-03) - Using MTGJSON card data v5.1.0 (2021-02-01) and Magic Sealed Data booster rules commit 0c510a9

## Detailed Description

I tried to open several sealed games with "Random Set" selected for all 6 packs.
In around 2/3 of the games I get the `Whoops! An error occurred while starting the game.` when I hit the `Start` button.

**Comment by tooomm** [comment]
To add to this, I happen to rerun our Action jobs on on a regular basis lately as they seem to randomly fail just to pass afterwards.

In the logs, I spotted an error in tests about RNG set today, I did not copy it though... the rerun passed all tests again. Will watch out for more of those and paste here.

**Comment by mixmix** [comment]
I've seen the unit tests complain occasionally about RNG not existing

**Comment by mixmix** [comment]
```
   1) Acceptance tests for Pool class
       can make all playable sets
         should return a normal booster:
     Error: RNG does not exist
      at map (backend/boosterGenerator.js:9:11)
      at Array.map (<anonymous>)
      at Object.DraftNormal (backend/pool.js:49:6)
      at forEach (backend/pool.spec.js:95:28)
      at Array.forEach (<anonymous>)
      at forEach (backend/pool.spec.js:91:14)
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (backend/pool.spec.js:90:35)
      at processImmediate (internal/timers.js:461:21)


```

https://github.com/dr4fters/dr4ft/pull/1457/checks?check_run_id=1906081656

**Comment by tooomm** [comment]
Do you think this is related to the issue?

**Comment by mixmix** [comment]
No idea, but you mentioned an RNG bug, so I copied what I saw.

**Comment by mixmix** [comment]
GOT IT
or I got something anyway
