### ISSUE TITLE
Improve favicon usage

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1465]
## Detailed Description

We only use a basic favicon and don't support e.g. various modern shortcuts.

For example, this is the view of Firefox's `Top Sites` on every new tab:
![fav](https://user-images.githubusercontent.com/9874850/108496879-fc6de780-72aa-11eb-91fa-93b098a9fe47.png)
dr4ft only gets a cropped screenshot as there is no support for a bigger icon yet.

## Further Information

Interesting resource: https://realfavicongenerator.net/

**Comment by mixmix** [comment]
This should be resolved now

**Comment by tooomm** [comment]
Thanks @Noojuno for implementing this. It looks great! :)
