### ISSUE TITLE
Add margin to page bottom

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1467]
On lower resolution screens, where the page is not displayed all at once and one has to scroll to see the bottom, there should be some clearance in between the footer and the site content:
![footer](https://user-images.githubusercontent.com/9874850/108593743-c9dcf100-7375-11eb-9f0c-bb4b343d86e1.png)

**Comment by mixmix** [comment]
Hey @tooomm if you're intetested I can teach you how to make these changes

**Comment by tooomm** [comment]
Sure, it's probably just difficult to find time right now. Will write you a message!
