### ISSUE TITLE
Remove further sets from "Random Set" pool

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1472]
## Detailed Description

As far as I understand it, `Draft Innovation` sets are still part of the pool considered for random.
Those sets should probably be excluded as well. They are not designed for use in normal draft, especially in combination with other sets.

Not sure about `Starter`.

**Comment by mixmix** [comment]
Do you want to have a go finding where to do this in the code?

**Comment by tooomm** [comment]
I think you put good notes down - guess I can find it. :)

What's your opinion about the `Starter` sets? Should they be excluded as well?

**Comment by mixmix** [comment]
Let's say yes exclude.
