### ISSUE TITLE
idea: allow to adjust size of cards

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#148]
If you are doing sealed and a lot of cards are shown, or when you draft on a smaller monitor it can be helpful to see more cards at once.
The smaller picture doesn't have to be a drawback, because most people know the cards and only go by their art without reading the actual card text.

On the other hand, people with e.g. eye issues could benefit from bigger cards.

It could be 3 options `Card size: small / normal / big` placed in the **Settings** widget.

**Comment by dev-id** [comment]
You can use your browser's zoom functionality to change the size of cards.

**Comment by tooomm** [comment]
Sure, one could do that as a workaround... and end up with a tiny (or gigantic) messy UI. 👍
