### ISSUE TITLE
idea: restructure game type selection

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#149]
| [ Draft ] | [ Sealed ] |
| :- | :- |
| [ **Regular** ] [ **Chaos** ] [ **Cube** ] | [ **Regular** ] [ **Chaos** ] [ **Cube** ] |

or

| [ Draft ] | [ Sealed ] |
| :- | :- |
| [ **Regular** Draft ] [ **Chaos** Draft ] [ **Cube** Draft ] | [ **Regular** Sealed ] [ **Chaos** Draft ] [ **Cube** Sealed ] |

In the GUI a simple version could look like this:
![draft-sealed](https://user-images.githubusercontent.com/9874850/43967214-2f84df12-9cc4-11e8-8ccd-7f92769d17c3.png)

You basically would have the `Game type` selection for **Draft** or **Sealed** same as now,
and a new row below with connected **Regular**, **Chaos** or **Cube** options.
(they could adjust depending on the selected game type above and display **Regular Draft**, **Chaos Draft** etc. instead)

Depending on which you choose you are presented with different settings just like now:
- Regular: amount of boosters, sets
- Chaos: only modern sets, total chaos
- Cube: text field for entering a cube list, cards in packs and packs settings

<br>

Considering further ideas from https://github.com/dr4fters/dr4ft/issues/64 with a dropdown to select the amount of boosters:
(defaulting to 3 packs for draft and 6 packs for sealed mode obviously)
![draft-sealed2](https://user-images.githubusercontent.com/9874850/43967839-b3cd1112-9cc5-11e8-8cb1-2a76a4c0ef5c.png)
At first my idea was to have a `[+]` button to dynamically add them one by one, but I even prefere @HerveH44's idea here with the list (up to 36 = one Display?).

<br>

Benefits:
- more logical and flexible structure
- clearer GUI, easier for the user
- cube sealed not possible currently (support could be added at a later point)

**Comment by HerveH44** [comment]
I love the idea. That's more or less what I've done on Asobi (https://github.com/HerveH44/Asobi)

**Comment by tooomm** [comment]
Haha, funny that you also felt that could be improved and went down a similar road. 😄
