### ISSUE TITLE
Bug: JSON download is accessible

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#1491]
**Webpage**: dr4ft.info and beta-dr4ft

The JSON download option is supposed to be disabled.
When you hover your mouse over its location on the right to `Text` in the `Download` box, it suddenly fades in, is clickable and offers you a JSON download.

I think you made it so, that it should only be accessible in debug mode? @mixmix

**Comment by mixmix** [comment]
Not a big, that's a feature I left in as an Easter egg to make it easy to pull raw json (and debug production of needed).

Your perceptive to have found it, it only appears if you put your mouse in the right place!

**Comment by tooomm** [comment]
Haha, reading the PR again you even announced it like that in one of the comments. Missed that. 😆
