### ISSUE TITLE
Bug: Server crash

### ISSUE THREAD

**Issue by laxect** [dr4fters/dr4ft#1507]
**Webpage**: dr4ft.gyara.moe

I have set up a server based on the latest commit [a09ab4e](https://github.com/dr4fters/dr4ft/commit/a09ab4e357334939d3f4089fb1a82e7513a781ae). The only modify is to change the game expiration time to 10h.

## Detailed Description

Run a docker image based on the latest commit and start a cube draft game. Then the server crashed.

## Further Information

```
/app/backend/player/human.js:135
    const remainingToBurn = Math.min(pack.length, this.burnsPerPack - this.selected.burns.length);
                                          ^

TypeError: Cannot read property 'length' of undefined
    at Human.confirmSelection (/app/backend/player/human.js:135:43)
    at Human._confirmSelection (/app/backend/player/human.js:60:10)
    at Sock.emit (events.js:315:20)
    at Sock.message (/app/backend/sock.js:17:8)
    at Socket.emit (events.js:315:20)
    at Socket.onPacket (/app/node_modules/engine.io/lib/socket.js:110:14)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.Transport.onPacket (/app/node_modules/engine.io/lib/transport.js:105:8)
    at WebSocket.Transport.onData (/app/node_modules/engine.io/lib/transport.js:116:8)
    at WebSocket.onData (/app/node_modules/engine.io/lib/transports/websocket.js:79:30)
```

All log if you need it: 
[log.log](https://github.com/dr4fters/dr4ft/files/6217385/log.log)

**Comment by tooomm** [comment]
Hi @laxect. Can you test with commit https://github.com/dr4fters/dr4ft/commit/68c609a64e8ca9ed22cbf9b8c0e32b53c610d46b please?

**Comment by mixmix** [comment]
Doesn't seem docker related, looks like a classic js bug where a variable hasn't been set correctly.

**Comment by mixmix** [comment]
Very strange. That pack variable is pretty core, comes from this.packs.unshift

Maybe if that was called when there were no packs left? But no idea how it would get into that state.

**Comment by laxect** [comment]
> Hi @laxect. Can you test with commit [68c609a](https://github.com/dr4fters/dr4ft/commit/68c609a64e8ca9ed22cbf9b8c0e32b53c610d46b), please?
> We just updated the Dockerfile in that commit to use Node 14 LTS. It should have the same result though.
> 
> Does the server also crash when you do other game modes?

No Crash in sealed game. I'm sorry but I have no time to test it until next weekend.



> Very strange. That pack variable is pretty core, comes from this.packs.unshift
> 
> Maybe if that was called when there were no packs left? But no idea how it would get into that state.

The server crash in the middle of the first pack and there are packs available.

**Comment by LotusWalker** [comment]
My play group just tried a draft for the first time in about 10 days and it crashed on us in Pack 2. When we tried to refresh/rejoin it wouldn't let us...said "No game found with ID..."

Screenshot attached.
![Dr4ft Crash](https://user-images.githubusercontent.com/69441720/114256826-f1f9d100-9970-11eb-9a43-20b1e1e5de48.png)

**Comment by mixmix** [comment]
@LotusWalker as this dr4ft.info?
Also, does anyone know if @ZeldaZach runs the docker image or npm start to run that?

**Comment by LotusWalker** [comment]
@mixmix Yes it was Dr4ft.info

**Comment by mixmix** [comment]
This is a good reason to do tagged releases which match deploys there - it
would make it much easier to jump back to previous stable versions and
bisect the problem
