### ISSUE TITLE
try to remove needed manual adjustments to frontend before installation

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#151]
*placeholder reminder*

Before each set can be used (even though the containing mtgjson is automatically fetched), there needs to be a manual change to https://github.com/dr4fters/dr4ft/blob/master/public/src/sets.js first.

**Comment by HerveH44** [comment]
The idea I guess would be to fetch the sets at start. There are 2 roads, either use the websocket to send the data or have an endpoint that is called during creation of lobby. For the second road, it would be cool to have the PR #96 up and running to use the setup and just add another endpoint.

**Comment by HerveH44** [comment]
That could be possible yes, but this would be just the following of the one of the 2 options. What you describe could be what the backend will do, fetching every X days the last MTGJson data before sending it back to the clients.

**Comment by HerveH44** [comment]
#96 should have closed this Issue. The sets are now fetched automatically from backend and the AllSets.json is checked every hour for update.

**Comment by tooomm** [comment]
Oh, so you squeezed some more changes in there than the API?

e.g. PR's that add new sets to public/src/sets.js are not needed anymore?

**Comment by HerveH44** [comment]
Yeah, no we just need to add the data in MTGJson and the site will fetch it!
