### ISSUE TITLE
Feature Request - Auto Draftroom Creation

### ISSUE THREAD

**Issue by Mycheze** [dr4fters/dr4ft#1519]
Hi! I have no idea if this is the right place at all for this, but I saw another Feature Request on the page.

I am a small-time Discord Bot Programmer and am working on a comprehensive "Cube Bot" that makes drafting and playing cube a lot easier. We already use dr4ft.info for the drafting portion, but someone always has to manually create the room. I would LOVE to have the option to do it automatically. If there was a fairly simple way to create a dr4ft.info link that players could join.

I already do something similar with CubeCobra for making P1P1s of a cube based on the Cube ID. I think it'd be really good to be able to create a URL that says something like https://dr4ft.info/createroom/cubeID/playersize/draftspeed/otherthings (something deterministic) and then have that automatically be turned into a regular, joinable room based on those settings.

That would make it super easy to implement into my bot since python can already send a URL and receive the "fixed" URL. I do that with CubeCobra's random feature to generate completely random p1p1s from some random cube on the entire site.

I have no idea how website programming works, but I thought I'd throw out this idea and would be more than happy to help how I can. If I can.

**Comment by Mycheze** [comment]
No way. I thought I looked hard enough!

My bad... Keep up the good work!

**Comment by tooomm** [comment]
We are always happy to hear what people build.

Let us know how it goes! @Mycheze

**Comment by Mycheze** [comment]
I have no idea if people will see this, but I've been messing around with to try and get it to work. 

I'm not very familiar with using APIs and I can't get the bot to create draft rooms! Do you know of any examples I can look through to figure things out?

Also, it is possible to get a cube list with just the cobraID? That's what I do when manually creating a draft room and it's such an amazing feature. It'd be amazing if that was possible.

**Comment by tooomm** [comment]
Unfortunately I can not help you with that, no experience here either.

You can look at the implementing PR (https://github.com/dr4fters/dr4ft/pull/96) and the requesting issue though. Maybe there is something useful? Sorry for not being more helpful.

>Also, it is possible to get a cube list with just the cobraID? 

As that's not documented I would not expect that to work. But you could probably get the list via their API and provide it in the `cube` object?
