### ISSUE TITLE
Masterpiece Series might be broken

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#154]
Card art seems to not show up for them.
Are they inserted at all?

See #121 for further details.

Affected Sets could be:
- Zendikar Expeditions (BFZ / OGW)
- Kaladesh Inventions (KLD / AER)
- Amonkhet Invocations (AKH / HOU)

**Comment by HerveH44** [comment]
I don't think it's the case anymore. Could you try on dr4ft.info?

**Comment by tooomm** [comment]
Not sure. I clicked through another 10 AKH drafts with bots to see around 100 rares, no Invocation art there.

Only card that could have showed up as special art was Oketra, but it had normal one.

**Comment by HerveH44** [comment]
After a couple sealed on dr4ft.info, i got lucky ;) !

![masterpiece](https://user-images.githubusercontent.com/16805904/44352082-af271a00-a4a3-11e8-9188-1727b1010718.png)

Code shows that you get a chance on 144 to get a masterpiece in a pack !

**Comment by tooomm** [comment]
Great!
