### ISSUE TITLE
M19 Packs are including cards from the Precon decks

### ISSUE THREAD

**Issue by JineteDV** [dr4fters/dr4ft#157]
Cards like Tattered Mummy and Mist-Cloaked Herald

**Comment by tooomm** [comment]
Is that fixed for you @JineteDV on http://dr4ft.com?
Since we found out, our fix might not be the right one...

**Comment by JineteDV** [comment]
Yea seems fine now.

**Comment by tooomm** [comment]
Thanks for coming back to us!
