### ISSUE TITLE
constantly show pick timer as little overlay somewhere

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#16]
Something like the card preview for example.

You always need to scroll up to check the timer right now.

Happens several times now to me:
You mark a card for autopick while re-considering other cards. To skip to the next pack you still double click on the card selected for autopick. But since the timer went down and/or due to the server delay I end up immediately picking the next card at the same position from the following pack.
If you always see the time, that won't happen.

**Comment by tritoch** [comment]
Related: should you not be able to pick a card in the first couple seconds of a new pack? Would need to adjust the timers up again.

**Comment by tooomm** [comment]
>should you not be able to pick a card in the first couple seconds of a new pack?

Interesting idea additionally... maybe not needed though.
Should also be very small - max 2-3s to actually refresh the page and start loading the new pictures?
Otherwise it get's annoying again for last packs where you literately just double click yourself through!

>Would need to adjust the timers up again

?
The case described above doesn't happen because i run out of time. If you have more time you use more time...
