### ISSUE TITLE
Auto-include masters sets when running make/cards.js

### ISSUE THREAD

**Issue by dev-id** [dr4fters/dr4ft#170]
Currently all the masters sets are defined independently. Masters sets should be built automatically so the images are available and the sets can be added with just public/src/sets.js edit

**Comment by HerveH44** [comment]
That's super interesting, what is our baseline as to what set should be included and which one should not and why. It seems to me that there are 2 levels : one is to get the maximum amount of cards in the DB to let people cube draft them but keep the sets that are draftable. 

Is there a way in the Allsets.json to know this?

**Comment by ZeldaZach** [comment]
Is this solved now with auto downloads, @HerveH44 ?

**Comment by HerveH44** [comment]
Not yet, I have to check it. I'll do a PR when #335 will be merged

**Comment by HerveH44** [comment]
Pushed in the PR #335
