### ISSUE TITLE
no beep for new pack on autopick

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#18]
At least if you selected a card for autopick before.
For random autopick I didn't check.

Update: Seems to not happen consistantly!?

**Comment by HerveH44** [comment]
It works for me. What browser do you use ? I am on Chromium Version 60.0.3112.78 (Debian 9.1, x86/64)

**Comment by tooomm** [comment]
Couldn't reproduce anymore with either FF or Chrome.
