### ISSUE TITLE
Show progress in draft - pack and pick number

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#19]

**Comment by tritoch** [comment]
Can you clarify?  Pick number is the inverse of cards left in pack (which is displayed above the pack).

**Comment by tooomm** [comment]
>Pick number is the inverse of cards left in pack

Yeah... could be easier :)

We could start off with displaying the pack number here: (since we don't have this info at all!)
![packs](https://cloud.githubusercontent.com/assets/9874850/26016314/cec62ffc-3764-11e7-858b-a3fbb1eaabf8.png)
