### ISSUE TITLE
Move Score Database Offline

### ISSUE THREAD

**Issue by dev-id** [dr4fters/dr4ft#2]
Currently the card score database used for bot pick orders uses a couchdb located online.  That couchdb is no longer being written to, so scores are currently static.  The database should be moved to a local json file.

Relevant code section:
https://github.com/dr4fters/dr4ft/blob/master/src/make/score.js#L5-L13

**Comment by tooomm** [comment]
This is addressed in https://github.com/dr4fters/dr4ft/pull/71 👍
