### ISSUE TITLE
Dominaria missing

### ISSUE THREAD

**Issue by dmaslowski** [dr4fters/dr4ft#200]
In the last update duplicate M19 and dominaria where deleted. But it looks like dominaria wasn’t a duplicate and is now missing from the website.

**Comment by tooomm** [comment]
The running code at dr4ft.com simply misses https://github.com/dr4fters/dr4ft/pull/137.
As you can see in our [history](https://github.com/dr4fters/dr4ft/commits/master) the "remove duplicate" commit, which the dr4ft.com page is currently running, is one day older.
@dev-id just needs to update the server.

Thanks for pointing out! @dmaslowski 

In the meantime you can run dr4ft.info which has that commit already included.

**Comment by dmaslowski** [comment]
Thanks so much!
