### ISSUE TITLE
GRN issues

### ISSUE THREAD

**Issue by hitz** [dr4fters/dr4ft#204]
Thanks for getting GRN up so fast.  There are a couple issues.

1) There should be 1 Guildgate per pack, it seems like they are done in the common slot.
2) Circuitous route has Japanese art and text
3) A couple other cards have french art; this is probably not dr4ft problem.

**Comment by HerveH44** [comment]
Hi,

Is it possible to give the URL where you read the mandatory presence of a guildgate? I couldn't find it and it could be of great help! 

Thanks

**Comment by HerveH44** [comment]
About the guildgate, just found a video : https://clips.twitch.tv/SpinelessFreezingYogurtPraiseIt

**Comment by JineteDV** [comment]
GRN draft on dr4ft also still has the Planeswalker deck cards in the packs

**Comment by TemporalMadness** [comment]
on the gates, it Should be both 1 per pack and common slot.

**Comment by JineteDV** [comment]
Fresh-Faced Recruit and Vernadi Shieldmate are two drops that get sorted into the 4drop column when sorting by cmc.

**Comment by JineteDV** [comment]
Smelt-Ward Minotaur is misnamed as Smelt-War Minotaur.

**Comment by impromptuu** [comment]
Parahelion Patrol still has the spoiler season image.

**Comment by tooomm** [comment]
mtgjson is updated with GRN, so I think this should no longer be an issue, as soon as the draft pages get updated with the new data.

**Comment by snyderrj** [comment]
So I'm not sure what's causing this, but Devious Cover-Up is named Devious Cover-up when copied. This causes issues with Cockatrice. I've attached a .txt downloaded from dr4ft.com where you can see the problem.

[filename.txt](https://github.com/dr4fters/dr4ft/files/2430239/filename.txt)

**Comment by TemporalMadness** [comment]
Hash-tags for decks DO not match. loaded it 4 times from the draft site.

**Comment by flyingdutchman0** [comment]
yeah, this has been a problem since the latest update. i think this has something to do with the guildgates, they don't behave properly on cockatric anymore.

**Comment by ZeldaZach** [comment]
I think it's b/c of the "GuildGate (a)" "GuildGate (b)" thing. This is fixed on V4, but still a problem on V3 :/

**Comment by tooomm** [comment]
>I think it's b/c of the "GuildGate (a)" "GuildGate (b)" thing. This is fixed on V4, but still a problem on V3 :/

Zach is talking about mtgjson, which is used as source for the card database on dr4ft as well.
Most likely v3 is still used since v4 is not yet released officially.

@HerveH44 did you try to run v4 already? Any issues so far?

**Comment by flyingdutchman0** [comment]
will this get fixed soon? i hate when the opponent drops 4 rares in a single game, and their deck codes don't match.

**Comment by TemporalMadness** [comment]
The obviously cheated, hence GRn is undraftable on cockatrice

**Comment by TemporalMadness** [comment]
closed, but not fixed

**Comment by tooomm** [comment]
@TemporalMadness which issue(s) is/are still left?
Pleas open a new ticket for each!
