### ISSUE TITLE
https://beta-dr4ft.herokuapp.com UPDATE

### ISSUE THREAD

**Issue by Rendroc** [dr4fters/dr4ft#211]
https://beta-dr4ft.herokuapp.com

I've been unable to use the dr4ft.com or dr4ft.info websites and I've posted in another issue thread here about it. The URL above has worked for me, but it currently doesn't have GRN. Can someone please add GRN?

Thank you.

**Comment by HerveH44** [comment]
Hi, 

The only thing to do is to merge the branch "grn" into master.

**Comment by HerveH44** [comment]
@Rendroc The branch has been merged, so http://beta-dr4ft.herokuapp.com/ is updated

Enjoy !
