### ISSUE TITLE
github commit hash not "correct"

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#216]
Currently the dr4ft.info site shows "Running Version 1a4ad0c".

The problem is that 1a4ad0c points to a single commit (last one) within https://github.com/dr4fters/dr4ft/pull/214.
Instead, it should display the merge commit of all PR to master (https://github.com/dr4fters/dr4ft/commit/b28ffefa73bc8aaab0101febc14b6a40d1c6c995) as displayed in the [history](https://github.com/dr4fters/dr4ft/commits/master).
Because that shows all other commits and links to the PR with more info etc.
The other is just a selection and has not the big picture.

**Comment by HerveH44** [comment]
Hi @tooomm ,

Currently, dr4ft.info is still on the branch "grn". I'll update it ASAP

**Comment by tooomm** [comment]
Great, that makes sense. I was sure it was "working" before... 🙈
