### ISSUE TITLE
update dr4ft to use new mtgjson v4

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#232]
https://github.com/dr4fters/dr4ft/pull/223#issuecomment-429618221

**Comment by tooomm** [comment]
>V4 still lacks "booster" parameter on sets.
I can't use v4 unless this is fixed :( !

The `booster` field is added in v4 now! (https://github.com/mtgjson/mtgjson4/pull/107)

**Comment by tooomm** [comment]
Is this fixed with https://github.com/dr4fters/dr4ft/pull/272?

**Comment by ZeldaZach** [comment]
Yes.

More work is needed to be done, but it's not a mtgjson issue

**Comment by tooomm** [comment]
Can you give a short outline what needs to be done or what is not working currently, please?
