### ISSUE TITLE
Cube Sealed requires 720 cards

### ISSUE THREAD

**Issue by dev-id** [dr4fters/dr4ft#24]
Cube sealed requires a minimum cube list size, but the number of players in the event is unknown at the time of cube size verification.

**Comment by HerveH44** [comment]
Hey @dev-id ,

I don't get exactly what you would like to do ? You would calculate the number of cards based on the max players? Like numPlayers * Packs * CardsPerPack?

**Comment by HerveH44** [comment]
I think we can close this issue as it's not true (we don't require 720). Actually we control how many cards we would need if the room is full. I think that's the best we can do and should stay like that.

**Comment by HerveH44** [comment]
@dev-id @ZeldaZach What do you think? Can we close this?

**Comment by ZeldaZach** [comment]
Yep!
