### ISSUE TITLE
Simplify (greatly) our life : use api.magicthegathering.io

### ISSUE THREAD

**Issue by HerveH44** [dr4fters/dr4ft#249]
Hi,

I just found out that there's an APi that can get us all that we want, without any effort of creating / updating rules to create a simple booster. 

I let you read everything here  : https://docs.magicthegathering.io/

it should be very simple to use. I'll work on that in the next weeks, it should greatly improve our code (less code, better performances)... I can't believe we didn't see that before ! The unique problem is that I can't find the code used right now, it doesn't seem to be open ... 

If anyone finds the code, I'll be happy to check how he makes the random boosters and get the way to create a clone of the site in case it goes down ...

Hervé

**Comment by ZeldaZach** [comment]
Awesome. I've been involved with MTGIO for a bit through MTGJSON, and they seem fairly well off with the information we'll need.

**Comment by HerveH44** [comment]
I'm very sad... it seems that the boosters are just made casually without controlling how to build them... 

I still hopes they can do something about it, but like that I just don't find a correct way to go past it...

**Comment by tooomm** [comment]
Too bad, that sounds very promising. :/

You can reach out to them in their discord. I think Zach was hanging around there as well!

**Comment by HerveH44** [comment]
Maybe there's still something to do. 
At least, that shows that we could split all the code to generate boosters in another module, that would help greatly to understand and easily work on features related to limited playing instead of card making.

I'm thinking of a sort of tiny API that would encapsulate all the efforts to create a realistic booster.

**Comment by ZeldaZach** [comment]
You can hijack MTGJSON4's database: https://github.com/mtgjson/mtgjson4/blob/master/mtgjson4/resources/boosters.json

**Comment by HerveH44** [comment]
You can check my branch to see the "refactor" and tell me if I'm wrong. [mtgio](https://github.com/dr4fters/dr4ft/tree/mtgio)

The idea is to fetch the cards from the API and keep them in memory (using memoization or queries).
This is just the first couple lines of codes I came up yesterday.

 My idea to compose the boosters depending if there's a rule or not would be a conditional require to see if there's an override of the default behavior (15 cards, 1 rare, 3 unco, 10 common, 1 basic), based on the set code. I'll implement that when the core will be solid. 

I just implemented the method for sealed "normal" boosters, but that should be the same for the normal drafts. The cube should be a little bit more tricky but nothing too hard, and I still don't know on what to rely on for chaos. We used a static list of sets to compose the modern style... I'd like something more dynamic. But @ZeldaZach if you could come up with an idea to add in MTGJSON sets, if it's modern or not? Is there a field that can tell me that and that I can query easily on a set?

Any help, suggestion or review of code will be much appreciated :) !

**Comment by HerveH44** [comment]
I'm stuck because of cube drafting. The API doesn't accept more than ~80 names per request, which can take a good amount of time ~15-20 seconds. In total, for a 720 cards cube draft, I had to wait ~2 minutes before starting the game. 

I don't know what to do, as it seems that for this unique reason, it could be really helpfull to have the DB in local and not through mtgio API... 

@ZeldaZach @dev-id @tooomm, wha do you think?

**Comment by tooomm** [comment]
>But @ZeldaZach if you could come up with an idea to add in MTGJSON sets, if it's modern or not? Is there a field that can tell me that and that I can query easily on a set?

Can't one tell that by the frame value? https://mtgjson.com/v4/docs.html

<br>

Because of cube it doesn't look feasible to use the API with the current limitations... 2 minutes is just crazy and not going to work.
Too bad actually, I liked the idea and it seems to work for sealed pretty well.
Did you contacted them for a key without or higher limits?

Why not pull the mtgjson (v4) file at each startup of the server?
It's not real time up to date data, but it would be as easy as restarting if the process is automated.

**Comment by ZeldaZach** [comment]
We have Modern.json and Standard.json now. Can use those in place of AllSets.json

**Comment by HerveH44** [comment]
After long investigation, it doesn't suit us anymore: the API takes too long to fetch information and the booster endpoint doesn't take any consideration of how to create a real booster.
