### ISSUE TITLE
add UMA

### ISSUE THREAD

**Issue by hitz** [dr4fters/dr4ft#255]
be great to see UMA up on dr4aft.com & dr4aft.info... it's already in  https://mtgjson.com/v4/

**Comment by HerveH44** [comment]
Hi,

I can't find it on https://mtgjson.com/v4/sets.html. Are you sure it's already on mtgjson_v4?

**Comment by hitz** [comment]
`>>> allsets['UMA'].keys()
dict_keys(['tokens', 'code', 'cards', 'mtgoCode', 'releaseDate', 'baseSetSize', 'name', 'meta', 'totalSetSize', 'type'])
>>> len(allsets['UMA']['cards'])
41
>>> allsets['UMA']['releaseDate']
'2018-12-07'
>>> allsets['UMA']['baseSetSize']
0
>>> allsets['UMA']['totalSetSize']
41
>>> allsets['UMA']['cards'][0]
{'artist': 'Mark Tedin', 'name': 'Emrakul, the Aeons Torn', 'power': '15', 'starter': True, 'text': "This spell can't be countered.\nWhen you cast this spell, take an extra turn after this one.\nFlying, protection from colored spells, annihilator 6\nWhen Emrakul, the Aeons Torn is put into a graveyard from anywhere, its owner shuffles their graveyard into their library.", 'isReserved': False, 'printings': ['MM2', 'PPRO', 'PRM', 'PROE', 'PUMA', 'ROE', 'UMA'], 'colors': [], 'supertypes': ['Legendary'], 'subtypes': ['Eldrazi'], 'hasFoil': True, 'types': ['Creature'], 'hasNonFoil': True, 'rulings': [{'date': '2010-06-15', 'text': 'Annihilator abilities trigger and resolve during the declare attackers step. The defending player chooses and sacrifices the required number of permanents before they declare blockers. Any creatures sacrificed this way won’t be able to block.'}, {'date': '2010-06-15', 'text': 'If a creature with annihilator is attacking a planeswalker, and the defending player chooses to sacrifice that planeswalker, the attacking creature continues to attack. It may be blocked. If it isn’t blocked, it simply won’t deal combat damage to anything.'}, {'date': '2010-06-15', 'text': 'Emrakul can be targeted by spells that try to counter it (such as Lay Bare). Those spells will resolve, but the part of their effect that would counter Emrakul won’t do anything. Any other effects those spells have will work as normal.'}, {'date': '2010-06-15', 'text': '“Protection from colored spells” means that Emrakul can’t be the target of colored spells (including colored Aura spells) or of abilities whose sources are colored spells (such as the “when you cast” ability of an Ulamog, the Infinite Gyre that’s been turned red by Painter’s Servant). It also means that all damage that would be dealt to Emrakul by colored spells is prevented. Like every protection ability, it works only while Emrakul is on the battlefield.'}, {'date': '2010-06-15', 'text': '“Colored spells” is not synonymous with “colored instants and sorceries.” For example, if a player cycles Choking Tethers, its triggered ability may target Emrakul because Choking Tethers wasn’t cast as a spell.'}, {'date': '2010-06-15', 'text': 'Emrakul may be affected by colored spells that don’t target it or deal damage to it, including those that cause it to become blocked. Abilities of colored permanents (such as Journey to Nowhere) may target it. Auras may be moved onto it by abilities or by colored spells that don’t target it (such as Aura Graft).'}], 'uuid': '0e0d989d-7186-40dc-bdfe-cfbb77656bc8', 'convertedManaCost': 15.0, 'layout': 'normal', 'colorIdentity': [], 'manaCost': '{15}', 'legalities': {'legacy': 'Legal', 'vintage': 'Legal', 'modern': 'Legal', 'commander': 'Banned', '1v1': 'Banned', 'duel': 'Banned'}, 'rarity': 'mythic', 'toughness': '15', 'foreignData': [], 'number': '4', 'borderColor': 'black', 'type': 'Legendary Creature — Eldrazi', 'frameVersion': '2015'}
>>> names = [ x['name'] for x in allsets['UMA']['cards'] ]
>>> names
['Emrakul, the Aeons Torn', 'Karn Liberated', 'Kozilek, Butcher of Truth', 'Ulamog, the Infinite Gyre', 'Snapcaster Mage', 'Temporal Manipulation', 'Bitterblossom', 'Demonic Tutor', 'Entomb', "Goryo's Vengeance", 'Liliana of the Veil', 'Mikaeus, the Unhallowed', 'Reanimate', 'Tasigur, the Golden Fang', 'Balefire Dragon', 'Through the Breach', 'Eternal Witness', 'Life from the Loam', 'Noble Hierarch', 'Tarmogoyf', 'Vengevine', 'Gaddock Teeg', 'Leovold, Emissary of Trest', 'Lord of Extinction', 'Maelstrom Pulse', 'Sigarda, Host of Herons', 'Fulminator Mage', 'Kitchen Finks', 'Engineered Explosives', 'Mana Vault', 'Platinum Emperion', 'Ancient Tomb', 'Cavern of Souls', 'Celestial Colonnade', 'Creeping Tar Pit', 'Dark Depths', 'Karakas', 'Lavaclaw Reaches', 'Raging Ravine', 'Stirring Wildwood', 'Urborg, Tomb of Yawgmoth']
>>> 
`

Apparently only has subset now.  I'll open an issue with them.

**Comment by hitz** [comment]
Ah they got caught in a release cycle, should be out this week.

**Comment by HerveH44** [comment]
Ok, When it's ready, we'll integer to dr4ft

**Comment by tooomm** [comment]
UMA not yet available at dr4ft.info @HerveH44

**Comment by tooomm** [comment]
@HerveH44 there was just a ticket opened about that: https://github.com/mtgjson/mtgjson4/issues/149
