### ISSUE TITLE
dr4ft.info pools not sorting by CMC or Color

### ISSUE THREAD

**Issue by hitz** [dr4fters/dr4ft#258]
Pools are not sorting by CMC or color, see attached.  This was seen with both GRN and UMA (did not check other sets)

<img width="847" alt="screen shot 2018-11-30 at 11 06 25 am" src="https://user-images.githubusercontent.com/288823/49309472-3b2be300-f490-11e8-9d4b-bc4e7081df11.png">

<img width="979" alt="screen shot 2018-11-30 at 11 09 08 am" src="https://user-images.githubusercontent.com/288823/49309532-64e50a00-f490-11e8-9436-49ed8e75daea.png">

**Comment by ZeldaZach** [comment]
Fixed
