### ISSUE TITLE
Draft Starting Incorrectly?

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#260]
Forwarding an email I received:

Hi, sorry for bothering you through email, but I have some problems with dr4ft
I found that the version using the jsonv4 branch (as hosted on dr4ft.info) has huge problems, where the draft starts already at the 10th pick then goes on semi randomly through the 15th one.
Also often I get stuck on a white screen where I can’t do anything except restart the draft
I’m on Win10, used different browsers and two different PCs
Also my other friends had the same problem
I tried to build the older version, but it doesn’t have Ultimate Masters, since it works using the older mtgjson database
Thank you for your time

**Comment by OfficialAlienZ** [comment]
Same problem here.
Windows 10
Firefox 63.0.3

**Comment by Manteric** [comment]
I'm the one who sent the email
I want to add that when I get to the blank screen, I get an "TypeError: cards[0] is undefined" error in console

**Comment by ZeldaZach** [comment]
Should be fixed on .info now...
