### ISSUE TITLE
Complile issues

### ISSUE THREAD

**Issue by trsbox** [dr4fters/dr4ft#273]
So I am getting all kinds of errors when running as per the README.md  

I am running Debian 

[outputfile.txt](https://github.com/dr4fters/dr4ft/files/2704891/outputfile.txt)

Any ideas

**Comment by ZeldaZach** [comment]
Interesting, I was having the same issues. cc: @HerveH44 

The fix was to manually copy the default configs from the config folder to the directory above it. But why is this buggy for everyone now?

**Comment by HerveH44** [comment]
Hey @trsbox ,

You have to rename them (delete the .default at the end of each file). I still don't understand why it doesn't work for you ... 

I'll try to investigate.

Hervé

**Comment by trsbox** [comment]
Move them up in directory tree and rename?

**Comment by trsbox** [comment]
Ok, I moved up the files and took out the .default.    Here is the latest issue:
[outputfile1.txt](https://github.com/dr4fters/dr4ft/files/2705544/outputfile1.txt)

**Comment by ZeldaZach** [comment]
Are you running off current master?

**Comment by trsbox** [comment]
Yes.  Just did a git clone

**Comment by trsbox** [comment]
Any other ideas?

**Comment by trsbox** [comment]
Any updates?

**Comment by ZeldaZach** [comment]
Yes! I was able to figure it out

```bash
$ sudo npm install --unsafe-perm
$ npm start
```

**Comment by tooomm** [comment]
Can you add the correct command to the readme, please?
