### ISSUE TITLE
The letter "û" gets saved as "u". When you draft "Lim-Dûl's High Guard" it saves it as "Lim-Dul's High Guard"

### ISSUE THREAD

**Issue by Lim-Dul2** [dr4fters/dr4ft#28]
The letter "û" gets saved as "u".

When you draft "Lim-Dûl's High Guard" it saves it as "Lim-Dul's High Guard".

This makes the art work not work properly in Cockatrice.

**Comment by HerveH44** [comment]
Hi,

In fact that's true for any cards containing a non-ascii letter.

The correction is easy to do, but need to check with developer why there's a control on names, when there are some cards with non-ascii letters (Lim-Dûl cards or Dandân for example).

**Comment by tooomm** [comment]
This could be a character encoding issue.
Our source for the allsets.json file - https://mtgjson.com/ - stated on their website that "All files are UTF8 encoded."

**Comment by ZeldaZach** [comment]
Just tested, this is still an issue
