### ISSUE TITLE
Suggestions and card errors dr4ft

### ISSUE THREAD

**Issue by Rendroc** [dr4fters/dr4ft#291]
Can you add the option to add basic snow lands to decks?

Also, I have a cube with every card in magic history, but for some reasons the only cards that dr4ft has issues with is the futureshifted cards from Future Sight, like Steamflogger Boss, Fleshwrithe, and Baru, Fist of Krosa.

**Comment by ZeldaZach** [comment]
[Basic Snows can't be added to a deck outside of drafting them](https://www.reddit.com/r/magicTCG/comments/3jwp36/using_snow_basics_in_limited/) so this won't be added unfortunately.

The cards should be working now, so I recommend you try again :)
