### ISSUE TITLE
dr4ft.com and dr4ft.info load very slow

### ISSUE THREAD

**Issue by Rendroc** [dr4fters/dr4ft#292]
It's impossible to draft with those URLs. https://beta-dr4ft.herokuapp.com/ is faster, but is still slow sometimes.

**Comment by tooomm** [comment]
http://dr4ft.com as well as https://dr4ft.info are working fine for me?!

What do you mean with "load very slow" exactly? Which parts of the page? How many seconds? ...

**Comment by Rendroc** [comment]
The card images load very slow, and the page loads slow as well. Maybe a card every 2 seconds or more sometimes.

**Comment by tooomm** [comment]
I tried a sealed with old sets I hadn't cached in the browser. All 90 cards loaded within ~10-15 seconds.

Do you have issues with your internet connection, isp, local network etc.?
Are you sure these two pages are the only ones which load slow? I mean can be a lot of data at once, maybe you just don't realize the issue on other pages?

Did you try to speed check your connection?

<br>

In general: Is it viable to switch to scryfall as image source? @ZeldaZach @HerveH44

**Comment by tooomm** [comment]
@Rendroc did anything change for you? at dr4ft.info we now use scryfall as an image source.
Can you please test again and let us know if it works better for you now?

**Comment by ZeldaZach** [comment]
Fixed on .info
