### ISSUE TITLE
Create preset cubes

### ISSUE THREAD

**Issue by dev-id** [dr4fters/dr4ft#3]
Create a list of preset cubes such as the ones from MTGO and allow them to be easily loaded into the cube list.

**Comment by HerveH44** [comment]
Hey @dev-id ,

Do you think of users uploading cubes or administrators uploading it? Because I guess it can't be something easily done by users (for security I guess), but for administrators we could add a directory of "cube lists" and have a combo list in the lobby to select the one we want to use.

**Comment by ZeldaZach** [comment]
My idea was to allow users to upload, store them in a safe location, then an admin can approve them. We will only accept a text list that will go through a linter before upload to ensure no malware

**Comment by HerveH44** [comment]
But there are no real users in the app. Everything is actually in the LocalStorage, we don't save anything serverside. I think it would be a great feature but I guess it requires a DB and some user management features. 

Unless you have an idea how to manage pseudobased users on a DBless server?

**Comment by ZeldaZach** [comment]
Since we now have uploads, can probably store them in custom or something similar?

**Comment by HerveH44** [comment]
You would present it as a dropdown in the "cube" section? 
But how to be sure that this is the right cube and not a joke somebody did  if anybody can upload "cube"?

**Comment by HerveH44** [comment]
So where do we want to go? 

Let people upload cubes lists - and let them override others? 
or have fixed lists in the repo?
