### ISSUE TITLE
Where is score data coming from?

### ISSUE THREAD

**Issue by clarle** [dr4fters/dr4ft#302]
I've been trying to implement a better draft picking algorithm for personal use, since it looks like `scores.json` hasn't been updated in quite some time, so the bots are just picking randomly.

Where did the original scores come from?  I'm trying to see if there's anything that could be done to make it easier for people to plug in their own scores for more recent expansions and have bots take into consideration color combinations.

**Comment by HerveH44** [comment]
@dev-id  Do you remember how the "scores.json" has been implemented? I remember that you worked on it at some point?

**Comment by ZeldaZach** [comment]
It's checked into the repo right now, and I don't believe anything updates it. Should be using draftStats to help update the weighted averages of stuff.

**Comment by ZeldaZach** [comment]
cc: @benjaminpwagner

**Comment by clarle** [comment]
What was it originally based on? Just log data from dr4ft.com of popular cards people were drafting?

**Comment by dev-id** [comment]
src/make/score pulls from an oooold couchdb that Aeosynth set up. hasn't been updated since around RTR.

**Comment by ZeldaZach** [comment]
Sounds like we should change it to use the new draft stats, as well as data from draftSim

**Comment by HerveH44** [comment]
@ZeldaZach  @tooomm should this one be closed?

**Comment by tooomm** [comment]
We elaborated where the data comes from, but the data is still heavily outdated.

@ZeldaZach mentioned a possible next step here - we can keep it open to track that? Maybe rename the ticket?

**Comment by ZeldaZach** [comment]
Rather get a new ticket up. We need to create scrapping and import tools to get data. I have some sources.
