### ISSUE TITLE
Refresh card image (mouse over) after click

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#314]
Happens with Firefox and Chrome on dr4ft.info

When you click a card in the piled view to move it to e.g. sideboard, the pile gets updated and the card beneath your mouse changes but the card preview does not refresh.

**Comment by tooomm** [comment]
As stated in #320, this is not fixed.

However, you find more details and explanation about the issue there.

**Comment by HerveH44** [comment]
This is too narrow and really neglectable bug. If that starts to bother a lot we'll reopen it.
