### ISSUE TITLE
Delay with images on new pack

### ISSUE THREAD

**Issue by ancestral** [dr4fters/dr4ft#329]
What is happening is the images aren’t loaded, so when the next pack comes, I have to wait for the images to load before I know what the card is, which eats into my timer.

Options:

1. Preload images from the next pack (bad idea).
2. Wait for all the images to load before displaying the pack and starting the pack timer.
3. Preload all the images from the set.
 
#1 is a bad idea because it could be used to cheat. #3 might be bad because it may be downloading way more cards than needed. #2 may be the way to go here.

**Comment by ZeldaZach** [comment]
There's no real way for us to know how long the download takes, as it's up to your connection. The server isn't involved in the loading or understanding of that. I don't think we can do much about this issue.

**Comment by ancestral** [comment]
There are ways to find out if the images have downloaded. These tricks exist, I can direct you to some resources if you like.

Of course, you can also take advantage of the ALT attribute for IMG.

**Comment by HerveH44** [comment]
Actually we are using the ALT attribute to display the card's name. Do you think it's not enough? What else would you need to be able to pick while expecting the card's image?

@ZeldaZach the image comes from scryfall if I'm correct. Do you know other sources of cards' images? Before we were directly fetching from wizards oracle. Are there places where we can decide how big we could fetch the cards and adapt from the frontend how big the images of cards the drafter wants?

**Comment by ZeldaZach** [comment]
Scryfall we can fetch different sizes: 

- https://api.scryfall.com/cards/63b2b7cd-a51d-4e50-b794-a52731196973?format=image&version=small
- https://api.scryfall.com/cards/63b2b7cd-a51d-4e50-b794-a52731196973?format=image&version=normal
- https://api.scryfall.com/cards/63b2b7cd-a51d-4e50-b794-a52731196973?format=image&version=large

**Comment by HerveH44** [comment]
Ok so that could be an idea!

**Comment by ancestral** [comment]
https://stackoverflow.com/questions/1977871/check-if-an-image-is-loaded-no-errors-with-jquery

**Comment by HerveH44** [comment]
So I did a little test with small cards' images: 

I wasn't very happy with it, you can barely read the card. But the cards are really quick to download.

![image](https://user-images.githubusercontent.com/16805904/53247957-e1b10a00-36b4-11e9-9a90-c6f7b3316e2c.png)

I pushed it to a branch, I'll add buttons to be able to adapt the card image quality.

**Comment by HerveH44** [comment]
I also set a checker : you can check the PR : #343

![image](https://user-images.githubusercontent.com/16805904/53248987-3ce3fc00-36b7-11e9-9702-95ac9b2ad52f.png)

**Comment by tooomm** [comment]
What do you think @ancestral?
You can test it on the deployment in the linked PR.

**Comment by ancestral** [comment]
So I think we can do better. I think the timer could pause and the pack could display after the pack’s images load.

I could make a patch for you.
