### ISSUE TITLE
Drafting can result in choosing more picks or fewer picks

### ISSUE THREAD

**Issue by ancestral** [dr4fters/dr4ft#331]
How the app is recording clicks or making picks seems to modify how many cards are chosen. This appears to be a potentially seriously issue.

Here’s a video, and here’s a screenshot (and link) of how the draft turned out where I was able to draft 129 cards:

[dr4ft bug.mov.zip](https://github.com/dr4fters/dr4ft/files/2881730/dr4ft.bug.mov.zip)
<img width="1440" alt="screen shot 2019-02-19 at 1 41 00 pm" src="https://user-images.githubusercontent.com/735024/53042520-10787780-344c-11e9-8c11-d408aee674f9.png">
https://dr4ft.info/#g/g71l6gtfv9

**Comment by HerveH44** [comment]
Hi,

Could you tell us what you are using as OS and web-browser? I can't reproduce it on Ubuntu 18.04 with chrome.

Thanks,

Herve

**Comment by ZeldaZach** [comment]
Can't reproduce on MacOS 10.14.3 on Firefox or Safari

**Comment by ancestral** [comment]
I witnessed it with both Firefox and Safari on macOS 10.14.2, but I can’t reproduce it all the time.

**Comment by ancestral** [comment]
Here’s what the above room looked like on my end. Maybe you can tell me if it’s showing duplicates or pulling cards from the rest of the boosters.

![dr4ft bug 0 5x](https://user-images.githubusercontent.com/735024/53043976-55ea7400-344f-11e9-8d42-eac5dac4c13a.jpg)

**Comment by ZeldaZach** [comment]
We agreed this was a cache bug, and is not a concern.
