### ISSUE TITLE
Draft Log

### ISSUE THREAD

**Issue by HerveH44** [dr4fters/dr4ft#34]
Hi, 

I've been trying to make a draft log from the app. I'll suggest a pull request, tell me if it's fine ! 

I tried, and it works with the site : http://magic.flooey.org 
I contacted them, and they replied that my file is fine. 

Let me know, what you think about it,

Herve

**Comment by tooomm** [comment]
Do you have this change running on a site so that i can see it in action?

**Comment by HerveH44** [comment]
Actually no, I'm trying to put it on Heroku but it's not that simple. I'll try in the next few days but I'm quite busy at the moment. 

It's easier to create on your own computer, I don't know if you're familiar with it.

If you want, I could add some pictures and log files to give a bit of a hint.

**Comment by tooomm** [comment]
Just tested it with a draft on the beta site. It works nicely and is a charm to use on that page.
Too bad it's just your data and not from all drafters.

This issue can be closed once you update your main site @dev-id ?

**Comment by tooomm** [comment]
The main site is updated in between. This can be closed.
