### ISSUE TITLE
iPad: title of download box displayed wrong

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#351]
Running iOS 12.1.4

Once in a game, there are boxes for "Lands", "Settings" etc.
While their titles are displayed correctly, the "Download" box title label is stretched over all box length.

On Windows with Firefox the same box looks ok.

**Comment by ZeldaZach** [comment]
Do you have a screenshot?

**Comment by ZeldaZach** [comment]
<img width="340" alt="screenshot 2019-02-26 15 44 23" src="https://user-images.githubusercontent.com/7460172/53445080-bf352e80-39dd-11e9-8235-786819ac84df.png">

Duplicated on safari

**Comment by ZeldaZach** [comment]
cc: @benjaminpwagner

**Comment by tooomm** [comment]
![img_0052](https://user-images.githubusercontent.com/9874850/53494711-a93b7280-3a9e-11e9-8a65-0c923727e550.PNG)
