### ISSUE TITLE
issues with new box layout

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#357]
This is related to https://github.com/dr4fters/dr4ft/pull/346 and https://github.com/dr4fters/dr4ft/pull/352

- when there are only fewer people (2 friends doing a sealed for example), there is a gap between `Game` and `Settings` box:
![layout1](https://user-images.githubusercontent.com/9874850/53404651-61d9b700-39b6-11e9-9a87-c6241c0484de.png)

- the distance between boxes is not identical, maybe the added margin (that `Settings` doesn't overlay anymore) differs from the rest?
![layout2](https://user-images.githubusercontent.com/9874850/53404655-630ae400-39b6-11e9-94c4-807523b7fad5.png)

CC: @benjaminpwagner

**Comment by HerveH44** [comment]
@benjaminpwagner  I can't remember why there's a control on the "Setttings" Panel to put it behind the player panel. It seems really odd to me, and it doesn't seem to be correlated with your nice timer HUD because it works nice whereever is the settings panel. Do you remember maybe ?
