### ISSUE TITLE
bug: pick timer broken on last pick

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#371]
With disabled immediate auto pick for the last card, there is a timer issue.
The timer should still run for the last card and auto pick after the timer run out.

![timer](https://user-images.githubusercontent.com/9874850/53497745-27027c80-3aa5-11e9-808c-d9effd5b3dee.png)

CC: @HerveH44

**Comment by ZeldaZach** [comment]
This is more an issue for @benjaminpwagner probably
