### ISSUE TITLE
Use better mana symbols

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#387]
[symbology.zip](https://github.com/dr4fters/dr4ft/files/2935030/symbology.zip)

use the mana symbols from that zip file instead of the meh ones we pull from wizards :)

**Comment by HerveH44** [comment]
Is there a website where we could download them (and not overcharge our bundle)? Or we put them directly in our website?

**Comment by ZeldaZach** [comment]
My thought is to throw them into a resources/ folder in the repo (only the ones we'd need)
