### ISSUE TITLE
Portal, Portal: Second Age, Portal: Three Kingdoms, and Starter 1999 missing

### ISSUE THREAD

**Issue by ancestral** [dr4fters/dr4ft#388]
Portal, Portal: Second Age, Portal: Three Kingdoms, and Starter 1999 are all missing. They were all products Wizards sold booster packs with.

Set codes (per MTGJSON):

POR
P02
PTK
S99

**Comment by HerveH44** [comment]
Theses are all with type "starter" in MTGJSON. I don't think they are supposed to be playable, but I'll have to investigate it a bit more. 

We'll have to check about the playability of all starter sets I think. We block these sets from being playable in the file src/data line 50

**Comment by ZeldaZach** [comment]
Should probably just put a check in to allow any set with more than 100 cards that's not a promo set

**Comment by ancestral** [comment]
Careful, that would leave out Arabian Nights then.

Is there a way to identify sets that were sold as booster packs?

**Comment by ZeldaZach** [comment]
Not easily... but frankly, we could just list all non-promo, non-fromthevault, etc sets

**Comment by tooomm** [comment]
>Should probably just put a check in to allow any set with more than 100 cards that's not a promo set

Something like that would have prevented that a not fully spoiled set with only 2 cards shows up already (https://github.com/dr4fters/dr4ft/issues/393).

**Comment by ancestral** [comment]
Can you just hardcode these?

**Comment by ucyd** [comment]
I'd guess is doable. I'm trying to get time spiral done, i'll probably look at it.

Do these starter sets follow the usual distribution for booster packs? Portal 02 does not have a boosterV3 value on mtgjson.
