### ISSUE TITLE
improve pre-selected default sets

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#389]
The default pre-selection is `Modern Horizons` from type `draft_innovation` currently.
Therefore I assume that always the most current set gets preselected when users come to the page for the first time?

For the majority of users though, this special sets are not interesting and since mtgjson has so much more of these now a better pre-selection could be to focus on sets from type core, expension and master maybe? The basic sets used at FNM events are the ones people are probably going to look for here as well. :)
The drop down list is is huge and it can be difficult to find the right set.

I know this can be seen as feature as well and is intended behaviour. Asking for opinions.

**Comment by benjaminpwagner** [comment]
I agree, it should probably default to the most recent standard set / set combo, i.e. What they are doing at FNM like you said.

**Comment by tooomm** [comment]
Thanks for taking care of this smaller things as well. 👍
