### ISSUE TITLE
MTGO import compatibility

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#39]
I'm wondering if dr4ft is compatible with the import functionality in MTGO?!
See: http://magic.wizards.com/en/articles/archive/importing-and-creating-decks
Is there any format you can download from the draft site working as an import there?

Why? Deck building practice and e.g. sealed preparation is just so much worse on the draft site or within Cockatrice...
Missing a simple kitchen table style building experience as with real cards. Filtering/Sorting as a nice-to-have on top.

**Comment by dev-id** [comment]
We'd need someone to test this isn't working (.txt is an export option), I do not currently have MTGO installed.

**Comment by ZeldaZach** [comment]
@tooomm can you test loading a draft deck in? I think the .txt file should work fine.

**Comment by tooomm** [comment]
I can't test it. Hence the ticket.

**Comment by HerveH44** [comment]
So there's no point in this issue right? If nobody cares to have MTGO export (nobody seems to have replied on this ticket), I'm wondering if we should ... 

I also don't have MTGO so can't help

**Comment by ZeldaZach** [comment]
Same, this isn't too useful imo.
