### ISSUE TITLE
modern horizons draft errors on start

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#393]
Doing a draft with 3x modern horizons errors currently

**Comment by ZeldaZach** [comment]
Modern Horizons has 2 cards, so it doesn't work. Not a shocker, and nothing we can do about it until the set is spoiled. Non-issue here.

**Comment by tooomm** [comment]
The error message could be more helpful then, telling you that the set has too few cards or something.

<br>

Anyway, such a set should then never be available in the dropdown in the first place!

Are sets beeing added to mtgjson during spoiler season successively?
I wasn't aware spoilers are beeing included... what's the source for that data then?
