### ISSUE TITLE
Map Print Runs

### ISSUE THREAD

**Issue by dev-id** [dr4fters/dr4ft#4]
Sealed paper packs are not random.  The cards are packed according to "(print) Runs".  The runs are created to allow for a balanced drafting experience.  They ensure that each pack has a certain balance of colors and power.

You can see some detailed information in this video: https://youtu.be/LnCyHJUGg7k which uses this data: https://docs.google.com/spreadsheets/d/1AtO2LGrVxKqfhvZ01zwhBzkDj1XGRFOoj_i7mf5CRTI/edit#gid=1168895507

In that example, Kaladesh has 4 distinct common print runs.  Packs of KLD will have 2-4 cards from Run A, 2 or 4 cards from Run B, and depending on how many cards from Run A, either 5-6 cards from Run C1 or 4 cards from C2.  

I have not ascertained the frequency of the double-size Run B or the relative frequencies of C1 and C2.

**Comment by ZeldaZach** [comment]
Seems way too complex to make this accurate and work as expected. Sorry :(
