### ISSUE TITLE
Inform users to change their name

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#42]
Copied over from old repo: https://github.com/arxanas/drafts.ninja/issues/33

>Would be helpful to find opponents after draft or to check who is missing... or if all correct people are in the room etc.

**Comment by dev-id** [comment]
Not sure if this is desirable, maybe lump this in with a future login system

**Comment by ZeldaZach** [comment]
It's a good idea, but not worth the implementation right now. I suggest making an easier way for users to know to change their name (maybe a header appears saying to change it / how to change it)

**Comment by HerveH44** [comment]
We actually don't have any easy way to create modals, maybe we could choose some library using components pre-made (for example modals). I ony used bootstrap a long time ago, maybe there's something new. Could be interesting to investigate a bit?

**Comment by tooomm** [comment]
A popup asking for your nick if you join a game room with the default nick... hmm, why not.

A login system seems to be totally overkill and makes things a lot more complicated.
