### ISSUE TITLE
add info about game type/packs to room

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#44]
Copied over from old repo: https://github.com/arxanas/drafts.ninja/issues/34

>(Just had a game where somebody left after he realized that the draft was to test the new set (tripple emn draft) instead of being a perfect styled emn-emn-soi draft. Draft got destroyed in last pack.)
>
>In general a nice information and avoids problems.
>It should be displayed inside the room, as well as outside.
>
>It could be in a new box next to settings/players. Or as some kind of headline?
Could also be removed completely once the draft starts or when it finishes to get replaced by the lands box for example.
>
>This information used to be around and got removed in your fork.

To stress, and further clarify this issue I'll attach two screenshots:
- view as `room creator`:
![host](https://user-images.githubusercontent.com/9874850/32980451-e0d758f0-cc66-11e7-9606-8e658c250b9f.png)

- view as `joined player`:
![joined_player](https://user-images.githubusercontent.com/9874850/32980442-aa4f7c22-cc66-11e7-83b8-5e98fc6c6e43.png)

So as long as a player joins a draft over a link he has no clue what he actually joined, and what he is going to play. The host could fool around with them, or the player could easily end up in a scenario as mentioned above.
There should be a `Game Information` or `Room Type/Settings` panel for everybody. Instead a `Start Game` one only for the creator.

*My suggestion is to change the name and content a bit (#22), make it available to all players and only display the <kbd>Start Game</kbd> button for the creator/admin of the room.*

<br>

Linking #19 here as well.

**Comment by HerveH44** [comment]
Fixed with PR #84
