### ISSUE TITLE
WAR has Guildgates?

### ISSUE THREAD

**Issue by hitz** [dr4fters/dr4ft#444]
I did a WAR sealed and got a simic guildgate and 8 planeswalkers.   Maybe the second is allowed but pretty sure the first isn't :)

**Comment by ZeldaZach** [comment]
Each pack gets a planeswalker, that is confirmed. We have no confirmation if guildgates are included or not, but this seems fine right now. I'll re-address after pre-release if needed.

**Comment by Raszero** [comment]
Hey Zelda, the pre-pre release from LRR happened and theres no guildgates.

I appreciate you having this up so quick massively, but I was holing to use this to practise for Magicfest London (which is WAR Sealed on pre-release weekend) so if you could update this before it'd be a massive help.

**Comment by ZeldaZach** [comment]
Gotcha I’ll look at addressing tonight then

**Comment by Raszero** [comment]
Sweet, thanks! FYI The 2 guildgates are in because of the planeswalker decks, thats why they popped up

**Comment by artofvs** [comment]
All the cards with collector number more than 264 should not be in packs. There is 11 of them (https://scryfall.com/sets/war?order=set at the bottom)

**Comment by SeismicLawns** [comment]
Guildgates have been removed, but Planeswalker deck cards are still in, incorrectly (collector's numbers 265-275). Cards like Jace's Projection aren't meant for limited.

**Comment by ZeldaZach** [comment]
The issue is I need a new MTGJSON build to fix it. I have the wrong base size. I’ll need to wait a few more days. Sorry.

**Comment by ZeldaZach** [comment]
Fixed
