### ISSUE TITLE
Chat duplication

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#449]
In a game, if I close chat and reopen, then send msg it appears twice. maybe it's because one is me sending and the other is a global receive? Seems off and a regression

**Comment by HerveH44** [comment]
Hey Zach,

I can't reproduce. What do you use exactly? 

I tested on Ubuntu18.04 Firefox and Chrome and it's working as expected.

**Comment by ZeldaZach** [comment]
🤷‍♂️ It was buggy in my 3 player, 5 bot game last night. Single player i don't see the issue.

**Comment by tooomm** [comment]
In my draft with 7 bots, hiding and showing the chat window again doesn't make new message that I post appear twice. Also closing the page and reopening the game url changes nothing.

Maybe several real players have to be involved.

**Comment by ZeldaZach** [comment]
Prob an issue that I caused somehow. Will close for now.
