### ISSUE TITLE
Pack Building

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#454]
For modern-based sets, packs should be generated as follows (afaik):

1 card from pool of red commons
1 card from pool of green commons
1 card from pool of blue commons
1 card from pool of black commons
1 card from pool of white commons
1 card from pool of colorless/land, if applicable
4 card from pool of commons not already selected
3 uncommons, of which they are not _all_ the same color (i.e. red, red, blue is fine)
1 rare/mythic of any kind

**Comment by HerveH44** [comment]
How can we distinguish if a set is "Modern-based" from MTGJson?

**Comment by ZeldaZach** [comment]
We can just say sets based on date are modern. Pick 8th edition forward.

**Comment by MotherofRuins** [comment]
Try to leave out cards only available in Planeswalkers decks

**Comment by ZeldaZach** [comment]
The `isStarter` flag indicates cards that cannot appear in packs. We already ignore this

**Comment by http404error** [comment]
I've been doing some research lately into the statistics of pack generation and while your model is not bad, I think it can be improved further (without going as far as replicating print runs themselves). I don't have a super-solid model yet (and I don't have enough info on artifact or multicolor sets yet, or how foils change the other assumptions).

The biggest takeaway I'm confident claiming so far is that there's not just a rough guarantee of at least 1 common per color, but a high chance of there being exactly 2 commons of a given color (70-80% per color). I'm not sure there's a guarantee of 1 colorless card per pack; if you have good info on that, it would be very useful for me to know.

**Comment by ucyd** [comment]
Well, the Magic 2015 "postmodern" border was created to collate sets better. I'd guess ensuring that all colors are represented would have been easier from m15 afterwards.

> Making the bottom of each card black to accommodate this information was not an easy decision, and may be the most disconcerting part of this frame update, but it was done with the best of intentions. This information is machine-readable by recognition software at our production plants. It will help eliminate the rare packaging error, like cards sneaking into the wrong expansion's boosters. - https://magic.wizards.com/en/articles/archive/making-magic/directors-chair-2013-2014-01-06

@http404error @ZeldaZach do you get any source on that info?

**Comment by http404error** [comment]
@ucyd The "rules" are derived from how print runs work. What we know about print runs is based on a mix of some public knowledge about printing, some statements by Wizards, and just collecting data by opening boosters. By seeing patterns in how the print runs are laid out, we can infer the rules/ideals that Wizards uses to create them, and replicate those rules without doing the full process ourselves (though we *could* if we had enough data on a set).

Examples of sources and data:
- https://markrosewater.tumblr.com/post/184342924408/hey-maro-i-recall-ive-read-somewhere-that
- https://imgur.com/a/3tphD
-https://www.reddit.com/r/lrcast/comments/6c7bjs/amonkhet_common_print_run_breakdown_and_analysis/
- https://www.reddit.com/r/lrcast/comments/3qb62b/battle_for_zendikar_common_print_run_analysis/
- https://www.reddit.com/r/lrcast/comments/ahppmj/mtg_arena_rna_uncommon_print_run/

**Comment by HerveH44** [comment]
@ZeldaZach it seems that it's still very unsure what to implement. Should we keep this issue open or close it and wait until a clear idea has arisen on the other ticket (mtgjson)?

**Comment by ZeldaZach** [comment]
Upstream may never support a new version of boosters. I’ll write up my proposal for tonight here and we’ll just go with it. Will probably be similar to my initial post in this ticket.

**Comment by HerveH44** [comment]
@ZeldaZach what's up?

**Comment by ZeldaZach** [comment]
I'll get around to this soon. Sorry for delay.

**Comment by HerveH44** [comment]
@ZeldaZach As you may have seen in the PR #798 I'm currently heading towards delegating the booster generation to @taw's project. I think it's way better to concentrate on just the draft game and the webapplication instead of implementing badly booster generation. 

That's also my take on bots. I prefer to delete our bad "score" implentation (that doesn't even check sets or cards that have been in the past) to keep the bots pick randomly. This is clearly a "bad bot" but until we find a library or project that we can use to implement a true good bot, I think that's reasonable to focus dr4ft on the game not on bots or pack generation.

**Comment by ZeldaZach** [comment]
Agreed. I’ll hit up some people for help on draft bots.
