### ISSUE TITLE
Beep on first pack missing (Pack 1 / Pick 1)

### ISSUE THREAD

**Issue by MotherofRuins** [dr4fters/dr4ft#465]
Please have the Beep occur for the first pack as well as all subsequent.  I rely on that beep when multitasking while room fills.

**Comment by tooomm** [comment]
Did I get this rigjt? It works for pack 2 and 3?

**Comment by MotherofRuins** [comment]
The beep happens for all packs except Pack 1 Pick 1

**Comment by tooomm** [comment]
Thanks for the clarification that only the very first pick in the first pack is problematic.

Hopefully Zach or Herve can have a look.

**Comment by MotherofRuins** [comment]
Windows 7 SP1
Chrome  74.0.3729.157

**Comment by tooomm** [comment]
With Chromium Version 74.0.3689.0 it works for me, too...

**Comment by HerveH44** [comment]
@MotherofRuins could you try with another browser just to see if it comes from Chrome? 

From source code, we don't make any difference between p1p1 and any other pick.

**Comment by ZeldaZach** [comment]
I have no issue with this personally...

**Comment by MotherofRuins** [comment]
Here's the best information I have so far:

Chrome or Firefox, hosted 8 man drafts with bots, it works properly.
(IE I was unable to give javascript permission)

Chrome, 8 man real draft, hosted by someone else, p1p1 no beep, all 35 others are there.
So, does the beep work for the host but not the others?
Next step is host an 8 man real draft, it may take a while, will advise

**Comment by MotherofRuins** [comment]
Host a draft locally.  Join said draft remotely from another computer.  Start draft.  Beep happens.

Host a draft on remote computer.  Join said draft locally.  Start draft.  Beep does not happen.

It appears that all beeps occur for the draft host and all but p1p1 occur for guests.  

The p1p1 beep is the most important one, because if a person is a guest and they join a draft but get sidetracked, the beep notifies them.  Otherwise they can miss picks and/or make other people angry.

**Comment by tooomm** [comment]
@MotherofRuins I tested again and joined a game as guest. When the host starts the game I correctly get the beep for the first pack as well! (Firefox 70.0.1)
