### ISSUE TITLE
WAR planeswalkers always show as Japanese-language version

### ISSUE THREAD

**Issue by lukasschwab** [dr4fters/dr4ft#476]
Draft/sealed War of the Spark packs include Japanese-language alternate art planeswalkers instead of their English-language equivalents; all the other cards are English-language.

<img width="259" alt="Screen Shot 2019-05-13 at 10 08 44 AM" src="https://user-images.githubusercontent.com/4955943/57640468-77975b00-7567-11e9-98c4-7ed81dc89416.png">

This is new in the last 24 hours.

**Comment by MotherofRuins** [comment]
Please revert.

**Comment by ZeldaZach** [comment]
This revolves around us needing to validate inputs better. We need to parse out all isAlternatives probably.

**Comment by tooomm** [comment]
I guess many users looked for other services because this isn't fixed.

**Comment by ZeldaZach** [comment]
Is an issue again
