### ISSUE TITLE
Time Spiral

### ISSUE THREAD

**Issue by 7stringplayer** [dr4fters/dr4ft#482]
Time shifted cards are missing from Time Spiral packs

**Comment by ucyd** [comment]
I noticed that. Time spiral packs are put from 2 sets.

> Time Spiral is the first set since Alliances to distribute cards in boosters differently from the typical eleven commons, three uncommons and one rare format. Instead, they included ten commons, three uncommons, one rare and one purple-rarity timeshifted card. Tournament decks contained three timeshifted cards, replacing three commons.  - https://mtg.gamepedia.com/Time_Spiral#Marketing

Do the timeshifted cards have some sort of rarity between then, or are they all "timeshifted common"?

**Comment by 7stringplayer** [comment]
No it was just a random one per pack

**Comment by 7stringplayer** [comment]
Doesn’t look like it’s fixed

**Comment by ZeldaZach** [comment]
Will rebuild .info at some point tonight or tomorrow

**Comment by tooomm** [comment]
Tried to start a game with 3xTSP and the game crashes.
3 other Boosters work fine...

**Comment by HerveH44** [comment]
@ZeldaZach 
Have you reconstructed the sets? It could be the reason the game crashes, because it couldn't find TSB set. To be sure, just run "node src/make/update_database.js"
Also, could it be possible to get the logs?

**Comment by ZeldaZach** [comment]
Yeah I forgot to update sets. Try again

**Comment by tooomm** [comment]
Same. Game crashes

**Comment by HerveH44** [comment]
@ZeldaZach if you paste the logs, I think we can find the problem. It works fine on my computer (after clean installl)

**Comment by ZeldaZach** [comment]
Working until 5ish but I’ll clean the data folder again later tonight and get logs here

**Comment by HerveH44** [comment]
Thanks!

**Comment by ZeldaZach** [comment]
Cleaned and rebuilt and tested. Works as expected.
