### ISSUE TITLE
Card search capability

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#49]
During deck building it would be very handy to have some kind of card search to check e.g. how many deserts you have or if your trial is supported by enough cartouches etc. without going trough all cards in your color.
Would also help with analyzing for specific keywords (like cycle) to evaluate if special archetypes are worth playing and much more.

Depending on how this is implemented and how powerful it would be, it's a kinda big project. :)

**Comment by HerveH44** [comment]
I feel that's way to hard to implement. I think this issue got his life and we should close it.

**Comment by ZeldaZach** [comment]
Clearly I didn't read this close enough. Seems overkill. Agree w/ closing :)
