### ISSUE TITLE
Modern Horizons packs don't have snow basics in sealed

### ISSUE THREAD

**Issue by Luke-Patterson** [dr4fters/dr4ft#495]
Pretty much what the title says.

**Comment by tooomm** [comment]
The problem only occurs in sealed? In draft it works for you?

**Comment by samfin** [comment]
Draft doesn't work either.

**Comment by ucyd** [comment]
There should be one per pack.

https://magic.wizards.com/en/articles/archive/card-preview/modern-horizons-tokens-and-art-series-2019-05-30
