### ISSUE TITLE
River Heralds' Boon misspelled

### ISSUE THREAD

**Issue by JineteDV** [dr4fters/dr4ft#50]
'River Heralds' Boon' is correct, 'River Herald's Boon' is what I got when I downloaded a draft deck.

**Comment by dev-id** [comment]
Thank you, appears this error comes from our Scryfall data source, I have reported it and am waiting a fix: https://github.com/scryfall/feedback/issues/389

**Comment by tooomm** [comment]
Fixed on scryfall and in newest https://github.com/Cockatrice/Magic-Spoiler/blob/files/spoiler.xml now.
