### ISSUE TITLE
Can draft with more than 3 packs

### ISSUE THREAD

**Issue by MotherofRuins** [dr4fters/dr4ft#509]
If you choose any number of packs greater than 3, it lets you create the room.  In the room it might say, eg. "Info: MH1 / MH1 / MH1 / MH1 / MH1 / MH1 / MH1".  But it stops generating new packs after drafting the third pack.

**Comment by HerveH44** [comment]
Working on it. There is something blocking the draft to 3. I'll publish a pull request ASAP
