### ISSUE TITLE
Xln Database and draft time setting

### ISSUE THREAD

**Issue by hrefrossi** [dr4fters/dr4ft#51]
hi there 
i set a local host of dr4fer, but i can not find the latest release XLN data, how could i get it .
another question how could i change the time setting of draft. i want double the time for it .

thank you very much

**Comment by tooomm** [comment]
You have 4 different time settings available. If the slowest `Leisurely` still isn't enough you have to change the code. Check the pull requests that last changed them here in the repo to find out where to look in the code.

For including XLN cards you need to provide a `allsets.json` file (with XLN already included), there is no support yet for different single databases: https://github.com/dr4fters/dr4ft/issues/37.
You can find that combined database in the `files` branch of [Cockatrice/Magic-Spoiler](https://github.com/Cockatrice/Magic-Spoiler/) repo for example.

**Comment by hrefrossi** [comment]
thank you tom very helpful

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
