### ISSUE TITLE
advanced hide packs feature

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#512]
While https://github.com/dr4fters/dr4ft/pull/385 implemented a first working version of https://github.com/dr4fters/dr4ft/issues/45...

...there are some things left that expand the feature further:

>allow this option to be a forced "host" option additionally, not only a players choice option

>implement review time in between packs like in real tournaments (depends on the first to not delay a normal draft where a player just decides to hide his picks on his own for whatever reason)

**Comment by ZeldaZach** [comment]
No fix
