### ISSUE TITLE
Have proper version + date in footer

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#518]
Not only show the commit as version, but also the version if it's a tagged commit.
As well as a build date of the website 👍 

Example: `Running Version: v0.2.4 (build on 2019-06-19)`

**Comment by ZeldaZach** [comment]
I could agree with this

**Comment by HerveH44** [comment]
There is no real "build", only the frontend is transpiled but i'm not quite sure there is an information about when. 

Only thing we could do is take the information on Git last commit date

**Comment by HerveH44** [comment]
TODO: check that webpack plugin : https://www.npmjs.com/package/git-commit-info-webpack-plugin

Maybe others exist too.

**Comment by HerveH44** [comment]
We could also get the version of MTGJson sets we used ...

**Comment by ZeldaZach** [comment]
Can show git date/hash and mtgjson date/version on the page

**Comment by HerveH44** [comment]
![image](https://user-images.githubusercontent.com/16805904/59858645-ac26df80-937b-11e9-86fa-1027ef2f7d2d.png)

**Comment by tooomm** [comment]
If the commit is a tagged version we don't have to display its hash - can we only link to the release in that case?

With the date, it might be easier to simply have `build 2019-06-20`, or at least without day of the week `build Jun 20, 2019`
