### ISSUE TITLE
commit // memory and never // return don't parse in cubes

### ISSUE THREAD

**Issue by derektumolo** [dr4fters/dr4ft#520]
http://www.cubetutor.com/viewcube/107859

connive // concoct works when i fix it, but Never // Return doesn't parse, and neither does Commit // Memory

**Comment by ZeldaZach** [comment]
cc: @HerveH44

**Comment by derektumolo** [comment]
Just to confirm, is Commit // Memory fixed as well? It's not aftermath, just split.

**Comment by ZeldaZach** [comment]
C/M is an aftermath card... 😅

**Comment by derektumolo** [comment]
So it is.... 
Got confused. Cubetutor export also broke connive // concoct and expansion // explosion (exported without second half). 
Thanks for fixing so quickly!
