### ISSUE TITLE
Create tool to convert Cockatrice.xml -> MTG.json

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#559]
Most custom sets people want to upload are Cockatrice-xml based. We should either accept them or create a tool to conver them to mtgjson-json format

**Comment by caelen-feller** [comment]
While it's not a direct solution, it's worth noting that those who are making custom sets often have access to a Magic Set Editor file, which can be converted using [this project](https://github.com/fenhl/mse-to-json/). I've yet to get it to work when uploading to the site though. I'll open a seperate issue for that.

**Comment by HerveH44** [comment]
This should be a parser from cockatrice XML v4 or v3?

**Comment by ZeldaZach** [comment]
V4 probably

**Comment by HerveH44** [comment]
I was thinking of a Go commandline tool. @ZeldaZach Do you think it's fine?

**Comment by ZeldaZach** [comment]
I’d highly recommend Python over Go here, just because of adoptability. I personally would be fine with it, but I’m thinking longer term when someone else comes to modify it.

**Comment by HerveH44** [comment]
I did a little test in go just for fun. Result is [here](https://github.com/herveh44/cockatricetomtgjson) (still work to do).

**Comment by HerveH44** [comment]
just to remember next what the cockatrice v4 format is : https://github.com/Cockatrice/Cockatrice/blob/master/doc/carddatabase_v4/cards.xsd

**Comment by HerveH44** [comment]
@ZeldaZach reading the xsd file, I'm surprised that no "prop" is defined (carddatabase -> cards -> card -> prop) while in the wiki it's written :

> 

Property name | Description
-- | --
layout | The card layout, eg. normal, split, transform
side | For normal cards this property defaults to front. Set it to back to specify that this card is the back side of another card.
type | The full type of the card, eg. Legendary Creature — Spirit Cleric
maintype | The main type of the card, eg. Creature
manacost | Card mana cost, eg. 1WU
cmc | Card converted mana cost, eg. 3
colors | card colors, eg. UW. If your card is colorless, then you may safely omit this tag.
coloridentity | Card color identity, eg. WU. If your card is colorless, then you may safely omit this tag.
pt | Card's power/toughness. If the card doesn't have a p/t, you may safely omit this tag.
loyalty | Card's starting loyalty total. If the card doesn't have a starting loyalty, you may safely omit this tag.
format-* | Specify that the card is legal of that game format, where  is the game format, eg. standard, modern. The property value must be legal. You can add one or more format- tags for each format


Is it something normal? I mean, should I expect any kind of property?
