### ISSUE TITLE
Error on custom set upload

### ISSUE THREAD

**Issue by caelen-feller** [dr4fters/dr4ft#565]
I get the following response on uploading the custom set during the http request to https://dr4ft.info/api/sets/upload, with status 400.

`"the json submitted is not valid: TypeError: Cannot read property 'includes' of undefined"`

The custom set json file can be found [here](https://gist.github.com/caelen-feller/aaa386b26a59e622029550a7cc27ce9e) and is a one card test file.

**Comment by caelen-feller** [comment]
Update: The issue is a missing "supertypes" field. Probably easier to fix the tools which created this json file than support the derivation of this field from originalType or types, as I belive it is part of the standard which is missing. Please reopen if you feel it's worth supporting.

**Comment by tooomm** [comment]
Could we validate those custom set files on upload against a xsd and print a more helpful error to the user?

**Comment by caelen-feller** [comment]
I don't have that comparision, unfortunately. They were a private project with others I cannot share at this time, and were converted directly from an MSE file using [this project](https://github.com/fenhl/mse-to-json). 

The script simply did add the "supertypes" field to cards. I modified the script to provide an empty supertypes array, ideally it would be the correct one, but this sufficed for my purposes at the time. I'll be pushing a change with the fix when I do it properly.

**Comment by caelen-feller** [comment]
For reference, given a Cockatice format XML, there is no `supertypes` field.
Here are the reference cards given in their docs: 

`type` is not formally decribed for Cockatrice V3, but in both it should include  "The full type of the card, eg. Legendary Creature — Spirit Cleric". As such, it is possible to parse the supertype - here "Legendary" from it. However, for the purpose of drafting with humans on dr4ft, this field is not necessary to use a custom set file if you do not include custom basic lands. Outside of Dominaria pack generation, it is used only to identity these by dr4ft at time of writing. 

### Cockatrice V4
```xml
<card>
  <name>Card name</name>
  <text>Card description and oracle text, including actions, effects, etc..</text>
  <token>1</token>
  <cipt>1</cipt>
  <upsidedown>1</upsidedown>
  <tablerow>3</tablerow>
  <set rarity="common" uuid="12345678-abcd-1234-abcd-1234567890ab" num="42" muid="123456" picurl="http://.../image.jpg">XXX</set>
  <related>Another card name</related>
  <reverse-related>Another card name</reverse-related>
  <prop>
    <layout>normal</layout>
    <side>front</side>
    <type>Instant</type>
    <maintype>Instant</maintype>
    <manacost>R</manacost>
    <cmc>1</cmc>
    <colors>R</colors>
    <coloridentity>R</coloridentity>
    <pt>0/2</pt>
    <loyalty>4</loyalty>
    <format-standard>legal</format-standard>
    <format-commander>legal</format-commander>
    <format-modern>legal</format-modern>
    <format-pauper>legal</format-pauper>
  </prop>
</card>
```
### Cockatrice V3
```xml
<card>
    <name></name>
    <set picURL=""></set>
    <related></related>
    <color></color>
    <manacost></manacost>
    <cmc></cmc>
    <type></type> 
    <pt></pt>
    <loyalty></loyalty>
    <tablerow></tablerow>
    <text></text>
    <token></token>
    <cipt></cipt>
</card>
```
### MTG JSON
```json
"CardName": {
        "colorIdentity": [
            "G",
            "U"
        ],
        "colors": [
            "G",
            "U"
        ],
        "convertedManaCost": 4.0,
        "foreignData": [],
        "layout": "normal",
        "manaCost": "{2}{G}{U}",
        "name": "CardName",
        "power": "12",
        "printings": ["setName"],
        "rulings": [],
        "subtypes": [
            "Kraken"
        ],
        "supertypes": [
            "Legendary"
        ],
        "text": "{T}: Add {G}{U}.",
        "toughness": "12",
        "type": "Legendary Creature — Kraken",
        "types": [
            "Creature"
        ],
        "uuid": "e853836c-949a-52bd-a766-3133e0f6fbe4"
    },
```

**Comment by caelen-feller** [comment]
Sorry, the new error is on game start, this issue is irrelevant.
