### ISSUE TITLE
ESLint cleanup + fix

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#577]
All travis builds throw a bunch of eslint errors since months.
https://travis-ci.com/dr4fters/dr4ft

Edit: It even errors completely and doesn't even run anymore.

**Comment by caelen-feller** [comment]
I'll give it a try this weekend, would like to get to know the project more. Do you suggest just running the linter on it and working through the various issues, or are further complications expected?

**Comment by ZeldaZach** [comment]
Hey @caelen-feller if you'd like to join us on the dev chat, we use Discord (https://discord.gg/74GUQDE) we can probably point you in a decent direction :)

**Comment by t-moennich** [comment]
Sorry @caelen-feller , just din't saw any progress on this and so I create a first starting PR :hugs:

**Comment by caelen-feller** [comment]
Ah, I messaged the discord about it to no reply after fixing it locally, and just forgot about it! Looks like we took more or less the same path, thanks!

**Comment by tooomm** [comment]
Hmm, too bad your message in discord got somehow missed...
But happy to read your reply here and that you think his changes are similar to your approach.
