### ISSUE TITLE
Chaos Draft not working

### ISSUE THREAD

**Issue by arobotcat** [dr4fters/dr4ft#588]
Hey love the site, I noticed that the chaos mode on draft isn't working. Not with total chaos or modern only. I cleared cache, tried several devices. I appreciate all that you all do!

**Comment by HerveH44** [comment]
Hi, 

@arobotcat Is it still broken? I tried different times on dr4ft.info and it worked fine.

**Comment by tooomm** [comment]
@HerveH44 Yes, problem persists for me.
Tried with the heroku version of your recent PR and on dr4ft.info.

One can start a Chaos Draft, but no cards show up to pick... :)

**Comment by HerveH44** [comment]
Ok, I understand. The problem is Chaos Draft, not Chaos per se. I'll push a PR soon. It's an error since my last refactor of the pool.js

**Comment by tooomm** [comment]
Yes. Only Chaos draft is affected as stated in the other issue.
Chaos sealed works!

**Comment by arobotcat** [comment]
Hey, it might be the pc that I'm trying it on, but the cards still aren't
showing up. They show up in all the other modes, but in chaos draft with
and without the total chaos selected it doesn't work (the cards don't show
up).

Love all the great work!

Evan

**Comment by arobotcat** [comment]
Hey, I tried it on another computer and it worked fine!

Thanks so much for your help

**Comment by ZeldaZach** [comment]
Aweseom!
