### ISSUE TITLE
Card Text Box

### ISSUE THREAD

**Issue by thinkingofmaud** [dr4fters/dr4ft#614]
Option to show the card text, instead of the card picture, on the dr4ft client.

**Comment by HerveH44** [comment]
What kind of text you would like exactly? If I remember correctly, we already show the card's name when the image can't be loaded.

**Comment by tooomm** [comment]
I think he means the oracle text.

**Comment by ZeldaZach** [comment]
Tom is correct here.

We'd want to show 
```
Card Name {COST}
Card Type | Rarity
Card Text
Power/Toughness/Loyalty
```

in a bounding box

**Comment by HerveH44** [comment]
I'm working on it. What do we do for the Cols feature? The cards are only shown for a tiny bit. I can't show any text ...

**Comment by ZeldaZach** [comment]
Card name and CMC only for column view
