### ISSUE TITLE
Chaos Draft not working

### ISSUE THREAD

**Issue by Throwaway-Account1** [dr4fters/dr4ft#622]
Hey! When I go on the website and try to chaos draft, no matter what settings I use, if I do a chaos draft the packs never load and nothing happens.

**Comment by tooomm** [comment]
Problem confirmed for drafting.

Chaos Sealed works!

**Comment by tooomm** [comment]
Another current report on reddit: https://www.reddit.com/r/Cockatrice/comments/dpxyoq/dr4ftinfo_chaos_draft/

**Comment by HerveH44** [comment]
duplicate #588
