### ISSUE TITLE
ELD adventure cards on dr4ft need their names changed to work with cockatrice

### ISSUE THREAD

**Issue by mythicrar** [dr4fters/dr4ft#624]
cockatrice doesn't read the adventure cards from dr4ft because they don't have the adventure in the name : so for example, "Ardenvale Tactician" is how the card name  appears from dr4ft but in cockatrice it's "Ardenvale Tactician // Dizzying Swoop"

**Comment by tooomm** [comment]
There is finally a fix for this. 🙈 
Sorry for the delay, we are reviewing it currently and then it needs to get deployed...

Thanks a lot for letting us now @mythicrar!
