### ISSUE TITLE
ELD - missing some commons and uncommons on the beta dr4ft site, probably some rares too

### ISSUE THREAD

**Issue by mythicrar** [dr4fters/dr4ft#625]
bloodhaze wolverine and mad ratter for example

**Comment by HerveH44** [comment]
@mythicrar can you check again now? From my point of view the problem got solved with new updates of MTGJSon files

**Comment by tooomm** [comment]
The two named cards are definitely available in between.
This is most likely solved with the new mtgjson data. As automatic card data updates should work soon again, we can prevent such issues in the future hopefully.

Feel free to reopen if there are still cards missing @mythicrar!
