### ISSUE TITLE
hide "Download Draft Log" button for any non-draft games

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#63]
If you play a sealed game you get this:
![draft log](https://user-images.githubusercontent.com/9874850/31772321-99b064c4-b4df-11e7-8878-1f16ae611734.png)

The option should only be available for:
- `Draft`
- `Cube Draft`
- `Chaos Draft`

Maybe even don't collect data at all to not slow things down for no reason.

**Comment by HerveH44** [comment]
I set it up on y refactor_frontend

**Comment by tooomm** [comment]
@HerveH44 just had a look at your updated heroku app again:

It's correctly hidden on `sealed` and `cubesealed`.
And correctly displayed on `draft`, `cube draft`.

But it's hidden on false in `chaos`. Which is draft as well!

**Comment by tooomm** [comment]
Addition:

The `Add picks to sideboard` and `Beep on new packs` options are also not needed for all non-draft **Sealed** game options.

**Comment by HerveH44** [comment]
Hey,

Indeed, the `beep on new packs` doesn't make much sense.

On the other hand, the `add picks to sideboard` is very usefull also for Sealed. This is typically how I create my sealed, starting with sideboard and adding to the main cards. I'd prefer to keep it

**Comment by tooomm** [comment]
I wasn't aware it works like that for sealed.
The wording doesn't clearly imply this behavior. :D
Interesting though, that sounds useful!

(A rename or some other tweak for the `sideboard` option is still possible later)
