### ISSUE TITLE
Selecting game mode cube breaks the page

### ISSUE THREAD

**Issue by ebbit1q** [dr4fters/dr4ft#645]
Since very recently the entire page just erases itself if you select the game mode cube.

You can open the page just fine but if you click the radio button every single element on the page is deleted.

**Comment by ZeldaZach** [comment]
Just noticed this myself... super weird

**Comment by ebbit1q** [comment]
Well it's really annoying.

**Comment by ZeldaZach** [comment]
I reverted the break, will be redeploying

**Comment by ebbit1q** [comment]
Fixed it https://github.com/dr4fters/dr4ft/commit/afc51a94ee5f2fcc27560ea9097d4aae22d0505f

**Comment by tooomm** [comment]
Well, I pointed that already out 3 weeks ago in the initial PR: https://github.com/dr4fters/dr4ft/pull/626#issuecomment-533965113

I also informed Zach in Gitter... :/
