### ISSUE TITLE
disable instant autopick for last card in pack

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#65]
Let people pick the last card instead auto-adding it immediately.
Mostly it's a card that you rather put into your sideboard or junk.
Right now you have to search for it in between your other playables in main to move it again all the time.

**Comment by HerveH44** [comment]
@tooomm What do you think about this issue now? is it still important? As for me I never felt it as a problem

**Comment by tooomm** [comment]
It still annoys me in every draft. :)
There might be other, more important things though.

**Comment by ZeldaZach** [comment]
I do agree this is annoying. Maybe wait a few seconds before autopicking.
