### ISSUE TITLE
problem with starting draft

### ISSUE THREAD

**Issue by braither90** [dr4fters/dr4ft#666]
Hi all guys i have a problem with the site (dr4ft.info) i can create easily the draft room and people can join it but when i click "start game" gives me this error : "Whoops! An error occurred while starting the game. Please try again later. If the problem persists, you can open an issue on the Github repository: https://github.com/dr4fters/dr4ft/issues" 
what can i do? :) thx so much for answer !

**Comment by tooomm** [comment]
Which settings did you use to create the draft room?

Does it always happen? Also if you select other booster to draft with for example? Maybe there is a problem with a certain set. Can you give some more details, please?

**Comment by Fyresis** [comment]
I've had the same issue the last few days. As far as I can tell, it applies to every format and every set, but I haven't tested all of them (I can confirm Throne of Eldraine and old ones such as Time Spiral don't work). Additionally, when trying to run a cube, it doesn't register any of the cards as existing, even on the presets. This issue happened maybe a year ago, but was fixed very quickly.

**Comment by braither90** [comment]
![dr4ft info](https://user-images.githubusercontent.com/56976279/67594076-dd694f00-f763-11e9-8843-08d6cdc90cc7.jpg)
i have this problem, i tested with some packs of standard, 3 ,4 ,5 packs and always same message

**Comment by tooomm** [comment]
Did some data at mtgjson change that we rely on maybe @ZeldaZach ?

**Comment by tooomm** [comment]
@braither90  @Fyresis 
Does the problem persist for you?

It seems to work for me. Tried with 3xM20 and 3xELD.

**Comment by Fyresis** [comment]
@tooomm
It's fixed as of like 2 days ago. Seems someone got to it.
Thanks :)

**Comment by tooomm** [comment]
Great! Thanks :) 

If you let us know next time that helps everybody seeing this issue report.
