### ISSUE TITLE
Automatic card updating not working

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#679]
Automatically pulling newest mtgjson data and refreshing the card database dr4ft uses while running does not work.

I think @HerveH44 implemented that?

**Comment by HerveH44** [comment]
Hi, 

Could you produce a JSON you want to integrate? If you tried on your own server, what output did it give?

I can have a look on my own server, but can't do much on the server "dr4ft.info" as I can't access it.

**Comment by tooomm** [comment]
Am I wrong? I was pretty sure the server updates its card database from mtgjson automatically from time to time and checks for newly available data?

Does this work on your server @HerveH44 ?

Only @ZeldaZach has access to dr4ft.info.
