### ISSUE TITLE
no `chaos sealed` game mode

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#68]
Would allow for epic fun events like this:
https://www.reddit.com/r/magicTCG/comments/5098lt/grand_prix_portland_36pack_chaos_sealed/

Or just any ordinary 6 pack chaos sealed...

---

Also, the `chaos` game mode we have right now should be named `chaos draft`

**Comment by HerveH44** [comment]
Hey @tooomm , can you check the site http:dr4ft.info:8080 and tell me what you think of the chaos sealed mode?

**Comment by tooomm** [comment]
@HerveH44 It seems to work as it should. You get x packs from random sets.
But the UI makes it not clear which sets are inserted on default and with the other two options, or a combination of them, enabled.
I would assume the default to have all cards, but what's total chaos then? (I assume to do the same)

I noticed the redesign of the game type selection and other related additions there. We can have a chat on gitter if you want feedback there. 👍 
(or post in the corresponding issues here)

**Comment by HerveH44** [comment]
well I'm not an expert of chaos, but the original code shows that "total chaos" is creating a booster from any card in the db. meaning, you take a booster of 1 rare, 3 unco and 10 commons, each filled with a random rare from a random set, 3 random uncos from random sets etc.

I'd love to have feedback about the implementation. I'm already starting to read and experiment using the framework [material-ui](https://material-ui.com/). Maybe soon i'll be able to show some examples.

**Comment by tooomm** [comment]
Hehe, interesting. Could be fun. 😄 

There should definitely be some hint next to the name, e.g. `Total Chaos (i)`.
On hovering the info symbol it could say:
>Every single card within each pack will be chosen on random, but still account for their rarities.
>A booster will contain 1 Rare/Mythic, 3 Uncommons and 10 Commons.
