### ISSUE TITLE
Reference: other draft sites/sealed generators

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#69]
This is just a list of similar services to keep track of them:
- http://draftsim.com/
- http://www.magicdrafting.com/
- http://mtgen.net/
- http://sealedmagic.se/
- http://tappedout.net/mtg-draft-simulator/ or http://tappedout.net/mtg-cube-drafts/
- http://draft.bestiaire.org/
  
Custom sets:
- http://www.planesculptors.net/

**Comment by HerveH44** [comment]
We could insert that it the README ?

**Comment by tooomm** [comment]
I just put it here to compare features, get inspiration on how they handle things or check what they offer in general.
I feel if its officially placed in the readme we have to maintain it actively.

**Comment by ZeldaZach** [comment]
No plans to cross reference officially. If you’d like to see what they do well, feel free to.
