### ISSUE TITLE
Cleanup + transition issues from old repos

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#70]
There is a lot of outdated and already fixed stuff hanging around at the former repositories.

I think if we clean them up and transition useful requests over to this one, everyone can benefit and we lower possible confusion for hosts and users.

I reopened (copied) already several of mine old requests and closed them in the old places.
Here are the ones we can still deal with...

Open Issues and PR's by @dev-id:
- [ ] [Issues at `aeosynth's repo`](https://github.com/aeosynth/draft/issues/created_by/dev-id)
- [ ] [Issues at `arxanas's repo`](https://github.com/arxanas/drafts.ninja/issues/created_by/dev-id)
- [ ] [Issues at `dev-id/dr4ft` (fork of arxanas's repo)](https://github.com/dev-id/dr4ft/issues) (also delete repo?)
- [ ] [Pull Requests at `aeosynth's repo`](https://github.com/aeosynth/draft/pulls/dev-id)
- [ ] [Pull Requests at `arxanas's repo`](https://github.com/arxanas/drafts.ninja/pulls/dev-id)

Open Issues by @tooomm:
- [ ] [Issues at `aeosynth's repo`](https://github.com/aeosynth/draft/issues/created_by/tooomm)
- [ ] [Issues at `arxanas's repo`](https://github.com/arxanas/drafts.ninja/issues/created_by/tooomm)

<br>

If the old maintainers put a note+link to this repo at one point, that would be very helpful as well.

**Comment by HerveH44** [comment]
Checking quickly the different repos, I didn't see any interesting issues that we coud take up. Maybe the idea of using "Tabs" could be interesting but it requires a bit of time and dedication. Maybe for another time...
