### ISSUE TITLE
Make sure foil overlay is loaded after card image

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#713]
Only a tiny nitpick.

**Comment by HerveH44** [comment]
What's the problem exactly? of course it's a bit weird when you see the overlay first, but we can't do much as the foil is already cached and the card image isn't.

**Comment by ZeldaZach** [comment]
Thinking about it further, I misread the ticket. The foil will appear over any spot no matter what. I thought it would be Card | Foil instead of Foil | Card, but that's not the case. Disregard.

**Comment by tooomm** [comment]
Note: with https://github.com/dr4fters/dr4ft/issues/614 we might have to rethink the foil overlay to maintain readability for a foil text only card.
