### ISSUE TITLE
Only calculate and show Trice/MWS code when downloading respective files

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#714]
Maybe it makes more sense to only generate and show the codes when .cod and .mwdeck files get downloaded. Not for .txt or .json files.

**Comment by HerveH44** [comment]
I wouldn't like that, you don't know how the players are gonna end up copying their file to cockatrice. I feel that it's best to keep generating the hash whenever they try to export the data. 

But I'm open to implement this too. I don't play anymore so ...

**Comment by ZeldaZach** [comment]
I'm on Herve's side here. Whenever someone downloads, I'm happy with it re-generating.

**Comment by tooomm** [comment]
Sure, fair enough. 👍
