### ISSUE TITLE
"Add picks to sideboard" option moves all cards around instead future picks only

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#719]
Maybe I understood this setting wrong?

I expected it to move cards that I pick during a draft to the sideboard when this is enabled, and once I disable it it moves new picks to the main deck.
That kinda works.

**But** it also *always* moves all cards from one zone to the other when the box is checked or unchecked. That is totally not expected and can mess around with picks or grouping of cards that you already did while drafting!

**Comment by ZeldaZach** [comment]
"Add picks to sideboard" means any future pick gets added there instead. This works as intended.

**Comment by HerveH44** [comment]
@ZeldaZach he's right. The picks all go to the side. I'll do a PR
