### ISSUE TITLE
Use other sources for draft stats

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#720]
Follow up issue on https://github.com/dr4fters/dr4ft/issues/302#issuecomment-471055972

>Sounds like we should change it to use the new draft stats, as well as data from draftSim

Currently, we use a very old and outdated database. @ZeldaZach mentioned that he has some sources.

**Comment by HerveH44** [comment]
@ZeldaZach what is our take on draft stats? What's the purpose of keeping stats? They are very valuable maybe that would be interesting to make an API to request the stats of dr4ft.info

**Comment by ZeldaZach** [comment]
I’m fine opening an API sup to get draft stats from us. I’d like to (at some point) use them to updating rolling medians for card picks and get our bots to take good cards over bad.

**Comment by HerveH44** [comment]
I think that's just not a reasonable goal for the project. I don't know much about artificial intelligence but if we want good bots (and I think that's what we should aim to) it takes a lot to produce a bot from just draft stats. 

I mean there should be a side project feeding from our stats (and maybe from all other draft simulators). Do you know if anybody is currently doing it?

**Comment by ZeldaZach** [comment]
I know of a few sites. I’ll see if any want to collaborate. By default our bots should pick cards on color with their first pick or two and just run it through it’s corse. Idk I gotta think

**Comment by ZeldaZach** [comment]
Tracking on #855
