### ISSUE TITLE
If commit is a tagged release, show release tag over hash and link to release

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#723]
Currently
`Running Version: 93b8e19 (build 2019-11-29) - Using MTGJSON card data v4.6.0 (2019-11-28)`
is dispalyed.
But 93b8e19 is a tagged release ([v0.2.5](https://github.com/dr4fters/dr4ft/releases/tag/v0.2.5)), and it's tag (+link to the release page) should be displayed over the inexpressive commit hash.

I thought we have that working and there has been some PR's about that? @HerveH44 

<br>

**Update:** mtgjson has the [requested striped down urls](https://github.com/dr4fters/dr4ft/issues/692#issuecomment-559023388) now for the changelog: https://github.com/mtgjson/mtgjson-website/pull/329

**Comment by HerveH44** [comment]
We talked with @ZeldaZach the problem was the config.server.js file not updated
