### ISSUE TITLE
Create set list file on-the-fly

### ISSUE THREAD

**Issue by dev-id** [dr4fters/dr4ft#74]
Currently the public/src/data.js file is manually curated. It should be generated automatically from data/sets.json

This will save one step when adding a set

Will need to bring in set type to set file

**Comment by HerveH44** [comment]
#96 has closed this one. Now src/data.js is kind of the DB wrapper. It exposes 5 methods: 

getCards: to get the "cards.json" file
getSets: idem for "sets.json"
getMws: idem for "mws.json"
writeCards: used to write cards.json file
writeSets: used to write sets.json file
