### ISSUE TITLE
Print game start with time to log

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#741]
Add useful timestamps to the log.
Print when the game started (e.g in grey like the time).

**Comment by HerveH44** [comment]
Is it really useful? I don't see the point of having the timestamp on when the game started...

**Comment by ZeldaZach** [comment]
Thinking about it, I do agree.

**Comment by tooomm** [comment]
> How is it useful? ... The game starting timestamp doesn't add any relevant information to the user.

I still think it does.
Otherwise you can never determinate when a draft started or how long it is already running.
Also critical conversations and discussions can not clearly be assigned to before or during draft.

I would even find it very useful to print when players leave the game room.
Or when a new pack is opened (not sure, if that happens for everybody at the same time or individually once one finished the former pack) etc.
