### ISSUE TITLE
Web notification improvements

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#744]
Follow up to https://github.com/dr4fters/dr4ft/issues/722 (web notifications got implemented in https://github.com/dr4fters/dr4ft/pull/733)
- [x] Use higher resolution "4" icon (#761)
- [x] Improve arrangement and wording of the two options in settings (#766)
- [ ] Further improve settings display, see description text in PR https://github.com/dr4fters/dr4ft/pull/766
<br>

- Maybe chat support is an option, balance pros and cons

**Comment by HerveH44** [comment]
@tooomm could you take care of this one? If I remember correctly you added the icon (or maybe the svg images of the mana).

Also maybe be more explicit in the issue, I don't know what you're expecting to change at the moment.

**Comment by tooomm** [comment]
Yes. I will take care of some parts. 👍
But will be a while probably until I find time.

**Comment by HerveH44** [comment]
>  But will be a while probably until I find time.
No problem, I guess the author of this issue will not accept that ;)
