### ISSUE TITLE
Improve text-only display of cards

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#752]
Known issues/limitations of the current first implementation (#742):

- [ ] Mana cost not being displayed completely for cards with a special layout (adventures, split, aftermath...)
Only one half is displayed as realized in ELD adventures.

- [x] Highlight card names in bold (#759)

- [ ] Highlight card names for alternative title in img tag in bold as well, see https://github.com/dr4fters/dr4ft/pull/759#issuecomment-565200634

- [ ] Increase visual separation between column header and its content.
Right now it's difficult because the card names are highlighted in bold. And column headers are bold, too. Use a gap maybe, or increase the size of the column caption a little?

- [ ] Offer option to disable card preview,
or allow the preview to be text-only as well for people who want/need to avoid pictures

- [ ] indicate card frame in text-only, too as guidance

- Also, see https://github.com/dr4fters/dr4ft/issues/769

- Discussion:
Only having the basic type of a card might not be enough in the long run.
As there are many important themes around types, like currently Knights. Artifacts, Legendary, or the Enchantment type of some creatures used to be important, too.
Dr4ft in text-only mode would be way less useful if you can't check those as well.

**Comment by HerveH44** [comment]
For the first bullet point, it needs first to be clear what should be done for all the special cards (aftermath, meld ...) for manacost. Do we want to show the double manacost always or only for specific layout?

**Comment by tooomm** [comment]
My first thought is always.
At least for special layouts on one card site. 
For which Layout wouldn’t it be useful there? For example split/aftermath/fuse, adventure, flip (kamigawa)... they all have more than one mana cost information on one card face. And they should all be shown. 

Special cards like any dfc only have mana costs on one side too I guess.
And if not, just the ones on the currently displayed side matter.

**Comment by HerveH44** [comment]
won't fix

**Comment by tooomm** [comment]
Still want to highlight two points from this issue which are lacking imo and are more important ones in case somebody wants to pick this up:
- Mana cost **(and text!)** not being displayed completely for cards with a special layout (adventures, split, aftermath...)
Only first half is shown as realized in e.g. ELD adventures or GRN split cards.

- Offer an option to disable the highlighted card preview for people who want/need to avoid pictures (e.g. bandwidth reasons or space issues on small screens)

**Comment by tooomm** [comment]
I keep adding to this to keep track of things:

There are scroll bars once there is too much text:
![scroll bars](https://user-images.githubusercontent.com/9874850/107579898-19911f00-6bf6-11eb-8f2f-903ccc9a0e9f.png)
(This is on Firefox, it looks different on Chrome with smaller text. Same issue though)

However, you can not use the scroll bars to read all text. Clicking them moves the card to other zones, and hovering + mouse wheel is not recognized.
