### ISSUE TITLE
Lower pack count for sealed needed

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#757]
As requested in https://github.com/dr4fters/dr4ft/issues/64 (and mostly addressed in #380), we have now the option to select how many packs we want to open in draft and sealed.

However, what is missing are options for 1 and 2 packs in sealed. 
Opening 1 pack is needed in Magic League for example.

For draft, I don't think we need fewer than 3 packs as option?
But I can't tell if there is some custom format which relies on that...

**Comment by ZeldaZach** [comment]
May as well give them the option
