### ISSUE TITLE
Flip card issue

### ISSUE THREAD

**Issue by Danielpick05** [dr4fters/dr4ft#767]
Flip cards no longer show their alternate side upon hovering over card, makes drafting Innistrad irritating.

**Comment by tooomm** [comment]
Can confirm, also for Eldritch Moon and Shadow over Innistrad with their double faced and meld cards.

More details:
Flip cards etc. do still show both sides in the preview window when hovering them in column view, but they don't display the back side any more when hovering them in normal view and they used to exchange the picture.

**Comment by tooomm** [comment]
Issue arised again: https://github.com/dr4fters/dr4ft/pull/775#issuecomment-613214295
