### ISSUE TITLE
Bad layout when card image can't be loaded and alt text is shown

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#768]
It breakes the layout if one card image can't be loaded:
![alt text](https://user-images.githubusercontent.com/9874850/70861229-3d41d200-1f2b-11ea-994a-10af22b7af81.png)

This can easily be reproduced as the image for the common card "Ulvenwald Captive" is currently not available at scryfall (but reported), and thus can't be loaded.

**Comment by HerveH44** [comment]
What is your OS and browser?

The card "Ulvenwald Captive" is back in scryfall I guess because I see it currently.

**Comment by tooomm** [comment]
Yeah, they fix reported mistakes very fast normally.

I use Firefox 70 on Windows 10.

**Comment by HerveH44** [comment]
won't fix

**Comment by HerveH44** [comment]
won't fix
