### ISSUE TITLE
Card info for the image alt attribute is badly styled

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#769]
- Card text starts in the same line as type and rarity
- Power and toughness is not separated with a dash
- Power and toughness starts in the same line as text

![alt text](https://user-images.githubusercontent.com/9874850/70861483-ea6a1980-1f2e-11ea-8610-510dbbbc8230.png)

And as mentioned in #752 already, the name should be bold there, too.

**Comment by HerveH44** [comment]
won't fix

**Comment by tooomm** [comment]
Probably difficult to change (if at all) and not worth it as it rarely ever happens.
