### ISSUE TITLE
Doubled cards in EMN pack

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#770]
Is that correct? Should that happen?
I think there was a slot for double faced cards, but could it hold a card that was already in the pack?

![doubled cards](https://user-images.githubusercontent.com/9874850/70861805-7e3de480-1f33-11ea-908c-77708b765390.png)

**Comment by HerveH44** [comment]
This is a EMN pack. I'd guess that's normal ... ?

**Comment by ZeldaZach** [comment]
One might be foil?

**Comment by tooomm** [comment]
>One might be foil?

As shown in the screen, both are normal cards. No foil effect applied.

DFC slot for meld in SOI: https://markrosewater.tumblr.com/post/146685423123/does-meld-cards-count-as-dfcs-can-we-get-one-of
i'm pretty sure there was such a slot for EMN too, but can a card appear in both, normal and DFC slot, at the same time?

**Comment by HerveH44** [comment]
@tooomm how often can you reproduce it ? I tried for couple minutes but couldn't find any duplications.

**Comment by tooomm** [comment]
I only ran into it once while testing the issue with back sides not loading and opening several boosters.
