### ISSUE TITLE
Error starting a draft

### ISSUE THREAD

**Issue by ArgothianEnchantress** [dr4fters/dr4ft#780]
I can't start a draft and get the message:

Whoops! An error occurred while starting the game. Please try again later. If the problem persists, you can open an issue on the Github repository: https://github.com/dr4fters/dr4ft/issues

**Comment by tooomm** [comment]
Which setting and especially which sets did you select for the packs?

**Comment by ZeldaZach** [comment]
Fixed

**Comment by ArgothianEnchantress** [comment]
It was indeed fixed. Thank you!

I was using Chrome on Windows 10, for a Chaos Draft.
