### ISSUE TITLE
Reset window position uniformly after manual pick in draft

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#799]
Manually picking a card in draft should constantly reset the window position to the top of the draftable cards with the headline "Pack x - Pick y/z". Currently the view jumps around after picks. It feels a bit random.
After manually picking and getting presented new cards most likely, it makes sense to center the view to the relevant area again to minimize scrolling.

On autopick, I suggest to not change the displayed content - one might be already building his pool and moving the view can result in unintended clicks to wrong areas.

**Comment by HerveH44** [comment]
There's actually no way to check if somebody has autopicked or not from the player point of view.

I'll make a PR to give a first impression of what would happen.
