### ISSUE TITLE
mtgjson version date, again

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#810]
Currently, our page shows:
`Using MTGJSON card data v4.6.1 (2020-01-12)`

While the [version.json](https://www.mtgjson.com/files/version.json) file from mtgjson has this data:
`{"date": "2019-12-01", "pricesDate": "2020-01-08", "version": "4.6.1+20200108"}`

The dr4ft page should use the "date" field from there and read:
`Using MTGJSON card data v4.6.1 (2019-12-01)`
Regarding to the explanation on the startpage on mtgjson that's the field we want as the other only updates for price data which we don't use.

**Comment by ZeldaZach** [comment]
Again, you're on an outdated cache. Please try hard refreshing as I see `{"date": "2020-01-12", "pricesDate": "2020-01-12", "version": "4.6.1+20200112"}`

**Comment by tooomm** [comment]
Even after hitting Ctrl+F5 several times (also before reporting the issue of course), I still get a different result than you. Updated, but different:
`{"date": "2019-12-01", "pricesDate": "2020-01-13", "version": "4.6.1+20200113"}`

My "date" field is still the old one which is even more weird as the dr4ft page shows the one you are seeing (2020-01-12). I also used a differnt browser to verfiy - both times I get "2019-12-01". Could it be that the most recent file update from 13th of janurary messed with the "date" field again?

**Comment by ZeldaZach** [comment]
I have to fix price things. I'll have time tonight or tomorrow.

**Comment by HerveH44** [comment]
is that about dr4ft or mtgjson?

**Comment by ZeldaZach** [comment]
This is a MTGJSON issue

**Comment by tooomm** [comment]
In case dr4ft uses the „date“ field correctly, that’s a mtgjson issue. Yes
