### ISSUE TITLE
Add unit test for supported json structure

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#811]
With #776 XML upload got added and there is a test case for it.

There should be a test case for json as well.

**Comment by HerveH44** [comment]
@tooomm thanks for your implication. If you feel like writing a PR to include the test, I'll be more than happy to review it!

**Comment by tooomm** [comment]
As mentioned in the PR (https://github.com/dr4fters/dr4ft/pull/798#issuecomment-584195049), this should not be addressed yet.

If I'm mistaken close this again, please.

**Comment by HerveH44** [comment]
won't do
