### ISSUE TITLE
Coldsnap lands

### ISSUE THREAD

**Issue by bomble** [dr4fters/dr4ft#828]
The Coldsnap packs don't include the snow basics from the set, making many cards unplayable. 
Is there a good fix to this?

**Comment by HerveH44** [comment]
Hi, 

We are currently working on a refactor of booster generation. So if you could tell us what you think about coldsnap booster making on this beta : 

[https://beta-dr4ft-pr-798.herokuapp.com](https://beta-dr4ft-pr-798.herokuapp.com)

That would be very helpful. 

At first glance on this beta, we do make snow covered lands for coldsnap but I'm not an export

**Comment by HerveH44** [comment]
@bomble hi, have you been able to test Coldsnap packs in the beta site? That would be interesting to get your feedback

**Comment by ZeldaZach** [comment]
I tested and it looks good!

**Comment by tooomm** [comment]
Not fixed on master yet
