### ISSUE TITLE
World series cards

### ISSUE THREAD

**Issue by bomble** [dr4fters/dr4ft#829]
The world series deck cards don't exist in the current program.
Only really an issue for cubes.

**Comment by HerveH44** [comment]
Hi we currently have cards that are available in MTGJson. Do you have any name of cards that we miss actually?

**Comment by Milldawg** [comment]
Here are all of Global Series cards that were not reprints:

https://scryfall.com/search?q=set%3Ags1+not%3Areprint&unique=cards&as=grid&order=set

And the list in text form:

Mu Yanling
Colorful Feiyi Sparrow
Purple-Crystal Crab
Vivid Flying Fish
Heavenly Qilin
Armored Whirl Turtle
Nine-Tail White Fox
Earth-Origin Yak
Moon-Eating Dog
Stormcloud Spirit
Ancestor Dragon
Qilin's Blessing
Drown in Shapelessness
Dragon's Presence
Rhythmic Water Vortex
Jiang Yanggu
Leopard-Spotted Jiao
Feiyi Snake
Sacred White Deer
Reckless Pangolin
Ferocious Zheng
Fire-Omen Crane
Screeching Phoenix
Earthshaking Si
Hardened-Scale Armor
Breath of Fire
Aggressive Instinct
Confidence from Strength
Journey for the Elixir
Cleansing Screech

Thanks!! My planeswalker cube isn't complete without Mu and Jiang :)

**Comment by HerveH44** [comment]
Hi, 

Could you try to use our cube list on this site : https://beta-dr4ft-pr-915.herokuapp.com/

**Comment by Milldawg** [comment]
Thanks for fixing this! Just tested Mu Yanling and Jiang Yanggu and they appeared correctly :)
