### ISSUE TITLE
Change column header labels

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#839]
![bold headings](https://user-images.githubusercontent.com/9874850/72907132-ab9c6000-3d33-11ea-8da3-91846c3e8b2f.png)

Since we have bold headings there is a problem for the long type name in combination with two digits nubmers. That needs some tiny adjustment.

Probably there would be the same issue for planeswalkers.

**Comment by ZeldaZach** [comment]
Would rather change the headers to just be `Creatures (23)`, `Enchantments (10)`, etc

**Comment by tooomm** [comment]
I like that!

It would work for the other filter types as well:
Color: `Colorless (11)`, `White (5)`, `Multicolor (8)` ...
Type: `Artifacts (2)`, `Creatures (15)`, `Enchantments (3)`...
Rarity: `Rare (3)`, `Uncommon (10)`, `Common (40)`...

Just for CMC it's not ideal:
CMC: `1 (13)`, `4 (5)`, `6+ (2)`...

But maybe something like:
CMC: `One (13)`, `Four (5)`, `Six and more (2)`...
CMC: `CMC: 1 (13)`, `CMC: 4 (5)`, `CMC: 6+ (2)`...

**Comment by HerveH44** [comment]
@ZeldaZach what is the definite headers that should be implemented?
