### ISSUE TITLE
Site crashed

### ISSUE THREAD

**Issue by vprelovac** [dr4fters/dr4ft#851]
Since this morning when starting a game the site dr4ft.info gives this message

Whoops! An error occurred while starting the game. Please try again later. If the problem persists, you can open an issue on the Github repository: https://github.com/dr4fters/dr4ft/issues

**Comment by tooomm** [comment]
@vprelovac I had a similar problem. Mine got solved with the recent rebuild form yesterday.

Please try and let us know if it works again for you!

**Comment by ZeldaZach** [comment]
This keeps happening and I'm not sure why. I rebuild the site, deploy, and it works as expected. Then a few hours later it dies. @HerveH44 

Taking a look into the system, it appears the `cards.json` file only contains custom cards right now. This means it was overwritten at some point when someone uploaded something. This seems like a bug. Will re-deploy now.

**Comment by squigel** [comment]
Same problem has come up again, only mario cards working.

**Comment by HerveH44** [comment]
Hi, 

I've been very busy lately. I'm sorry I can't help right now. I guess this must be done on how we use integrate the custom cards. I fear that if the custom cards names equal the real ones we just overwrite them!

**Comment by HerveH44** [comment]
Should we close this issue? reopen it if the problems rearises
