### ISSUE TITLE
Hide download deck option until game/draft is finished

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#854]
`Download` and `Copy deck to clipboard` options should only be available at the end of the draft.

For example:
- Grey button out until all picks are made, but allow name and file type changes before
- Grey all options in the download widget out until all picks are made
- Hide that widget completely until all picks are made

v2.0:
It could also be connected to the deck size option and only offers a download if the amount of cards in the main deck matches this number to avoid problems with unfinished/incomplete decks being downloaded (new players think they can/have to add lands in Cockatrice later).
E.g. Hide the widget until the draft is over, buttons are still grayed out until card count in main deck matches the selected deck size (aka lands are added).

**Comment by HerveH44** [comment]
I'm not up for it. I don't know what is the problem here, people can download their deck whenever they want, why should they wait for the game to be finished?

**Comment by HerveH44** [comment]
won't fix

**Comment by ZeldaZach** [comment]
Agreed. Not necessary.
