### ISSUE TITLE
Chaos Draft Issue

### ISSUE THREAD

**Issue by GrandiaKnight** [dr4fters/dr4ft#856]
I tried to do a chaos draft but every pack is exactly the same. I also tried to do a total chaos draft with the same result

**Comment by HerveH44** [comment]
Hi, 

Could you indicate the game settings (chaos settings (modernOnly, total chaos), number of players, how many bots were playing) ?

Thank you in advance,

**Comment by GrandiaKnight** [comment]
I tried it 8 players,draft, 3 packs, modern only, modern only, 1 player and the rest bots.

I also tried the same above but with total chaos as well with the same result

**Comment by HerveH44** [comment]
Thank you for the feedback, 

@ZeldaZach could you tell us what is going on on the website "https://dr4ft.info" ? It seems that it would need a restart :) !

**Comment by HerveH44** [comment]
This issue is not valid anymore. Chaos draft is back on track :)
