### ISSUE TITLE
Earthshaker Giant not in Card Database

### ISSUE THREAD

**Issue by mwheeler93** [dr4fters/dr4ft#860]
Hey Dr4ft,

I've been trying to include Earthshaker Giant in my cube for months now and it still doesn't seem to be in the card database. Seems like a quick fix, potentially. Just wanted to let you know in case it isn't on your radar!

Cheers

**Comment by tooomm** [comment]
[This card from GN2?](https://scryfall.com/card/gn2/5/earthshaker-giant)
It's part of the mtgjson file at least as Cockatrice can display it.

**Comment by ZeldaZach** [comment]
I think dr4ft excludes non-draftable sets... Overall maybe not the best approach.

**Comment by tooomm** [comment]
Hiding them from the set picker for draft (and sealed?) should be enough.
Or list them in their own category/group at the very end of the list maybe?

**Comment by mwheeler93** [comment]
> Hiding them from the set picker for draft (and sealed?) should be enough.
> Or list them in their own category/group at the very end of the list maybe?

Hey, not totally sure how to do either of the things you mentioned. Help?

**Comment by tooomm** [comment]
Unfortunately, nothing you can do about that currently.

That's something we have to do as it affects our internal database as I understood it.
We are aware of the issue, thanks for opening the issue @mwheeler93!
We keep you posted here.

**Comment by mwheeler93** [comment]
Thanks so much!

**Comment by HerveH44** [comment]
@ZeldaZach this is linked to the type of the set not being included to our accepted types. GN2 has type "box". What does that mean ? I can include this type to the accepted ones. 

Also we could work with a blacklist instead of a whitelist of types if you think you may add a lot of different set types in the near future.

**Comment by ZeldaZach** [comment]
We should include _all_ magic cards within the system, but only allow active drafting of the sets we have so far
