### ISSUE TITLE
All cards in cube invalid

### ISSUE THREAD

**Issue by ebbit1q** [dr4fters/dr4ft#862]
When I enter a cube I get the message that all the cards are invalid:
![image](https://user-images.githubusercontent.com/36401181/75093273-77110380-5580-11ea-9fe0-98788cb42e33.png)
I'm fairly certain storm crow is a legal and draftable magic card. It happens for the prebuilt cubes too.

**Comment by ZeldaZach** [comment]
For some reason cards keep getting invalidated. I'm not sure why this keeps happening, but a rebuild fixes it temporariy

**Comment by tooomm** [comment]
We should keep one issue about that open
