### ISSUE TITLE
Error: FlatMap is not a function

### ISSUE THREAD

**Issue by mint-jar** [dr4fters/dr4ft#864]
Hello,

Last few weeks my friends and I started encountering that the dr4ft.info is not working as expected. We can't start drafts, sealed or cubes.

I installed the application locally to see if I could reproduce it.

Starting from Docker according to install gives no trouble.

Starting from NPM with the readme gave me the same issues as I am encountering online.
Logs show the following:

```
2020-02-24 20:39:46,269+0100 [ERROR] Game ras4cujsni  encountered an error while starting: TypeError: replaceRNGSet(...).flatMap is not a function
```
Maybe some issue with the last npm updates?
My current node version is `v10.16.31`
I'll look into how to fix it. but for now I wanted to report the issue.

Update:
Looks like flatmap is not supported locally. When I add a hack to add it everything works again:
in  pool.js I added:
```
const concat = (x,y) =>
  x.concat(y)

const flatMap = (f,xs) =>
  xs.map(f).reduce(concat, [])

Array.prototype.flatMap = function(f) {
  return flatMap(f,this)
}
```

**Comment by ZeldaZach** [comment]
I haven't seen this issue before... I use v12.8.0 to run the server. Can you try using that one?

**Comment by mint-jar** [comment]
12.8.0 doesn't have the issue unfortunately.

Dang it. Was hoping this could fix it :sweat_smile: 

I'll keep looking if I can find issues elsewhere.
