### ISSUE TITLE
Cube isn't available for custom sets

### ISSUE THREAD

**Issue by user6174** [dr4fters/dr4ft#865]
Hi everyone, first and foremost I apologize if the custom sets I added are causing unwanted clutter and/or if they aren't properly named to reference the game they're part of, I wasn't aware that uploading them would've made them permanently available without me being able to delete them. Onto the issue, as the title says, card names in a cube list are only checked with MTG card databases, and thus I'm unable to issue a cube draft with cards from the custom sets I've uploaded. 
Would it be possible to expand the card databases to accommodate custom sets, or better yet, to be able to optionally specify from which set(s) the cards from a cube are being taken from, in order to avoid possible homonyms?

**Comment by HerveH44** [comment]
@user6174 could you try again on https://beta-dr4ft.herokuapp.com/ ? It should work now

**Comment by HerveH44** [comment]
@user6174 dr4ft should be able to show you the image from the "url" field. I don't know what kind of set you use, let me know how is your set.

**Comment by user6174** [comment]
@HerveH44 I'm using the 'picurl' attribute, as per https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets
Although similar, I'm not sure you're talking about that.
I'll link [my xml](https://raw.githubusercontent.com/user6174/Shadowverse-to-Cockatrice/master/sv_cards.xml) to double check

**Comment by HerveH44** [comment]
I'll make a PR for you @user6174
