### ISSUE TITLE
Cube Cobra integration

### ISSUE THREAD

**Issue by KouriR** [dr4fters/dr4ft#875]
Cube draft feature request:
Add the ability to input a Cube ID to import from https://cubecobra.com/.

**Comment by ZeldaZach** [comment]
I like the idea. Would be useful and help @dekkerglen out. You interested in this feature, G?

**Comment by dekkerglen** [comment]
Lol I requested this feature from you months ago 😂

**Comment by dekkerglen** [comment]
Sure, I'll take this as my first issue, why not

**Comment by HerveH44** [comment]
@dekkerglen need a hand? I can give you hints/help if you want. Just let me know

**Comment by dekkerglen** [comment]
I may not get around to this - don't let me being assigned to this stop anyone else from building it

**Comment by HerveH44** [comment]
Can you let us know what would be the API of Cube Cobra?

**Comment by dekkerglen** [comment]
The route is:
`cubecobra.com/cubes/api/cubelist/:id'`
Where id is the id of cube, which can be manually set but defaults to a ~3-4 character value. You can see the ID in any cube url 

It will return a plaintext list of card names

**Comment by HerveH44** [comment]
Could you please add the possibility to fetch data from another website? Right now I receive an error because CORS header is missing (It's an error from frontend - Mozilla and Chrome do not allow download if CORS header is missing, it's a security policy): 

"Reason: CORS header 'Access-Control-Allow-Origin' missing"
-> https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

I think you need to add this header "Access-Control-Allow-Origin" to the response to your API if you want any website to consume it.

**Comment by HerveH44** [comment]
Also, if I put a bad ID, it seems that your API does not return anything. I receive a timeout ...

**Comment by KouriR** [comment]
Side issue is cards with split names.
For example, Cube Cobra returns "Brazen Borrower", but dr4ft doesn't recognize this. It only accepts "Brazen Borrower // Petty Theft".

**Comment by dekkerglen** [comment]
This is only the case for adventure cards - and this can be worked around by finding the card name that starts with the text, not equals

**Comment by HerveH44** [comment]
@KouriR I already took care of this issue in the future PR. 

@dekkerglen have you thought of the 2 main problems I'm facing right now for the integration?

**Comment by ZeldaZach** [comment]
Poke @dekkerglen

**Comment by dekkerglen** [comment]
Created a PR: https://github.com/dekkerglen/CubeCobra/pull/1256

**Comment by HerveH44** [comment]
@dekkerglen let us know when this is deployed in production. As for now, I still get the same answer from your backend (no CORS allowed)

**Comment by dekkerglen** [comment]
It will be live on the 18th

**Comment by HerveH44** [comment]
of April?

**Comment by dekkerglen** [comment]
...yes

**Comment by tooomm** [comment]
Did you deploy your new code @dekkerglen?

**Comment by dekkerglen** [comment]
Yes

**Comment by tooomm** [comment]
@KouriR & @dekkerglen can you test Herve's CubeCobra integration, please?
--> https://beta-dr4ft-cubecobra-sqj1znapl.herokuapp.com/

**Comment by dekkerglen** [comment]
Works for me!

**Comment by KouriR** [comment]
Works for me as well.
Only issue I found is if you enter an invalid cube id it will display "Could not retrieve CubeCobra list with id xxx" but then if you enter a valid id, the list imports fine but the error message doesn't go away.

**Comment by HerveH44** [comment]
Fixed that.

**Comment by KouriR** [comment]
CubeId field should have a max length of 100 characters.

**Comment by HerveH44** [comment]
That's a good question: @dekkerglen what is the max for a cube id ?

**Comment by dekkerglen** [comment]
100 character is our max.
