### ISSUE TITLE
We can't fire a draft because the lobby doesn't show all of the drafters at once

### ISSUE THREAD

**Issue by Ragaxus** [dr4fters/dr4ft#884]
We can use chat, but the lobby isn't holding players correctly.

![image](https://user-images.githubusercontent.com/10427478/77000055-b33c4780-6925-11ea-9499-fb3464b472c4.png)

**Comment by ZeldaZach** [comment]
I don't seem to have this issue on Firefox or Safari... This is weird. You said you're on mobile?

**Comment by Ragaxus** [comment]
Some of us were, but we were able to reproduce the issue when everyone was
using desktop machines.

**Comment by grosbegue** [comment]
I can confirm the problem. We were unable to launch a draft, it seems only 2 drafters could join the room at the same time. Furthermore it seems that public rooms don't appear in the room list.

**Comment by Ragaxus** [comment]
Cause is intermittent; we were able to fire a draft last night.
