### ISSUE TITLE
Upload Custom Set (JSON): Cannot Read property 'type' of undefined

### ISSUE THREAD

**Issue by aSipiere** [dr4fters/dr4ft#892]
I've created a paired down file from the MB1 and CMB1 files on mtgjson, by adding the cards together and removing a few of the more wordy keys from each card, this gets it down to 1.7MB which is small enough for uploading a custom set.

But I'm getting a `"the json submitted is not valid: Cannot read property 'type' of undefined"`.

This was the python script I used to generate it if you wanna have a go.

```python
import json

with open("./MB1CMB1.json", encoding="utf8") as file:
    mb1cmb1 = json.load(file)
    
bad_keys = [
    'edhrecRank',
    'foreignData',
    'legalities',
    'prices',
    'purchaseUrls',
    'tcgplayerProductId',
    'rulings'
]

for card in mb1cmb1['cards']:
    for k in bad_keys:
        card.pop(k, None)
        
with open('mb1cb1-small.json', 'w') as outfile:
    json.dump(mb1cmb1, outfile)
```

I created the file by splicing together the cards list from MB1 and CMB1 and changing the the total set size. I have a feeling that dr4ft is dependant on one of the fields I've killed. But it would be nice not to have to fix it through trial and error.

_Originally posted by @aSipiere in https://github.com/dr4fters/dr4ft/issues/891#issuecomment-602040762_

**Comment by aSipiere** [comment]
I actually did a bit of further digging with some other mtgjson files, and all of them seem to cause the same error. So far its reproducible with all of the mtgjson sets I've tried (if you change the set code and upload them as a custom set).

**Comment by HerveH44** [comment]
Hi, 

Could you share the file you are trying to update?

Hervé

**Comment by aSipiere** [comment]
Sure

- mb1-small.json is the core mystery booster set with those fields removed
- mb1cmb1-small.json is the full mystery booster convention edition
- CN2_test.json is conspiracy 2 take the crown but with its set code changed to TST (results in the same invalid json error).
[mtgjson.zip](https://github.com/dr4fters/dr4ft/files/4392913/mtgjson.zip)

**Comment by HerveH44** [comment]
It seems that your json are missing the field "code" at the root level.

**Comment by HerveH44** [comment]
Hi,

In fact the error is a bit tricky. You JSON miss the "code" field at root level. Then the "type" error is not directly linked on it.

**Comment by aSipiere** [comment]
Ah, I was about to say that i just noticed the conspiracy 2 upload works okay after refresh even after displaying the error.

But after adding a code to the top level json the `mb1cmb1-small.json`, I still get the error and cannot see the set in Custom after refresh.

**Comment by HerveH44** [comment]
Yeah because now the DB is corrupted with a bad json file :( !

@ZeldaZach could you please tell me what is inside the data/custom folder? Do you any "undefined.json" file?

**Comment by aSipiere** [comment]
Ah, sorry about that. There's probably a good few of them, I've been tinkering with this for a few days, are the files not validated before entering the DB?

**Comment by HerveH44** [comment]
Don't be sorry, it's my mistake, I should have added this control!

**Comment by ZeldaZach** [comment]
Rebuilding without custom sets. HMU on Discord later.

**Comment by HerveH44** [comment]
Hi @aSipiere could you please try to upload your set to the PR : https://beta-dr4ft-pr-907.herokuapp.com ? 

Thanks in advance,

**Comment by aSipiere** [comment]
@HerveH44 Uploaded fine, but Custom doesn't appear on drop down after loading or refreshing.
![image](https://user-images.githubusercontent.com/32668629/77971729-5ce8e480-72e7-11ea-9a65-9ec73fe4af23.png)

**Comment by HerveH44** [comment]
In fact, you don't see it because the property "baseSetSize" is at 0, which means that this is not a playable set

**Comment by aSipiere** [comment]
Hmm.. okay. That appears to be a problem with the mtgjson source. How is the baseSetSize different to the totalSetSize and what is baseSetSize used for?
