### ISSUE TITLE
Time Limit during draft

### ISSUE THREAD

**Issue by Nilsinho187** [dr4fters/dr4ft#897]
Let me start by saying thank you for this great platform. We had a Cube Draft last Saturday and used dr4ft.info for the actual draft part. Disregarding some minor issues it went swimmingly. 

There was just one thing that made it difficult for the more inexperienced players: the time limit. Even the option "leisurely" with 90 seconds for the first pick can be pretty fast when you are unfamilar with the majority of cards. Plus in Cube Draft most of the cards can be quite complex, making it necessary to read them carefully.

So an additional timer option even slower than leisurely would really improve the drafting experience for our group. Maybe even the option to use no timer at all.

Thank you

**Comment by Flutschi** [comment]
You can just disable the timer when you unclick the checkbox..

**Comment by ZeldaZach** [comment]
Gonna close as a no-fix as the timers are optional :)
