### ISSUE TITLE
Allow to select the language of displayed cards

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#900]
Support for different languages.
User should be able to set the language of the cards displayed to him.
If I recall correctly we pull card images from scryfall. They support card art for several languages.

Selection should be made via dropdown menu - next to the image quality.
Available languages: https://scryfall.com/docs/api/languages

Fallback to english if selected language is not available.

**Comment by HerveH44** [comment]
Could be a useful resource the API of scryfall : 
https://scryfall.com/docs/api/cards/collector

for example: 

https://api.scryfall.com/cards/xln/96/fr?format=image&version=large
