### ISSUE TITLE
Issue with Cockatrice v3 export

### ISSUE THREAD

**Issue by Le0Bandito** [dr4fters/dr4ft#904]
I'm trying to draft a custom set I designed, but when I try to load up the Cockatrice v3 export file, it gives me this error:

> "the xml submitted is not valid: node sets and cards must be present"

When I look at the file, it has the /cards node, and has no sets node.
I haven't done anything to the file, just straight out of Artifice exporting Cockatrice v3.

Any help would be greatly appreciated!

**Comment by HerveH44** [comment]
Hi, 

Thank you for letting us know. Could you share a copy of the file you would like to update? 

Hervé

**Comment by Le0Bandito** [comment]
This is the file exactly as it was exported.

[01.customcards.xml.zip](https://github.com/dr4fters/dr4ft/files/4395023/01.customcards.xml.zip)

**Comment by HerveH44** [comment]
Hi, 

We are missing the case when the sets node is not present. Looking at the cocktrice v3 specs (https://github.com/Cockatrice/Cockatrice/blob/master/doc/carddatabase_v3/cards.xsd) it's possible for a XML to miss the sets portion. We will need to update our XML parser to handle this too.

**Comment by HerveH44** [comment]
Hi @Le0Bandito  could you please try to upload your set to the PR : https://beta-dr4ft-pr-907.herokuapp.com ? 

Thanks in advance,

**Comment by Le0Bandito** [comment]
It works now! Well done!

**Comment by Le0Bandito** [comment]
Looks like on the main dr4ft.info even after the coding was merged it's giving me the same error again.

**Comment by ZeldaZach** [comment]
New deployment goes live 00:00 EST

**Comment by Le0Bandito** [comment]
Ah, thank you, I didn't realize that!
