### ISSUE TITLE
Not Reading Custom Mythics

### ISSUE THREAD

**Issue by Le0Bandito** [dr4fters/dr4ft#910]
While now I can draft my custom set, it doesn't seem that mythic rares are showing up.
I wasn't certain at first, but after generating 32+ packs without a single mythic, I think it may not be reading that rarity in Cockatrice v3 files.

**Comment by HerveH44** [comment]
Hi, 

You're perfectly right. We expect a rarity to be one of : 
basic, common, uncommon, rare, or mythic
from the mtgjson site : 
https://mtgjson.com/structures/card/#rarity

I don't know if there is any information on cockatrice about another list of rarities. But if it's possible for you to change that on your side it would be perfect. 
If not, we'll try to patch the importer to check and change the rarity.

**Comment by Le0Bandito** [comment]
Took a look this morning and saw that Cockatrice v3 exports with the rarity as "Mythic Rare", whereas mtgjason wants just "Mythic".
Now I know to change that before I load it up!

**Comment by tooomm** [comment]
Wondering that mtgjson uses „mythic“. Isn’t „Mythic Rare“ the official wording? @ZeldaZach 

To avoid problems, draft should understand both and treat them the same l guess.

**Comment by ZeldaZach** [comment]
Rarity is only "mythic" on MTGJSON4/5
