### ISSUE TITLE
Time Spiral missing some artifacts

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#913]
Someone reported, and I verified, that Time Spiral sealed wasn't showing most of the common artifacts. I ran several 12-pack sealeds, and notice that very few, if any, artifacts were found. This could be an overarching issue of cards are missing from dr4ft inadvertently.

**Comment by HerveH44** [comment]
@taw do you have any idea on this issue?

**Comment by taw** [comment]
Which artifacts are missing or underrepresented?

[If I open a Sealed box on mtg.wtf](https://mtg.wtf/sealed?count%5B%5D=36&set%5B%5D=tsp&count%5B%5D=0&set%5B%5D=thb&count%5B%5D=0&set%5B%5D=thb), then click Preview as Deck, the numbers of artifacts seem to be about right (Artifact Creatures are in Creatures section).

**Comment by ZeldaZach** [comment]
User reported never seeing Prismatic Lens, Chromatic Star, and Terramorphic Expanse. I couldn’t find them either while I simulated sealed events or drafts.
