### ISSUE TITLE
Short feedback to new dr4ft.info (with new refactored code)

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#92]
- Game config screen misses some linebreaks:
![draft-game_infos](https://user-images.githubusercontent.com/9874850/36487446-2f985714-1721-11e8-8c09-bb7c53c8a66b.png)

- Same with in-game info (left):
![draft-in_game](https://user-images.githubusercontent.com/9874850/36487456-354a9b36-1721-11e8-8abf-44bd0696426b.png)
`main` is misaligned (middle)
and the sort options could see an additional paragraph (right)

- `Storm the Vault` just shows its back pic (I hover one of the relics, see the little color difference for highlighting)
![draft-dfc_pic_wrong](https://user-images.githubusercontent.com/9874850/36487452-318c62ae-1721-11e8-8b51-f1d6c931166c.png)
The shown pool is from a sealed 6-pack game by the way.

- If you go to the dr4ft page and have js disabled or blocked one should see a hint and little explanation what's up and why it's essential for its functionality.
Right now there is nothing but a empty page:
![draft-no_js_hint](https://user-images.githubusercontent.com/9874850/36487454-33535ab6-1721-11e8-80e3-9b3b9f8b7044.png)

<br>

All on Firefox 58 and Windows 10

**Comment by HerveH44** [comment]
Hey @tooomm,

Thanks for your feedback. My bad, I only test using Chrome. I'll check that ASAP.

Herve
