### ISSUE TITLE
Compile/Run issues after latest git pull

### ISSUE THREAD

**Issue by trsbox** [dr4fters/dr4ft#920]
Any ideas?
![Screenshot at 2020-04-03 12-33-48](https://user-images.githubusercontent.com/17534007/78415497-6328da80-75df-11ea-884c-b10f0bb48f0b.png)
![Screenshot at 2020-04-03 12-34-48](https://user-images.githubusercontent.com/17534007/78415498-645a0780-75df-11ea-81d1-1d11de0521b3.png)
![Screenshot at 2020-04-03 12-35-03](https://user-images.githubusercontent.com/17534007/78415499-658b3480-75df-11ea-808e-fe4331946518.png)

**Comment by HerveH44** [comment]
Hi @trsbox , long time no see. I didn't know you still run dr4ft. When was the last pull you did? The v1.0.0 is a big change you might need to rerun "npm install" to update some dependencies. 

The screen captures also indicate that you miss the boosterRules.json that contains the rules to create boosters. 

To create it (it should be created when updating the MTGJson sets, but if you had the latest version before doing "git pull" you might not have triggered its creation), you should launch "node scripts/download_booster_rules.js" when you are in the dr4ft directory.

**Comment by trsbox** [comment]
Thanks for the info!  I will try out.  Yup still run it at trsbox.net:1337

**Comment by trsbox** [comment]
Running the script did not solve it.  I did a git pull today and tried everything again as per the REAME.md file.  Same result.

**Comment by HerveH44** [comment]
could you remove all the "data" directory and redo a "npm install" ? And then indicate the error you encountr?

**Comment by trsbox** [comment]
> could you remove all the "data" directory and redo a "npm install" ? And then indicate the error you encountr?

![Screenshot_20200412-010230](https://user-images.githubusercontent.com/17534007/79062708-c9ee6980-7c59-11ea-8973-1133ea54af08.png)
![Screenshot_20200412-010355](https://user-images.githubusercontent.com/17534007/79062709-cf4bb400-7c59-11ea-8214-64a32e5ba36d.png)
![Screenshot_20200412-010502](https://user-images.githubusercontent.com/17534007/79062711-d70b5880-7c59-11ea-8d0b-dd3bf133144f.png)

**Comment by ZeldaZach** [comment]
Can you show us what git pull says?

**Comment by HerveH44** [comment]
@trsbox can you redo "git pull" and "npm install" and indicate us what is the result?

**Comment by trsbox** [comment]
Sorry for the delay guys...
![Screenshot at 2020-04-17 18-41-24](https://user-images.githubusercontent.com/17534007/79623720-0fd48300-80db-11ea-9f32-067a11eb3dba.png)


![Screenshot at 2020-04-17 18-38-59](https://user-images.githubusercontent.com/17534007/79623685-e7e51f80-80da-11ea-9b9f-9a639e2b1671.png)

**Comment by HerveH44** [comment]
Hi @trsbox, I'm sorry but this does not help much. Could you please do the following:

1. "git pull"
2. remove everything in "./data"
3. "npm install"

And then tell us the output of "npm run start"

**Comment by trsbox** [comment]
![Screenshot at 2020-04-22 10-31-59](https://user-images.githubusercontent.com/17534007/80008288-c9897600-8484-11ea-98a7-f5af36a031ff.png)

I did not have a data directory after doing the git pull above.

![Screenshot at 2020-04-22 10-35-04](https://user-images.githubusercontent.com/17534007/80008639-3e5cb000-8485-11ea-9d4d-36b809128896.png)

Above is npm install

![Screenshot at 2020-04-22 10-35-59](https://user-images.githubusercontent.com/17534007/80008651-4288cd80-8485-11ea-9234-2fae80a14378.png)

Above is npm run start

![Screenshot at 2020-04-22 10-37-57](https://user-images.githubusercontent.com/17534007/80008777-6e0bb800-8485-11ea-83c5-f0f53462c3b1.png)

Above is after creating a data directory

**Comment by ZeldaZach** [comment]
Can you try backing up & deleting your config file?

**Comment by HerveH44** [comment]
Hi @trsbox thank you for the output files. It seems that npm can't create the data directory by itself. I don't know why, I guess it must be permissions issues. If you can provide us this the following informations we could help: 
1. "ls -lA" on the root directory (~/dr4ft)
2. what is your OS (it seems Linux Mint), setup (is it on a Virtual Machine, or in a container/docker, etc.)

I don't know if that would be possible for you to allow me to connect in SSH to your computer so I could investigate further. Just let me know, I could give you my public SSH key and let me know how to connect to it (via private messages or mail).

You could also create the directories by yourself (I guess this command "mkdir -vp ./data/{custom,draftStats,log,sets}" should create all the needed directories)

After that run "npm run postinstall", that will download and install the MTGJson cards and the boosterRules.

**Comment by trsbox** [comment]
Thank you for the info.  I will try above in the next few days.  Its debain virtual machine.

If i can not get it to work ill give u access.  Thanks again.

**Comment by trsbox** [comment]
@HerveH44  Your instructions appear to have worked.  Thank you.

**Comment by ZeldaZach** [comment]
Awesome!
