### ISSUE TITLE
Better Sanitization of Uploads

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#925]
People have been uploading rogue files to the service. We need to validate they're proper JSON/XML, see if they work, and allow for a quick rollback. Attached is the file that crashed dr4ft.

[trev.json.txt](https://github.com/dr4fters/dr4ft/files/4433007/trev.json.txt)

**Comment by ZeldaZach** [comment]
Related #924

**Comment by HerveH44** [comment]
Hi, 

Can you be more specific about the crash of dr4ft? What was crashing? Could you please show me the logs of the app?

**Comment by ZeldaZach** [comment]
The homepage was blank, and the console showed the error found in ticket #924 There don't seem to be any logs attached
