### ISSUE TITLE
Tempest Boosters

### ISSUE THREAD

**Issue by 7stringplayer** [dr4fters/dr4ft#932]
Hello.  Drafted Tempest last night with some friends.  There is packs that contained more than 1 land.  one even contained 4.  I dont think this is correct.

**Comment by 7stringplayer** [comment]
I also noticed this happened with Alpha as well

**Comment by 7stringplayer** [comment]
Ok so i notice it is happening with a lot of boosters.  Might be something you want to look into too

**Comment by HerveH44** [comment]
Hi thank you for your feedback. 

Hey @taw, there's something I must have missed, could you tell me how to get only one basic from your sheets? For example, one sheet is "tmp_common_or_basic: 11, tmp_uncommon: 3, tmp_rare: 1" but I guess it can lead to multiple lands

**Comment by 7stringplayer** [comment]
could you do a code thats 1 basic 10 common 3 uncommon 1 rare.  Thats how it use to be.  I dont remember this being a problem before

**Comment by HerveH44** [comment]
We've updated the way we create boosters to be as close as possible to real ones. Rules around how to make a real booster are multiple and difficult.

**Comment by 7stringplayer** [comment]
you could get rid of the lands and make 14 card packs without lands.  I think thats better than having 4 to 5 lands in a pack.

**Comment by HerveH44** [comment]
Well that's true. If you want you can make a PR and we'll be happy to merge it !

**Comment by 7stringplayer** [comment]
I dont know what that is.  I dont right code or anything i was just letting you know this was happening and wasnt correct.

**Comment by 7stringplayer** [comment]
My Suggestion would be do 

a. 14 cards instead of 15 with no land 
b. 15 cards and 12 commons no land
c.  Make a land slot for land and 11 commons (which you said is hard)

Those are more realistic than havings lots of lands in packs especially when drafting it sucks.

**Comment by ZeldaZach** [comment]
This is a @taw issue and will not be addressed by the dr4ft team at the current time. Just gotta wait for his response.

**Comment by nomoid** [comment]
The issue of basic lands appearing in boosters affected my recent draft of Invasion too. From what I can find in my research, many older sets do not have basics in boosters. I'm going to submit a pull request to [taw/magic-sealed-data](https://github.com/taw/magic-sealed-data) to change data of the older sets from `"[set]_common_or_basic"` to `"[set]_common"`.

**Comment by taw** [comment]
So you're saying some of the old sets didn't have basics in their boosters, but I'm including them in commons sheet?

This is definitely possible, as it changed multiple times, and those early sets are poorly documented. I was meaning to double check, but never got to it.

Just give me the list of sets you think are incorrect, or some source, so we can get it done once and for all.

**Comment by 7stringplayer** [comment]
You use to have to buy a Starter pack to get lands for older sets they didnt come with lands in booster packs.  Any set though you draft can have multiple lands in it which is really the problem i just opened an M2019 and got 3 plains in it as commons instead of real cards

**Comment by taw** [comment]
You got 7 basics out of a single M19 booster? That sounds like there's some whole second problem. 

JSON for M19 is definitely correct in having basics on its own sheet (plus small chance of basic on foil sheet).

**Comment by 7stringplayer** [comment]
Yea heres an example.  I picked  1 pack of 6 different sets for a sealed game.  I ended up with 9 lands for Mercadian Masques.  

![image](https://user-images.githubusercontent.com/21352581/78681568-8b039100-78b2-11ea-83b0-a8d4b50bd139.png)

**Comment by taw** [comment]
Right, I can 100% see MM having issues. I guess I'll have to check all old sets.

**Comment by 7stringplayer** [comment]
I almost think it would be better if albeit easier to do 14 cards and forget the land unless its a special thing like fate reforged i think you get a dual-like land or some other sets or do the 15th card as a common(but not a land) but thats your call.  Thanks for the site though its awesome.

**Comment by taw** [comment]
The intention is to be as accurate as data we have allows. Many early sets had basics on common sheet ([here's example](https://www.mediafire.com/convkey/7f7e/rav9e0idbi5841c6g.jpg)), it just looks like I messed up which ones did.

**Comment by 7stringplayer** [comment]
I would be more than happy to compile a list of what was in each booster for each set if that would help.

**Comment by taw** [comment]
Yeah, that would be super useful. What I need is list of sets which have basics, but those basics are not in boosters.

**Comment by 7stringplayer** [comment]
ok i found this link which is probably better.  

https://mtg.gamepedia.com/Booster_pack

From Mirage until Coldsnap, booster packs contain fifteen cards:
Eleven commons, three uncommons, and one rare.  There is no land

From Shards forward packs are actually 16 cards which i didnt know but anyway it is all there if you want to look.

**Comment by Meerkov** [comment]
> I also noticed this happened with Alpha as well

This is supposed to happen in Alpha boosters though. Alpha and Beta included lands in the common slot, not in a special land slot. I just posted a bug saying there isn't *enough* lands in the alpha packs, actually.

**Comment by taw** [comment]
I'm going through http://www.lethe.xyz/mtg/collation/index.html one by one and fixing any mismatches. I'm pushing updates as I make them, I'll let you know when it's done.

**Comment by HerveH44** [comment]
@taw let me know how I can know when your rules are updated, I still haven't implemented an automatic update of your rules.

**Comment by taw** [comment]
I think I fixed all issues with common sheets containing or not containing basics. Wiki and The Collation Project disagreed for many sets, so I took The Collation Project and filled gaps with some pack opening videos.

The only known issue left is adding basics to ABUR uncommon/rare sheets.

**Comment by 7stringplayer** [comment]
Awesome

**Comment by 7stringplayer** [comment]
Has it been uploaded into the system yet?

**Comment by HerveH44** [comment]
@ZeldaZach could you relaunch "node scripts/download_booster_rules.js" ?

**Comment by ZeldaZach** [comment]
Done

**Comment by 7stringplayer** [comment]
I just did a pack of Invasion and i got 4 lands?  I dont think its been fixed then

**Comment by HerveH44** [comment]
on what website have you tried? I just tried on dr4ft.info and it works for me

**Comment by 7stringplayer** [comment]
Dr4ft.info

**Comment by HerveH44** [comment]
can you send a screenshot please?

**Comment by 7stringplayer** [comment]
![image](https://user-images.githubusercontent.com/21352581/78942163-bcc95300-7a7e-11ea-99a9-cbbf66b29a1f.png)

**Comment by HerveH44** [comment]
it was only one booster?

Checking on my side, I found that "inv_foils" contain basic lands. Is it normal @taw ?

**Comment by 7stringplayer** [comment]
Still it should be 2 max not 3.  I got 4 in another.  It should be max 2 I
believe.

**Comment by HerveH44** [comment]
have you done only 1 booster or multiple?

**Comment by 7stringplayer** [comment]
now it seems i cant get them to do that.  Maybe it just took a minute.  I'll keep checking.  I'm just opening a pack

**Comment by HerveH44** [comment]
Thank you for your time, when you're at it, check also the rest of the suspicious sets and we'll try to update them too.

**Comment by taw** [comment]
> Checking on my side, I found that "inv_foils" contain basic lands. Is it normal @taw ?

According to [The Collation Project](http://www.lethe.xyz/mtg/collation/inv.html), after introduction of foils, set basics only in non-booster products, would still have foil basics in boosters.

One minor thing I'm aware that I don't currently properly simulate is that initially, foils displaced another card of their rarity (except basic foils replaced common, as there were no basics). So you couldn't get 2nd rare or 4th uncommon as foil.

Right now I have all foils replace commons like in current system.

**Comment by HerveH44** [comment]
Thanks a lot @taw for your dedication, your quick work and your time. Sorry to bother you again with that but is there a way for us to know when you updated your rules in order to fetch as soon as you update them?

**Comment by taw** [comment]
[Github has some notification options](https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github). Is any of that useful?

**Comment by HerveH44** [comment]
issue solved. Again thanks @taw

**Comment by tooomm** [comment]
@HerveH44 I guess he updates his [data repo](https://github.com/taw/magic-sealed-data) right away after he made changes in the [main repo](https://github.com/taw/magic-search-engine) and commits the new data. Is that correct @taw?

Would it be possible to pull the commit hash of his ["pack_factory.rb" file](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/pack_factory.rb)?
Maybe we can store the hash of the newest commit/change to that file (fetch via API?) and check+compare it from time to time to trigger an update.
(Or query the commit history of the data repo directly)

**Comment by taw** [comment]
Yeah, I have a script that exports data from main repo into data repo as jsons.

Could you first check if [any of many github notification options](https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github) are good enough for you?
I could add some hash, but github probably already has something that works just as well.

**Comment by HerveH44** [comment]
Well I don't see how github notifications can help, it's something the server must watch and keep track without needing to have a github account). I don't think github can help with that.

**Comment by taw** [comment]
Is  this useful?

```
$ git ls-remote  https://github.com/taw/magic-sealed-data  master
b781ba398447424459fcdd01a34ee29a561edb32	refs/heads/master
```

Server can check if repo changed without needing any account anywhere.

**Comment by HerveH44** [comment]
Yeah, thanks: I'll work from that

**Comment by taw** [comment]
Or alternatively there's [REST API](https://developer.github.com/v3/git/refs/):

```$ curl   https://api.github.com/repos/taw/magic-sealed-data/git/refs/heads/master
{
  "ref": "refs/heads/master",
  "node_id": "MDM6UmVmMjMzMDc0NDU3Om1hc3Rlcg==",
  "url": "https://api.github.com/repos/taw/magic-sealed-data/git/refs/heads/master",
  "object": {
    "sha": "b781ba398447424459fcdd01a34ee29a561edb32",
    "type": "commit",
    "url": "https://api.github.com/repos/taw/magic-sealed-data/git/commits/b781ba398447424459fcdd01a34ee29a561edb32"
  }
}
```

Anyway, let me know if you need more support.
