### ISSUE TITLE
Disable language option selector when "text-only" is chosen

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#941]
The little term "Card **image** language" will be over-read by some users and they wonder why the oracle card texts are not shown in the selected language.

**Comment by HerveH44** [comment]
I don't know, I don't feel it's a big problem and somehow I don't want to clutter code with a lot of "if" ...

**Comment by ZeldaZach** [comment]
For a one liner, I'm fine with adding it. This is a reasonable thing to me as it could get confusing
