### ISSUE TITLE
LEA + LEB Rare Island

### ISSUE THREAD

**Issue by Meerkov** [dr4fters/dr4ft#945]
There is a chance of an Island in the rare slot for LEA and LEB. It should include an extra possible rare:
"LEA:288"
"LEB:291"

This is because originally, it was supposed to be secret which card was the rare, so including an island in the rare slot would help throw players off.

[[ Good for new contributors! ]]

Just need to add two lines to this file, and adjust the total_weight. https://raw.githubusercontent.com/taw/magic-sealed-data/master/sealed_basic_data.json

**Comment by Meerkov** [comment]
**Additionally:**
The uncommon slot appears that is also has land in it.

**And as for the common slot**: It seems like there is a lot more than 1 copy of each land on the common sheet. Packs rarely have less than 3 basics, and often have 4 or 5.

So, the weights on the LEA/LEB lands need to be adjusted, but I'm not sure to what values. I think just an approximation is that provides packs that look sorta like real packs is fine, and it doesn't need to be perfect.

You can watch a Beta draft here to see what beta boosters look like. Notice 3,4,5,6 and even 7 lands occur. Average maybe around 4: https://www.youtube.com/watch?v=xIVPBUx4zE4

**Comment by ZeldaZach** [comment]
cc: @taw

**Comment by taw** [comment]
This is done now. It makes drafting ABUR super miserable, as you get flood of lands and not enough cards, but it's realistic experience.

**Comment by HerveH44** [comment]
Perfect! Thanks again.
