### ISSUE TITLE
Error when uploading split cards in custom set

### ISSUE THREAD

**Issue by Kumarbis** [dr4fters/dr4ft#960]
When uploading a custom set using the Cockatrice v4 XML format, I'm encountering the following error message:

"the xml submitted is not valid: Cannot read property 'join' of undefined"

When I remove all split cards from the set, the error doesn't occur and I can draft the custom set. I can reproduce the error with the following minimal example, which contains a single split card and nothing else:

https://pastebin.com/zMDq38C0

As far as I'm aware, I'm following the standard format for split cards. Does dr4ft have some extra formatting requirement? I noticed glancing through the code that there seems to be a "names" field that's used somewhere in the backend, so my naive guess is that that has something to do with it.

**Comment by HerveH44** [comment]
Hi, 

Thank you for opening this issue. It's something we haven't worked on (special cards import via XML cockatrice v3) so we still have to figure out how to import them correctly. 

First thing, your XML file doesn't seem exactly as expected by the v3 (https://github.com/Cockatrice/Cockatrice/blob/master/doc/carddatabase_v3/cards.xsd)
I don't see "mainType", "coloridentity" in the XSD so I don't know where they come from. 

It looks like cockatrice may parse their XML with a very specific strategy, we may need to see with them how we could apply the same strategy to our importer.

**Comment by Kumarbis** [comment]
Hi,

Thanks for your reply. Just to clarify, I'm using cockatrice v4, not v3. For comparison, this is the entry for Fire // Ice that appears in the cards.xml file of the most up to date version of Cockatrice:

https://pastebin.com/XRnCgC6D

I've followed the instructions on [this page](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets) to construct the xml - the maintype and coloridentity fields are described there.

**Comment by Kumarbis** [comment]
So I've figured out a "fix," which is that everything seems to work perfectly if I just claim that the layout is 'normal' instead of 'split' - the set uploads without error and split cards appear during the draft exactly as you'd expect.
