### ISSUE TITLE
Draft Results

### ISSUE THREAD

**Issue by 7stringplayer** [dr4fters/dr4ft#962]
Would it be possible when you finish drafting looking at what the other players got when drafting by yourself.  I know that magic online bestiare(i think thats what its  called) posts the results when your finished.  Not a huge deal just more curious than anything.

**Comment by HerveH44** [comment]
Hi, 

I guess right now without a proper bot intelligence it wouldn't make much sense (apart from the fact that we would also need to rethink the UI). 

I would not do it right now, but maybe later when we'll have some good bots.

**Comment by tooomm** [comment]
You mean http://draft.bestiaire.org/?
The page is not available for me currently.

But I remember a service where one could upload a mtgo draft and see all picks everybody did for analysis and discussion.

This would be especially useful when drafting with other humans to see what they picked.

<br>

But probably difficult to do with our current system.

**Comment by 7stringplayer** [comment]
Yes that is the site I was referring to

**Comment by tooomm** [comment]
Maybe check this: https://github.com/dr4fters/dr4ft/pull/96

We have an API which can deliver deck lists. However, I never used the API and honestly don't know if draft.info supports it. @ZeldaZach
