### ISSUE TITLE
Multiple foils of the same type in one pack

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#969]
This might be related/caused to your recent rules updates @taw, can you chime in and check please?

![foils1](https://user-images.githubusercontent.com/9874850/79248597-4f516400-7e7c-11ea-866c-23d847bd83e0.png)
![foils2](https://user-images.githubusercontent.com/9874850/79248599-4fe9fa80-7e7c-11ea-8cc0-89ee62883608.png)
![foils4](https://user-images.githubusercontent.com/9874850/79248605-51b3be00-7e7c-11ea-9391-745dad565501.png)

**Comment by taw** [comment]
[I'm not seeing any double foils at mtg.wtf](https://mtg.wtf/sealed?count%5B%5D=6&set%5B%5D=thb&count%5B%5D=0&set%5B%5D=thb&count%5B%5D=0&set%5B%5D=thb) and it uses the same data, so I guess this is specific to this project?

**Comment by tooomm** [comment]
Hmm, thanks!

It could be a displaying issue of some kind.

**Comment by HerveH44** [comment]
Hi, 

this is definitely a problem of display on our side. I already saw and thought it was fixed. I'll give a second look.

**Comment by HerveH44** [comment]
Ok, I found out the true problem. It's a deep fix as it roots on the way we save cards in the app. I'll produce a PR when I find a satisfying way to deal with it.
