### ISSUE TITLE
Card images are not showing/loading

### ISSUE THREAD

**Issue by DaisyRedRyder** [dr4fters/dr4ft#973]
Just as the title suggests. When starting a draft, some card images take several seconds (10-15 seconds) to load while the counter is counting down, resulting in about 2 cards being invisible per pack. Drafters in the same pod are experiencing similar issues.

**Comment by HerveH44** [comment]
@ZeldaZach I guess we are now DDOSing Scryfall?

**Comment by HerveH44** [comment]
@DaisyRedRyder does it happen with any kind of game or with a specific set ? What set did you use?

**Comment by ZeldaZach** [comment]
I don't think so, we're a very small entity

**Comment by DaisyRedRyder** [comment]
This is with a 360 cube. 4 drafters and 4 bots. The next time we draft, I will ask everyone to turn card image quality to low. I will report back (we likely won't draft again until the end of the week).

**Comment by HerveH44** [comment]
Ok thank you for your quick response. I guess it all depends on your connection mostly, we set the card image quality option to ease with this kind of problems

**Comment by DaisyRedRyder** [comment]
I should probably open another ticket, but we also sometimes have cards load as foreign images instead of English (Especially Nissa, Who Shakes the World and Fellwar Stone).

**Comment by HerveH44** [comment]
Yes, the best would be to take a screenshot of it and indicates the list of the cube and the draft site you used so we can test on our side.

**Comment by DaisyRedRyder** [comment]
So, last night we ran draft. I asked everyone (5 players) to set their card image quality to low, and to set the card language to English. Most of the issues seem to have resolved.
The system still retrieves the "Spanish" card (its the English version with the text "localized image not available") for Fellwar Stone from scryfall.

**Comment by tooomm** [comment]
Looks like scryfall has the correct card art in English. (I didn’t check what the api returns)
https://scryfall.com/card/9ed/297/fellwar-stone

Could browser cache be holding an old, wrong image?

**Comment by HerveH44** [comment]
That's a problem on Scryfall, they are missing some cards sometimes.
