### ISSUE TITLE
Ikoria draft - Common "gain lands" appearing in common slot, but should replace basics

### ISSUE THREAD

**Issue by Milldawg** [dr4fters/dr4ft#978]
The cycle of 10 common dual lands that come in tapped and gain a life are appearing in drafts in the common slot, but in physical booster packs they only appear in the basic land slot. (Not sure about the rate they appear vs. basics, but I've heard something like 50%.)

**Comment by ZeldaZach** [comment]
cc @taw

**Comment by taw** [comment]
Fixed on my side (it was also affecting M19 and M20, and they're also fixed).

**Comment by tooomm** [comment]
Awesome, thanks for the fixes!
