### ISSUE TITLE
Integrate other cube sites as well

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#986]
With the new and awesome cube pull feature via API...
it would be nice to have the biggest site about cubes "Cube Tutor" available, too!

Is there an API available? I just read something in their dev blog, but couldn't find more information.

Maybe you need to reach out if we want to integrate them, @ZeldaZach?
Ben Titmarsh is running the site (https://www.cubetutor.com/contact)

<br>

Are there other important ones? But I feel having Cube Tutor and CubeCobra is solid.

**Comment by ZeldaZach** [comment]
Unfortunately, CubeTutor is on its last legs according to Ben. I don't find this worth our time or efforts, as Cube Cobra is a solid replacement and is under active development. No fix.

**Comment by tooomm** [comment]
Interesting. I agree 👍
