### ISSUE TITLE
Simplify configurations override

### ISSUE THREAD

**Issue by HerveH44** [dr4fters/dr4ft#99]
Use config.js in src directory that will merge default configs with particular config file

**Comment by tooomm** [comment]
Do you want to open a WIP-PR for this to keep better track of it and have a reference to the branch and actual changes?

I assume it's this branch? https://github.com/dr4fters/dr4ft/tree/configuration

**Comment by HerveH44** [comment]
I've been thinking of this problem. It's important to be able to add configuration's variables while staying compatible with past configuration usage. 

Our situation is that we have default configurations variables for server and client, and we give the possibility to any user to change what he wants by rewriting the files. 

Actually at the end of "npm install", during the "postinstall" phase, we check if the configurations' files exist, and if they don't we copy the default. So we always have the default versions in "config/config.server.js.default" (same for client configuration file) and the EFFECTIVE configurations' files in "./config.server.js" and "./config.client.js". 

A problem arises when we add a new variable in the default configuration and then a server updates the project. This variable doesn't get copied, because the effective configurations' files already exist.

I can see different solutions but right now I'd do that:
Try to merge at runtime the configurations from both server and client. That means that the client's configuration doesn't get compiled, meaning in the end that all the informations of the config get passed to the client by the Websocket. Which means more traffic, especially of static informations (name of the site ...)

@ZeldaZach @dev-id @tooomm what do you think?

**Comment by HerveH44** [comment]
My idea is impossible yet because of the client config file: there can be React components inside, so it's impossible to have it pushed to frontend ...

**Comment by ZeldaZach** [comment]
My idea is to try and do a "merge" of the files, and then if it fails offer a solution similar to how apt does it (open a shell to investigate, view diff, use yours, use maintainers)

**Comment by HerveH44** [comment]
Do you know any good JS library that could merge files ?

I feel a bit insecured about trying to merge 2 JS files ...

**Comment by HerveH44** [comment]
I don't know if anyone is still using our repository for personal projects. In order to "simplify" the configurations I'd like to rewrite all the configuration using env variables and start from there. 

@ZeldaZach @tooomm do you know anybody using this project ?

That would imply breaking the current configuration style. I really don't want to keep the configuration files as they are now, that really look odd.

**Comment by ZeldaZach** [comment]
Fee free to change and we’ll bump to 1.0.0 soon

**Comment by HerveH44** [comment]
@ZeldaZach How do you like the possibility to modify freely the file "config.client.js" ? I'm wondering about just commiting the informations to the repository as a real file. How would you feel about it?

**Comment by ZeldaZach** [comment]
Up to you. As long as there is no privileged/confidential information in it were fine.

**Comment by HerveH44** [comment]
@ZeldaZach could you copy the config.server.js of your server? If there is confidential data, just indicate it (like <MYPASSWD...>) just to know what could be directly implemented in the project and what should be open to override. Thanks

**Comment by HerveH44** [comment]
@ZeldaZach hi, sorry to bother again but I'm working on the config rewrite and I really need to know what does your config.server.js look like. Without it, I may delete or keep configurations that nobody needs.

For example I want to directly add your paypal (if there's no personal information on it) or add the possibility to overwrite it. And I'd like also to write the changelog in the code (or find a way to scrap these informations from elsewhere)

**Comment by ZeldaZach** [comment]
I swear I sent it to ya on a Discord. Reach out there for more chatting :)
