### ISSUE TITLE
"invalid cards: lurrus of the dream-den"

### ISSUE THREAD

**Issue by slumberspirit** [dr4fters/dr4ft#991]
Hi, dr4ft is telling me Lurrus of the Dream-Den is an invalid card. (Note I was fetching a cube from Cube Cobra containing that card.)

**Comment by HerveH44** [comment]
Hi @slumberspirit , thanks for reaching out. Could you indicate the cubeId you used ?

**Comment by slumberspirit** [comment]
Tried it with a few and encountered the same issue. One was: wtwlf123

**Comment by HerveH44** [comment]
Yeah, I guess it's because it's written differently in MTGJson : the card's name is "Lurrus of the Dream Den" not "Lurrus of the Dream-Den"

**Comment by tooomm** [comment]
Regarding Scryfall `Lurrus of the Dream-Den` is correct and MTGJSON has it wrong then:
https://scryfall.com/card/iko/226/lurrus-of-the-dream-den

(Cockatrice shows the same issue)

**Comment by ZeldaZach** [comment]
Will be fixed with tonight's rebuild.

**Comment by HerveH44** [comment]
@slumberspirit this has been fixed by the new MTGJson version
