### ISSUE TITLE
Missing draft modes

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#996]
Next to #919, which requested "Rich Man's Draft", there are two famous & fun draft formats also missing:

- [x] Rich Man's Draft (#990)

- [ ] Rochester Draft

- [ ] Winston Draft

"Grab a Bag" Draft and Sealed options, where every player chooses a pack (set) for all group. would only be possible when sets can be changed from within an already created room.

**Comment by HerveH44** [comment]
> "Grab a Bag" Draft and Sealed options, where every player chooses a pack (set) for all group. would only be possible when sets can be changed from within an already created room.

That does not seem impossible. I would prefer an issue for each game mode with exhaustive explanation and link to other resources in order to fully understand how they should be played.

**Comment by ZeldaZach** [comment]
Agreed w/ Herve. These should be split up.

**Comment by tooomm** [comment]
Ok, sure. I get your point. Will open separate issues and try to keep that in mind. 👍
